export default [
  // ===== BLASER SWISSLUBE =====
  {
    productName: "Blasocut 2000 CF",
    manufacturerName: "Blaser Swisslube",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Hartnaeckiger Geruch an den Haenden nach laengerer Exposition",
    description: "Mehrere Anwender berichten ueber einen penetranten Geruch an den Haenden, der sich auch durch Waschen nicht entfernen laesst und 4-6 Stunden anhaelt. Tritt besonders bei laengerer Schichtdauer mit Blasocut 2000 CFSW auf.",
    symptoms: ["Geruch an Haenden", "Geruch bleibt 4-6h"],
    rootCause: "Vermutlich Reaktion zwischen Bioloegischer Aktivitaet im Sumpf und Hautflora",
    workaround: "Handschuhe, Hautschutzcreme, Sumpfpflege intensivieren",
    preventiveMeasure: "Regelmaessige pH- und Konzentrationskontrolle, Tramp-Oil-Skimmer",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-coolant-blasocut-2000-bc935sw.290221/",
    sourceTitle: "Blaser coolant. Blasocut 2000 / BC935SW",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasocut 2000 CF",
    manufacturerName: "Blaser Swisslube",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Braune oeligen Rueckstaende (brown goop) an Maschine",
    description: "Anwender berichten von braunen, klebrigen Rueckstaenden an Maschinen bei Blasocut 2000MD; ein Anwender stieg nach 17 Jahren Blasocut-Treue auf einen Wettbewerber um, weil alle Maschinen extrem klebrige oelige Rueckstaende entwickelten.",
    symptoms: ["Braune Verfaerbung", "Klebrige Rueckstaende", "Schwer abwaschbar"],
    rootCause: "Akkumulation von oxidierten Mineraloel-Komponenten und Tramp-Oil-Eintrag",
    workaround: "Maschine reinigen, Tramp-Oil entfernen, Konzentration pruefen",
    preventiveMeasure: "Sumpfumwaelzung, Tramp-Oil-Skimming, Bandfilter pflegen",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-coolant-blasocut-2000-bc935sw.290221/",
    sourceTitle: "Blaser coolant. Blasocut 2000 / BC935SW",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasocut 2000 Universal",
    manufacturerName: "Blaser Swisslube",
    category: "FILTRATION",
    severity: "MEDIUM",
    title: "Hoher Tramp-Oil-Eintrag und Atemwegsreizungen nach 2 Jahren Einsatz",
    description: "Nach mehrjaehrigem Einsatz von Blasocut 2000 Universal berichten Anwender ueber stark steigenden Tramp-Oil-Anteil und damit einhergehende Atemwegsreizung. Wenn die Anlage laenger steht, separiert die Emulsion und der obere Belag wird ranzig - auch Abskimmen rettet nicht mehr.",
    symptoms: ["Tramp-Oil", "Geruch", "Atemwegsreizung"],
    rootCause: "Hydrauliklecks/Tramp-Oil-Eintrag stoeren die bakteriostatische Wirkung des Bio-Konzepts",
    workaround: "Tramp-Oil-Skimmer, Sumpfumwaelzung am Wochenende",
    preventiveMeasure: "Hydrauliklecks beheben, regelmaessige Skimmer-Wartung",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/source-for-blasocut-2000-universal.185894/",
    sourceTitle: "Source for Blasocut 2000 Universal",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasocut 4000 Strong",
    manufacturerName: "Blaser Swisslube",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Verklebung von Maschinentueren durch Restfilm",
    description: "Anwender berichten, dass Blasocut 4000 Strong LF in CNC-Maschinen klebrig wird (gummy) und die Tueren nicht mehr frei laufen. Empfehlung aus dem Forum: Wechsel auf demineralisiertes Wasser bei Ansatz statt Leitungswasser.",
    symptoms: ["Klebrige Rueckstaende", "Schwergaengige Tueren"],
    rootCause: "Hartes Leitungswasser fuehrt zu Seifenbildung mit den Inhibitoren",
    workaround: "DI-Wasser fuer Ansatz und Nachfuellung",
    preventiveMeasure: "Wasserhaerte messen, ggf. Umkehrosmose installieren",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blasocut-4000-strong-lf.371720/",
    sourceTitle: "Blasocut 4000 Strong LF",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasocut 4000 Strong",
    manufacturerName: "Blaser Swisslube",
    category: "CORROSION",
    severity: "HIGH",
    title: "Lichter Flugrost auf Box-Ways bei Blasocut BC40",
    description: "Anwender mit 9 Bedienern und 15 Maschinen berichtet von leichten Rost-Flecken (Oxidation) auf Maschinen-Box-Ways nach ca. 1 Jahr Einsatz mit Blasocut BC40SW. Manche Maschinen stehen 2 Wochen ungenutzt. Loesung war hoehere Konzentration (ca. 8% war zu wenig).",
    symptoms: ["Flugrost", "Verfaerbung Fuehrungsbahnen"],
    rootCause: "Bei Stillstand und niedriger Konzentration unzureichender Korrosionsschutz",
    workaround: "Konzentration hochfahren auf >8%, Maschinen bei Stillstand pflegen",
    preventiveMeasure: "Wochen-Refraktometer-Kontrolle, Standzeit-Programm bei Stillstand",
    reportedConcentration: 8.0,
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-coolant-box-way-rust.403344/",
    sourceTitle: "Blaser Coolant & Box Way Rust",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasocut 4000 Strong",
    manufacturerName: "Blaser Swisslube",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Separation im Sumpf bei laengerem Stillstand",
    description: "Blaser hat den Ruf, im Tank ueber Zeit zu separieren. Bei Maschinen, die laenger ungenutzt sind, schwimmt eine Schicht oben auf, die ranzig wird. Empfehlung: nie nur Wasser oder Konzentrat nachfuellen, sondern stets aus vorgemischter Charge.",
    symptoms: ["Separation", "Oberflaechenfilm", "Geruch"],
    rootCause: "Stillstand und falsche Nachfuelltechnik destabilisieren Emulsion",
    workaround: "Vormix-Tank etablieren, regelmaessige Umwaelzung",
    preventiveMeasure: "Vormix-Behaelter, Wochenend-Pumpenprogramm",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blasocut-bc40-coolant-anyone-use.220935/",
    sourceTitle: "Blasocut BC40 Coolant - Anyone use?",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "B-Cool 755",
    manufacturerName: "Blaser Swisslube",
    category: "FOAM",
    severity: "HIGH",
    title: "Extremes Schaeumen beim Schleifen von Silizium und Glas",
    description: "Anwender berichtet von unglaublichem Schaeumen mit B-Cool 755 beim Schleifen harter Materialien (Silizium, Glas). Trotz Hersteller-Empfehlung 10-15% Brix muss die Konzentration auf 2-3% gesenkt werden, um Schaum zu vermeiden - dann beginnt das KSS aber nach ca. 1 Woche zu riechen.",
    symptoms: ["Schaum", "Geruch bei niedriger Konzentration"],
    rootCause: "Schleif-Mikropartikel zerschlagen Emulsion + zu hohe Drueckung der Tensidsysteme",
    workaround: "Konzentration auf 2-3% reduzieren, oder Entschaeumer dosieren",
    preventiveMeasure: "Anwendungs-spezifisches Konzept vom Hersteller anfordern",
    reportedConcentration: 2.5,
    affectedMaterials: ["Silizium", "Glas"],
    affectedOperations: ["Schleifen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anyone-running-blaser-b-cool-755.343739/",
    sourceTitle: "Anyone running Blaser B-COOL 755?",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "B-Cool 755",
    manufacturerName: "Blaser Swisslube",
    category: "FILTRATION",
    severity: "MEDIUM",
    title: "Schwierige Schlamm-Abscheidung in Zentrifuge bei 7-10% Konzentration",
    description: "Bei Konzentrationen von 7-10% hat das KSS Probleme, den Schleifschlamm in der Zentrifuge abzuscheiden. Bei 2% riecht das KSS, bei hoeherer Konzentration scheidet es schlecht.",
    symptoms: ["Schlechte Schlammabscheidung", "Zentrifuge ueberlastet"],
    rootCause: "Tensidsystem bindet Feinstpartikel zu stark",
    workaround: "Konzentrations-Fenster mit Hersteller abstimmen",
    preventiveMeasure: "Anwendungs-Audit Blaser-Service",
    reportedConcentration: 8.5,
    affectedMaterials: [],
    affectedOperations: ["Schleifen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anyone-running-blaser-b-cool-755.343739/",
    sourceTitle: "Anyone running Blaser B-COOL 755?",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "B-Cool 755",
    manufacturerName: "Blaser Swisslube",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Bakterien-Outbreak im Sommer nach 4 Jahren Aluminiumbearbeitung",
    description: "Ein Anwender betrieb B-Cool 755 vier Jahre stabil in Aluminiumbearbeitung, hatte dann im Sommer einen Bakterien-Outbreak. Danach blieb dauerhaft ein Restgeruch und Atemwegsreizungen bei den Bedienern.",
    symptoms: ["Bakterien-Outbreak", "Restgeruch", "Atemwegsreizung"],
    rootCause: "Sommerliche Temperaturen + verminderte Sumpfumwaelzung beguenstigen Keime",
    workaround: "Stossbiozid, Teilumtausch",
    preventiveMeasure: "Sommer-Wartungsprogramm, Bio-Monitoring",
    affectedMaterials: ["Aluminium"],
    affectedOperations: ["Fraesen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anyone-running-blaser-b-cool-755.343739/",
    sourceTitle: "Anyone running Blaser B-COOL 755?",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 735",
    manufacturerName: "Blaser Swisslube",
    category: "CORROSION",
    severity: "HIGH",
    title: "Korrosion und Pitting auf Maschinen / Werkstuecken",
    description: "Mehrere Anwender berichten ueber Korrosionsprobleme mit Synergy 735, teilweise mit rapider Lochfrass-Bildung. Eine Analyse weist auf interstitielle Chlorid-Ionen als Ursache hin. Blaser sei das Problem bekannt.",
    symptoms: ["Lochfrass", "Rost", "Verfaerbung"],
    rootCause: "Chlorid-Ionen-Eintrag plus aggressive Inhibitor-Chemie (Carbonsaeuren)",
    workaround: "Wechsel auf DI-Wasser, ggf. Konzentration erhoehen",
    preventiveMeasure: "DI-Wasser strikt vorschreiben, Konzentrationskontrolle",
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-synergy-735-and-rust.368130/",
    sourceTitle: "Blaser Synergy 735 and Rust",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 735",
    manufacturerName: "Blaser Swisslube",
    category: "PERFORMANCE",
    severity: "HIGH",
    title: "Geringe Schmierfaehigkeit beim Formgewinden in Aluminium",
    description: "Anwender berichten, dass beim Formgewinden in Aluminium die Formgewindebohrer brechen, weil Synergy 735 kaum Schmierwirkung hat. Aluminiumspaene bleiben in den Werkzeugen stecken. KSS fuehlt sich nicht 'oelig' an wie Mineraloel-basierte Fluids.",
    symptoms: ["Werkzeugbruch", "Spaene kleben am Werkzeug"],
    rootCause: "Vollsynthetische Formulierung ohne EP-/Lubrizitaets-Additive",
    workaround: "MMS-Zusatzschmierung beim Gewinden, ggf. anderes KSS fuer diese Operation",
    preventiveMeasure: "Alternativ-KSS fuer Form-Tap-Operationen",
    affectedMaterials: ["Aluminium"],
    affectedOperations: ["Formgewinden"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-recommendations-for-copper-and-alum-currently-using-blaser-synergy-735.410024/",
    sourceTitle: "Coolant recommendations for Copper and Alum, currently using Blaser Synergy 735",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 735",
    manufacturerName: "Blaser Swisslube",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Schleimige Rueckstaende und dicke Tropfen-Verkrustungen",
    description: "Anwender berichten, dass Synergy 735 ueberall schleimige Rueckstaende hinterlaesst; Tropfen verharren als dicke Blobs an der Maschine. Vertriebsmitarbeiter hat das Problem bestaetigt - eine neue Version sei in Vorbereitung.",
    symptoms: ["Schleimige Rueckstaende", "Klebrige Tropfen-Verkrustungen"],
    rootCause: "Carbonsaeure-/Alkanolamin-Konzentrationen bilden bei Eintrocknung Seifen",
    workaround: "Regelmaessige Maschinenreinigung",
    preventiveMeasure: "DI-Wasser + Kontaktzeit verkuerzen",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/new-clear-blaser-synergy-735-coolant.357860/",
    sourceTitle: "New clear Blaser Synergy 735 coolant?",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 735",
    manufacturerName: "Blaser Swisslube",
    category: "SEAL_DAMAGE",
    severity: "HIGH",
    title: "Zersetzung von Way-Cover-Abstreifern aus Kunststoff",
    description: "Nach knapp 4 Jahren Einsatz zersetzen sich die Kunststoff-Abstreifer der Way-Covers an mehreren Stellen der Maschine. Auch Dichtungen, Bumper, Gummi-Teile und verzinkte Komponenten werden angegriffen; Zink wird unter Bildung gelber/weisser Rueckstaende abgetragen.",
    symptoms: ["Bruechige Abstreifer", "Angegriffene Dichtungen", "Gelbe/weisse Salze an Zink"],
    rootCause: "Alkanolamine/Carbonsaeuren greifen Polymere und Zink an",
    workaround: "Wechsel auf Alternativ-KSS, Zink-Bauteile beschichten",
    preventiveMeasure: "Werkstoff-Vertraeglichkeitstest vor Einfuehrung",
    affectedMaterials: ["Zink", "Kunststoff"],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-synergy-735-coolant-and-impact-on-waycover-plastic-wipers.400734/",
    sourceTitle: "Blaser Synergy 735 coolant and impact on waycover plastic wipers",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 735",
    manufacturerName: "Blaser Swisslube",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Gesundheitliche Beschwerden / Hautreizung",
    description: "In einem deutschen Industrieforum berichten Anwender ueber Hautprobleme und Beschwerden mit Synergy 735.",
    symptoms: ["Hautreizung"],
    rootCause: "Mehrere Inhaltsstoffe (Alkanolamine, Isothiazolinone) sind potenzielle Sensibilisatoren",
    workaround: "Hautschutzplan, ggf. Produktwechsel",
    preventiveMeasure: "Bedienerschulung, Hautschutz nach TRGS 401",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://de.industryarena.com/forum/blaser-swisslube-synergy-735-erfahrungen--84981.html",
    sourceTitle: "Blaser Swisslube Synergy 735 Erfahrungen ?",
    language: "DE",
    isOfficial: false,
  },
  {
    productName: "Vasco 5000",
    manufacturerName: "Blaser Swisslube",
    category: "BIOLOGY",
    severity: "HIGH",
    title: "Geruchsbildung im Fass / im Sumpf",
    description: "Anwender berichten ueber stinkenden Vasco 5000. Die Produktgeneration wird als alt beschrieben - sogar im Fass nur 2-3 Jahre haltbar. Empfohlene Loesung: Blaser-Service kontaktieren oder Wechsel zu Nachfolgeprodukt.",
    symptoms: ["Geruch", "Bakterienbefall"],
    rootCause: "Aelteres Produkt mit alterungsanfaelliger Konservierung; geringe Konzentration verschaerft Problem",
    workaround: "Konzentration erhoehen, Biozid-Stoss",
    preventiveMeasure: "Wechsel zum Nachfolge-Produkt, Lagerdauer < 2 Jahre",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/smelly-vasco-5000.432655/",
    sourceTitle: "Smelly vasco 5000",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Vasco 5000",
    manufacturerName: "Blaser Swisslube",
    category: "SHELF_LIFE",
    severity: "MEDIUM",
    title: "Begrenzte Lagerstabilitaet im Originalgebinde (2-3 Jahre)",
    description: "Forumshinweis (auch vom Distributor bestaetigt): Vasco 5000 ist im Fass nur 2-3 Jahre haltbar, danach koennen mikrobielle Probleme schon vor Anmischen auftreten.",
    symptoms: ["Geruch im Konzentrat"],
    rootCause: "Konservierungsmittel altern",
    workaround: "Lagerbestand begrenzen, Charge vor Verwendung sensorisch pruefen",
    preventiveMeasure: "FIFO-Lagerhaltung, max. 24 Monate",
    affectedMaterials: [],
    affectedOperations: [],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/smelly-vasco-5000.432655/",
    sourceTitle: "Smelly vasco 5000",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Vasco 6000",
    manufacturerName: "Blaser Swisslube",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Schaumprobleme bei langen Zykluszeiten (10+ Stunden)",
    description: "Anwender berichtet auf Practical Machinist von Schaumproblemen mit Vasco 6000 (neben SW20 und Quali Chem 251), insbesondere bei langen Zykluszeiten ueber 10 Stunden.",
    symptoms: ["Schaum"],
    rootCause: "Lange Zykluszeit + weiches Wasser foerdert Schaumbildung",
    workaround: "Calciumacetat zur Wasserhaerte-Anpassung (Blaser-Empfehlung)",
    preventiveMeasure: "Wasserhaerte ueberwachen, ggf. Antischaum",
    affectedMaterials: [],
    affectedOperations: ["Fraesen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-recomendations.394348/",
    sourceTitle: "Coolant Recomendations",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Vasco 6000",
    manufacturerName: "Blaser Swisslube",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Anwender verschenkt Vasco 6000-Fass nach Unbrauchbarkeit",
    description: "Anwender bietet im Forum sein Vasco 6000 'gratis' an - Hinweis darauf, dass die Charge fuer den eigenen Einsatzfall nicht brauchbar war. Praxisbeleg fuer Anwendungs-Sensitivitaet (Wasserhaerte, Druck).",
    symptoms: ["Anwendungs-Probleme"],
    rootCause: "Wahrscheinlich Wasserhaerte/Druckverhaeltnisse",
    workaround: "Blaser-Service einbinden",
    preventiveMeasure: "Vor Einfuehrung Pilotversuch mit Werkswasser",
    affectedMaterials: [],
    affectedOperations: [],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/vasco-6000-coolant-to-give-for-free.408242/",
    sourceTitle: "Vasco 6000 coolant to give for free",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Vasco 1000",
    manufacturerName: "Blaser Swisslube",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Geruchsbildung bei zu niedriger Konzentration",
    description: "Geruchsprobleme mit Vasco-Reihe (inkl. Vasco 1000) werden auf Bakterien/Mikroben zurueckgefuehrt; Betrieb unter empfohlener Konzentration foerdert dies. Vasco 1000 wurde mittlerweile vom Hersteller durch Vasco 5000 abgeloest.",
    symptoms: ["Geruch", "Bakterien"],
    rootCause: "Unterdosierung schwaecht Konservierung",
    workaround: "Konzentration auf 10% halten",
    preventiveMeasure: "Refraktometer woechentlich, Konzentrationsfenster einhalten",
    reportedConcentration: 8.0,
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-vasco-7000-coolant-questions.247427/",
    sourceTitle: "Blaser Vasco 7000 coolant questions",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasomill GT 22",
    manufacturerName: "Blaser Swisslube",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Hoher Oelverbrauch beim Aluminium-Drehen durch oelbenetzte Spaene",
    description: "Anwender mit Tsugami-Langdrehmaschine berichtet, dass beim Bearbeiten von Aluminium 6061 mit Blasomill GT 22 ein 208-Liter-Vorrat innerhalb von 12-14 Tagen aufgebraucht wurde. Die langen Aluminiumspaene tragen das Oel mit ab. Spanwagenlagerung zur Rueckgewinnung half nur begrenzt.",
    symptoms: ["Hoher Oelverbrauch", "Oeliger Spanaustrag"],
    rootCause: "Lange duktile Spaene transportieren Oel aus dem System",
    workaround: "Span-Zentrifuge, Span-Abtropf-Behaelter",
    preventiveMeasure: "Investition in Zentrifuge bei hohem Oel-Durchsatz",
    affectedMaterials: ["Aluminium", "AlMgSi (6061)"],
    affectedOperations: ["Langdrehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/aluminium-scrap-and-oil-issue.399360/",
    sourceTitle: "Aluminium Scrap and Oil Issue",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Blasomill GT 22",
    manufacturerName: "Blaser Swisslube",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Anwendungs-Hinweise und Erfahrungsaustausch zum Erstbetrieb",
    description: "Erfahrungs-Thread fuer Erstanwender von Blaser-Schneidoelen (Swiss/Oil): Hinweise zu Konzentration, Spankontrolle, Rezeptur-Anpassung an Material.",
    symptoms: ["Bearbeitungsoptimierung noetig"],
    rootCause: "Optimierung benoetigt Anwendungs-Know-how",
    workaround: "Blaser-Service hinzuziehen",
    preventiveMeasure: "Schulung der Bediener",
    affectedMaterials: [],
    affectedOperations: ["Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/new-to-swiss-oil.349075/",
    sourceTitle: "New to Swiss/Oil",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "B-Cool 9665",
    manufacturerName: "Blaser Swisslube",
    category: "STABILITY",
    severity: "LOW",
    title: "Diskussion ueber Stabilitaet bei aelteren Maschinen mit schwacher Pumpe",
    description: "In einem IndustryArena-Thread wird ueber B-Cool 665/9665 diskutiert; einige Anwender weisen auf moegliche Stabilitaetsprobleme bei aelteren Maschinen mit schwachen Kuehlmittelpumpen hin (geringe Umwaelzung).",
    symptoms: ["Sedimentation", "Geruch"],
    rootCause: "Schwache Umwaelzung beguenstigt Separation/Bakterien",
    workaround: "Umwaelz-Pumpe verstaerken, Umwaelzprogramm im Stillstand",
    preventiveMeasure: "Bei Retrofit Pumpenleistung pruefen",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://de.industryarena.com/forum/blaser-b-cool-665--18388.html",
    sourceTitle: "Blaser B-Cool 665 - Hat da jemand Erfahrungen?",
    language: "DE",
    isOfficial: false,
  },
  {
    productName: "Blasocut BC 25 MD",
    manufacturerName: "Blaser Swisslube",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Empfehlung fuer Kupfer/Zink-Bearbeitung (Hinweis auf Eingrenzung)",
    description: "Im Forum wird BC 25 MD als bessere Wahl als andere Blasocut-Varianten fuer Kupfer und Zink beschrieben. Implizit: Andere Varianten (z.B. 4000 Strong) sind fuer Buntmetall weniger geeignet und koennen Flecken verursachen.",
    symptoms: ["Buntmetall-Flecken bei Alternativ-Produkt"],
    rootCause: "EP-Additive in Standard-Produkten greifen Buntmetalle an",
    workaround: "Produktwahl nach Material",
    preventiveMeasure: "Materialspezifische KSS-Auswahl",
    affectedMaterials: ["Kupfer", "Zink", "Buntmetalle"],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-recommendations-for-copper-and-alum-currently-using-blaser-synergy-735.410024/",
    sourceTitle: "Coolant recommendations for Copper and Alum",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Synergy 915",
    manufacturerName: "Blaser Swisslube",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Hohe Konzentrationen organischer Saeuren - Korrosionsrisiko diskutiert",
    description: "In einer Forum-Analyse wird angemerkt, dass Synergy 915 hohe Konzentrationen an Triethanolamin, Alkanolaminen und Carbonsaeuren enthaelt. Diese koennen unter ungeguenstigen Bedingungen Korrosion verursachen (Vergleich mit Synergy-735-Erfahrungen).",
    symptoms: ["Potenzielles Korrosionsrisiko"],
    rootCause: "Hohe Konzentration von organischen Saeuren und Alkanolaminen",
    workaround: "DI-Wasser, hohe Konzentration halten",
    preventiveMeasure: "Wasserchemie-Audit",
    affectedMaterials: ["Stahl", "Verzinkte Bauteile"],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-synergy-735-and-rust.368130/page-2",
    sourceTitle: "Blaser Synergy 735 and Rust (Diskussion zu 915)",
    language: "EN",
    isOfficial: false,
  },
  {
    productName: "Vasco 7000",
    manufacturerName: "Blaser Swisslube",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Schaum bei Hochdruck-Kuehlung in weichem Bergwasser",
    description: "Fallstudie aus der Luftfahrt: Module mit leistungsstarken Wassersystemen hatten mit Vasco 7000 Probleme, weil weiches Bergwasser bei 70 bar Schaum erzeugte. Blaser entwickelte eine spezielle Formel mit Calciumacetat zur Haerteanpassung.",
    symptoms: ["Schaum bei Hochdruck", "Stabilitaetsprobleme"],
    rootCause: "Sehr weiches Wasser + hoher Druck destabilisieren Emulsion",
    workaround: "Calciumacetat-Zugabe zur Haerteanpassung",
    preventiveMeasure: "Wasserhaerte testen, ggf. Aufhaerten",
    reportedConcentration: 8.0,
    affectedMaterials: ["Titan"],
    affectedOperations: ["Hochdruck-Fraesen"],
    sourceType: "CASE_STUDY",
    sourceUrl: "https://www.aerospacemanufacturinganddesign.com/article/fighting-the-foam/",
    sourceTitle: "Fighting the foam - Aerospace Manufacturing and Design",
    language: "EN",
    isOfficial: false,
  },

  // ===== CARL BECHEM =====
  {
    productName: "Avantin 361",
    manufacturerName: "Carl Bechem",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Formaldehyd-Depot-Aenderung der Formulierung (I-N)",
    description: "Carl Bechem hat Avantin 361 in der Variante 'I-N' explizit frei von Formaldehyd-Depot-Stoffen formuliert - Hinweis darauf, dass die fruehere Variante diese kritischen Konservierungsmittel (TRGS-611-relevant) enthielt.",
    symptoms: ["Regulatorische Anpassung"],
    rootCause: "Formaldehyd-Depots wegen TRGS 611 und Sensibilisierungs-Risiko ungeliebt",
    workaround: "I-N-Variante verwenden",
    preventiveMeasure: "Auf Variante I-N achten",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.bechem.us/en/products/water-miscible-cooling-lubricants/bechem-avantin-361-i-n.html",
    sourceTitle: "BECHEM Avantin 361 I-N - Water-miscible cooling lubricants",
    language: "EN",
    isOfficial: true,
  },
  {
    productName: "Avantin 361",
    manufacturerName: "Carl Bechem",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "Hinweis auf 1,2-Benzisothiazol-3(2H)-on im SDS (Sensibilisator)",
    description: "Im SDS und Produkthandbuch wird der Konservierer 1,2-Benzisothiazol-3(2H)-on (BIT) als moegliches Allergen genannt. Diese Information ist relevant fuer Bediener mit bekannter Sensibilisierung.",
    symptoms: ["Hautsensibilisierung moeglich"],
    rootCause: "BIT als sensibilisierender Konservierungsstoff",
    workaround: "Handschutz, Bediener mit Allergie ausschliessen",
    preventiveMeasure: "Hautschutzplan TRGS 401",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "SDS",
    sourceUrl: "https://www.scribd.com/document/414435633/MSDS-of-Bechem-Avantin",
    sourceTitle: "MSDS of Bechem Avantin",
    language: "EN",
    isOfficial: true,
  },

  // ===== HEBRO CHEMIE =====
  {
    productName: "Hebrocut HEB 1200",
    manufacturerName: "Hebro Chemie",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Trockenes Ekzem mit Hautrissen / Blutungen",
    description: "In einem deutschen Industrieforum berichten Anwender ueber 'trockenes Ekzem' bei Arbeit mit Hebro-KSS - Haut riss an mehreren Stellen auf und blutete. Mehrere Anwender berichten von Hautausschlaegen.",
    symptoms: ["Trockenes Ekzem", "Hautrisse", "Blutungen"],
    rootCause: "Borsaeure (ca. 8% in der Standard-Rezeptur) plus Alkalitaet trocknen Haut aus",
    workaround: "Sofort Hautschutz/Pflege, ggf. Produktwechsel",
    preventiveMeasure: "Borreduzierte Variante (Bezeichnung mit 'B' im Code, z.B. HB1400B); strikter Hautschutz",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://de.industryarena.com/forum/kss-der-firma-hebro--50386.html",
    sourceTitle: "KSS der Firma HEBRO",
    language: "DE",
    isOfficial: false,
  },
  {
    productName: "Hebrofluid Plus",
    manufacturerName: "Hebro Chemie",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Hoher Borsaeure-Gehalt (~8%) - regulatorisch heikel",
    description: "Laut Aussage eines ehemaligen Hebro-Vertreters enthalten alle Hebro-KSS ca. 8% Borsaeure. Borsaeure ist als reproduktionstoxisch (SVHC) klassifiziert; ab 5,5% besteht Kennzeichnungspflicht. Reduzierte Variante: Bezeichnungs-Endung 'B'.",
    symptoms: ["SVHC-Kennzeichnungspflicht", "Anwender-Bedenken"],
    rootCause: "Hoher Borsaeure-Gehalt zur Stabilisierung",
    workaround: "Wechsel auf 'B'-Variante mit reduziertem Bor",
    preventiveMeasure: "Bei Neueinfuehrung borfreie Alternative bevorzugen (REACH-CMR-Aspekt)",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://de.industryarena.com/forum/kss-der-firma-hebro--50386.html",
    sourceTitle: "KSS der Firma HEBRO",
    language: "DE",
    isOfficial: false,
  },
  {
    productName: "SE 22 KSS",
    manufacturerName: "Hebro Chemie",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Hautirritationen einzelner Bediener trotz problemloser Mehrheit",
    description: "Anwender, die von anderen Marken auf Hebrosol (Hebro) gewechselt sind, hatten selber keine Probleme - aber einzelne Mitarbeiter zeigten weiterhin Hautreaktionen. Hinweis auf individuelle Sensibilisierung gegen Hebro-Inhaltsstoffe.",
    symptoms: ["Einzelne Hautirritationen"],
    rootCause: "Individuelle Sensibilisierung (Borsaeure, Konservierer)",
    workaround: "Versetzung sensibilisierter Mitarbeiter, Hautschutzplan",
    preventiveMeasure: "Pre-Employment-Patchtest in kritischen Bereichen",
    affectedMaterials: [],
    affectedOperations: ["Fraesen", "Drehen"],
    sourceType: "FORUM",
    sourceUrl: "https://de.industryarena.com/forum/kss-der-firma-hebro--50386.html",
    sourceTitle: "KSS der Firma HEBRO",
    language: "DE",
    isOfficial: false,
  },

  // ===== REGULATORY / ALLGEMEIN (Hinweis: nur eintragen wenn Quelle Produkt nennt) =====
  // - Hier nicht eintragen, weil TRGS-611-Quellen die hier gelisteten Produkte
  //   nicht namentlich erwaehnen.
];
