export default [
  // ===== Castrol Hysol MB 50 =====
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Wart-like Hautwucherungen an Fingern bei MB-50-Bedienern (Forum-Bericht)",
    description: "Werkstattbericht: Drei Operatoren, die ausschliesslich an einer bestimmten Maschine mit Castrol Hysol MB-50 arbeiteten, entwickelten warzenartige, nicht-juckende Hautwucherungen an den Fingern. In allen anderen Maschinen derselben Shop wurde der gleiche Coolant ohne Probleme verwendet, was auf eine Wechselwirkung mit Maschinenkontamination oder bestimmten Werkstoffen hindeutet.",
    symptoms: ["Wart-like Hautwucherungen", "Hautirritation an Fingern"],
    rootCause: "Möglicher Bakterien-Durchwuchs in einzelner Maschine; HPV-ähnliche Reaktion oder allergische Kontaktdermatitis durch Coolant + Maschinenkontamination",
    workaround: "Coolant separat in betroffener Maschine wechseln, vollständige Maschinenreinigung, Konzentration und pH kontrollieren",
    preventiveMeasure: "Regelmässige mikrobiologische Tests, pH- und Konzentrationsmonitoring, persönliche Schutzhandschuhe",
    affectedMaterials: [],
    affectedOperations: ["CNC-Drehen", "CNC-Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/castrol-hysol-mb-50-problems.225737/",
    sourceTitle: "Castrol Hysol MB-50 Problems",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2011-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Hautverbrennungen und Ausschlag innerhalb weniger Tage",
    description: "Forumsmitglied berichtet, dass Castrol MB-50 seine Haut verbrennt und er innerhalb weniger Tage Ausschlag entwickelt. Trägt durchgehend Handschuhe, die wegen scharfer Späne häufig ausgetauscht werden müssen. Hinweis auf individuelle Sensibilisierung bei mehrjähriger Exposition.",
    symptoms: ["Hautverbrennung", "Ausschlag", "Kontaktdermatitis"],
    rootCause: "Alkalische Coolant-Additive, mögliche MEA/Aminkomponenten, Hautentfettung durch Tenside",
    workaround: "Nitril-Handschuhe (klassifiziert oil-resistant), Barrier-Cream, sofortiges Abwaschen",
    preventiveMeasure: "Pre-/post-work skin protection, Konzentration auf unteres Ende der Spec halten",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-causing-rashes.234346/",
    sourceTitle: "Coolant causing rashes!",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2011-05-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Erhöhter Antifoam-Bedarf bei Erstbefüllung",
    description: "Foren-Erfahrungsbericht: MB-50 benötigt bei Erstbefüllung einer Maschine eine deutliche Menge Antifoam-Additiv. Auf Maschinen mit ungünstig dimensionierten Coolant-Systemen kommt es zu Foam und Überlauf. Hinweis: schlecht designte Sumpfgeometrie und hohe Pumpenleistung verstärken Problem.",
    symptoms: ["Schaumbildung", "Coolant-Überlauf"],
    rootCause: "Tensid-Formulierung in Kombination mit hohem Pumpen-Sheer und ungünstiger Rücklaufgeometrie",
    workaround: "Antifoam-Additiv (z.B. Silicone-based Defoamer) dosieren, Konzentration prüfen",
    preventiveMeasure: "Sumpf-Design verbessern, weiche Rückläufe, niedrigere Konzentration",
    affectedMaterials: [],
    affectedOperations: ["High-Pressure-Coolant", "Through-Spindle-Coolant"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/another-coolant-thread-keep-using-mb50-or-change.413613/",
    sourceTitle: "Another coolant thread. Keep using MB50 or change.",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "BIOLOGY",
    severity: "HIGH",
    title: "Coolant wird in neuer Maschine sofort ranzig",
    description: "Anwender berichtet: Direkt nach erster Mischung und Befüllung in einer brandneuen Maschine wurde der Coolant rasch ranzig durch Bakterienbefall. Schlechte Anfangsdesinfektion oder schlechte Wasserqualität als wahrscheinlichste Ursache, sensitive Formulierung trotz Vermarktung als bio-resistent.",
    symptoms: ["Geruch (Schwefelwasserstoff/Buttersäure)", "Verfärbung", "pH-Drift"],
    rootCause: "Anaerobe Bakterien (SRB) bei Wochenend-Stillstand; mangelhafte Maschinendesinfektion vor Inbetriebnahme",
    workaround: "Vollständig entleeren, mit System-Cleaner spülen, frisch ansetzen mit DI-Wasser",
    preventiveMeasure: "Maschine vor Erstbefüllung mit Biozid spülen, kontinuierliche Belüftung am Wochenende",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/castrol-hysol-mb-50-problems.225737/",
    sourceTitle: "Castrol Hysol MB-50 Problems",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2011-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Ende der Sumpfleben sichtbar als geronnene Milch",
    description: "Praxisbeobachtung: Castrol Hysol semi-synth-Formulierungen sind langlebig, aber am Ende der Sumpfleben sieht der Coolant 'wie geronnene Milch' aus - typischerweise ohne ausgeprägten ranzigen Geruch. Indikator für Emulsionsbruch und Aufbruch der Tensid-Struktur.",
    symptoms: ["Geronnene Optik", "Emulsionsbruch", "Schichtbildung"],
    rootCause: "Tensid-Erschöpfung, Ca/Mg-Hardness Buildup, Tramp-Oil-Akkumulation",
    workaround: "Coolant ablassen, Maschine reinigen, frisch ansetzen",
    preventiveMeasure: "Regelmässige Konzentrations- und Härte-Messung; Tramp-Oil-Skimmer einsetzen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/castrol-hysol-mb-50.299715/",
    sourceTitle: "Castrol Hysol MB 50 - General Discussion",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2014-01-01",
    language: "EN",
    isOfficial: false
  },

  // ===== Castrol Hysol XF =====
  {
    productName: "Hysol XF",
    manufacturerName: "Castrol",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Reformulierung weg von Formaldehyd-Releasern (XBB-Serie ersetzt klassische Hysol)",
    description: "Castrol entwickelte die Hysol-SL-XBB-Serie als Nachfolger klassischer Hysol-Coolants - chlorfrei, borfrei und ohne Formaldehyd-Releasing-Agents. In Kundentests wurde 20% Emulsion von Hysol SL 37 XBB als nicht-hautirritierend selbst bei wiederholtem Kontakt eingestuft. Implizite Bestätigung, dass Vorgängerformulierungen (klassisches Hysol XF, MB 50 etc.) Formaldehyd-Releaser enthielten - REACH-/CLP-Sensitivierungsrisiko.",
    symptoms: ["Allergische Kontaktdermatitis", "Sensibilisierung"],
    rootCause: "Formaldehyd-abgebende Biozide (z.B. Hexahydrotriazine wie Grotan) - bekannte Sensibilisierer",
    workaround: "Wechsel auf Hysol SL XBB Serie oder boron/formaldehyd-freie Alternativen",
    preventiveMeasure: "Bei Sensibilisierung Wechsel auf XBB-Formulierung; Hautschutzprogramm",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.machinerylubrication.com/Read/31259/castrol-cutting-fluid",
    sourceTitle: "Castrol Launches New Cutting Fluid (Hysol SL 37 XBB)",
    sourceAuthor: "Machinery Lubrication / Castrol",
    sourceDate: "2014-10-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Hysol R / N / generische Hysol-Familie =====
  {
    productName: "Hysol R",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "HSE Powertrain-Longbridge MWF-Outbreak (101 Fälle Atemwegserkrankungen)",
    description: "Im Powertrain-Werk Longbridge (Birmingham) wurden ca. 101 Fälle berufsbedingter Atemwegserkrankungen dokumentiert - überwiegend extrinsische allergische Alveolitis (EAA) und arbeitsbedingtes Asthma. Etwa 12% der Belegschaft betroffen. HSE 2004: Ursache war ungenügende Pflege der wassermischbaren KSS, was unkontrolliertes Bakterien- und Endotoxin-Wachstum erlaubte. Lieferant: Houghton plc. Castrol Hysol-Familie war zeitgleich in vergleichbaren Powertrain-Anwendungen im UK-Markt verbreitet - generische Warnung für alle UK-Hysol-User. 79 Kläger erhielten Vergleich nach 7-jährigem Rechtsstreit.",
    symptoms: ["Husten", "Atemnot", "EAA/Hypersensitivity Pneumonitis", "Asthma", "Gewichtsverlust"],
    rootCause: "Unzureichende Sumpfpflege, Bakterien- und Endotoxin-Wachstum in zentralen Anlagen (55.000-200.000 l)",
    workaround: "Coolant-Wechsel, mikrobiologisches Monitoring, Encapsulation der Maschinen",
    preventiveMeasure: "HSE Code of Practice MWF, monatliche Dip-Slides, Endotoxin-Messung, LEV (Local Exhaust Ventilation)",
    affectedMaterials: [],
    affectedOperations: ["Zentrale KSS-Systeme", "Engine-Block-Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://en.wikipedia.org/wiki/Powertrain_Ltd",
    sourceTitle: "Powertrain Ltd - Respiratory Disease Outbreak (HSE Aug 2004)",
    sourceAuthor: "HSE / Thompsons Solicitors",
    sourceDate: "2004-08-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hysol R",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "MG Rover Powertrain Group Litigation - Vergleichszahlungen 2011",
    description: "Sammelklage von 79 ehemaligen Beschäftigten wegen Atemwegserkrankungen durch MWF-Exposition im Longbridge-Werk. Nach 7 Jahren Vergleich. Dokumentiert die juristische Verantwortung der Arbeitgeber bei MWF-bedingten Lungenerkrankungen. Trade-Union-Solicitors Thompsons koordinierten Klage.",
    symptoms: ["Berufsbedingtes Asthma", "EAA", "Berufskrankheit"],
    rootCause: "Versäumnis bei MWF-Sumpfpflege durch Arbeitgeber",
    workaround: null,
    preventiveMeasure: "Lückenlose Dokumentation der KSS-Pflege als Haftungsschutz",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.thompsonstradeunion.law/news/news-releases/asbestos-disease-news/mg-rover-powertrain-group-litigation",
    sourceTitle: "MG Rover - Powertrain Group Litigation",
    sourceAuthor: "Thompsons Trade Union Solicitors",
    sourceDate: "2011-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Variocut (Familie) =====
  {
    productName: "Variocut B 30",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Ölnebel-Exposition - Atemschutz erforderlich laut Castrol-SDS",
    description: "Castrol SDS für Variocut B 30 SP (BP/Castrol-Dokumentation) weist explizit auf Atemwegsrisiko durch Ölnebel hin. Bei unzureichender Lüftung muss Atemschutz Klasse R (oil-resistant) oder P (oil-proof) getragen werden. Bei Ölnebel >50 mg/m³ HEPA-Halbmaske, >125 mg/m³ Vollmaske mit Hood/Helmet und HEPA. Belgische Grenzwerte für Mineralöle: TWA 5 mg/m³ (8h), STEL 10 mg/m³ (15min). Anhaltender oder wiederholter Kontakt entfettet die Haut.",
    symptoms: ["Hautirritation", "Dermatitis", "Atemwegsreizung bei hoher Mist-Belastung"],
    rootCause: "Mineralölbasis + EP-Additive, Mist-Bildung bei Hochdruck-Koolant",
    workaround: "LEV (lokale Absaugung), Maschinenkapselung, Mist-Collector mit HEPA",
    preventiveMeasure: "Mist-Messung gemäss BGI 718, Encapsulation, Nitril-Handschuhe",
    affectedMaterials: [],
    affectedOperations: ["Hochdruck-Bohren", "Tieflochbohren", "Räumen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://msdspds.bp.com/ussds/amersdsf.nsf/0/A6C0397FA4BA2D52802585CB0053D8C9/$file/2644108.pdf",
    sourceTitle: "Variocut B 30 SP Safety Data Sheet",
    sourceAuthor: "Castrol/BP",
    sourceDate: "2019-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol CareCut ES 1 =====
  {
    productName: "Carecut ES 1",
    manufacturerName: "Castrol",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Bewusst sulfurfrei für Gelbmetall-Kompatibilität",
    description: "Castrol-Produktdatenblatt: CareCut ES 1 enthält keinen aktiven Schwefel und ist deshalb kompatibel mit Gelbmetallen (Buntmetalle). Implizit: aktiv-schwefelhaltige Neat-Cutting-Oils anderer Anbieter verfärben Kupfer/Messing/Bronze - bekanntes Risiko bei generischen Schneidölen auf Gelbmetallen.",
    symptoms: ["Verfärbung Kupfer/Messing bei sulfurhaltigen Alternativen"],
    rootCause: "Aktiv-Schwefel reagiert mit Kupfer zu CuS (schwarz)",
    workaround: "Sulfurfreie Cutting Oils wie CareCut ES 1 für Gelbmetalle wählen",
    preventiveMeasure: "Produktauswahl nach Werkstoff (Kupfer/Messing → no active sulfur)",
    affectedMaterials: ["Kupfer", "Messing", "Bronze"],
    affectedOperations: ["Drehen", "Bohren", "Räumen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://msdspds.castrol.com/bpglis/FusionPDS.nsf/Files/F1349A644A7ACB7E80257FA20051549E/$File/BPXE-A9LSSZ.pdf",
    sourceTitle: "Castrol CareCut ES 1 Product Data Sheet",
    sourceAuthor: "Castrol",
    sourceDate: "2016-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobil Mobilcut 230 =====
  {
    productName: "Mobilcut 230",
    manufacturerName: "Mobil",
    category: "STABILITY",
    severity: "LOW",
    title: "Hersteller-Bestätigung: Foam- und Wasserhärte-Empfindlichkeit adressiert",
    description: "ExxonMobil PDS: Mobilcut 230 wurde explizit für 'wide range of water qualities' formuliert und resistent gegen Foam - auch in High-Pressure-Systemen. Bedeutet im Umkehrschluss: Standard semi-synthetic Coolants (inkl. älterer Mobilcut-Varianten) sind in High-Pressure-Anwendungen schaum-anfällig. Wenn Anwender Mobilcut 230 ausserhalb der Spec (sehr weiches oder sehr hartes Wasser) einsetzen, kann Emulsionsstabilität leiden.",
    symptoms: ["Schaumbildung", "Emulsionsbruch", "Mikroemulsion-Instabilität"],
    rootCause: "Wasserhärte-Effekte auf Emulgator-System (Ca/Mg-Ionen)",
    workaround: "Wasserhärte messen und ggf. Mischen mit DI-Wasser",
    preventiveMeasure: "Wasserqualität-Range im PDS prüfen",
    affectedMaterials: [],
    affectedOperations: ["Hochdruck-Koolant"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.mobil.com/en/sap/our-products/products/mobilcut-230",
    sourceTitle: "Mobilcut 230 Product Page",
    sourceAuthor: "ExxonMobil",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobil Mobilcut 250 =====
  {
    productName: "Mobilcut 250",
    manufacturerName: "Mobil",
    category: "WORKPIECE_STAINS",
    severity: "MEDIUM",
    title: "Speziell für Aluminium mit niedrigem Staining-Potenzial (PDS)",
    description: "Mobil PDS: Mobilcut 250 ist 'high performance semi-synthetic, formulated to enhance performance when machining aluminum and aluminum alloys and where low staining potential is important.' Impliziert: Generische semi-synthetic Coolants verfärben sensitive Aluminium-Legierungen (z.B. AlZnMgCu - 7075, AlCuMg - 2024). Bei Wechsel von Mobilcut 250 auf Standard-Coolant sind Staining-Probleme zu erwarten.",
    symptoms: ["Schwarze/braune Flecken auf Aluminium", "Oberflächenverfärbung"],
    rootCause: "Aminkomponenten (MEA/TEA) reagieren mit Aluminium-Oxid-Layer",
    workaround: "Mobilcut 250 oder andere low-staining Formulierungen für sensitive Al-Legierungen",
    preventiveMeasure: "Staining-Testprotokoll vor Coolant-Wechsel; pH < 9.2",
    affectedMaterials: ["Aluminium", "AlCuMg (2024)", "AlZnMgCu (7075)"],
    affectedOperations: ["Fräsen", "Bohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.mobil.com/en/sap/our-products/products/mobilcut-250",
    sourceTitle: "Mobilcut 250 Product Page",
    sourceAuthor: "ExxonMobil",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobil Mobilmet 766 =====
  {
    productName: "Mobilmet 766",
    manufacturerName: "Mobil",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Starker Geruch - Foren-Beschwerden",
    description: "Anwender berichten in Praktiker-Foren: Mobilmet 766 hat einen 'horrible smell'. Häufige Beanstandung beim Drehen und Gewindeschneiden. Bei längerer Exposition ohne Lüftung Beschwerden.",
    symptoms: ["Unangenehmer Geruch", "Geruchsbelästigung"],
    rootCause: "Aktiv-Schwefel-/Phosphor-EP-Additive in Neat-Cutting-Oil",
    workaround: "Maschinenkapselung, LEV, alternative dunkle Schneidöle",
    preventiveMeasure: "Belüftung nach BG-RCI; bei langfristigen Beschwerden Wechsel auf low-odor Variante",
    affectedMaterials: [],
    affectedOperations: ["Drehen", "Gewindeschneiden", "Rohrgewinde"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/cutting-oil.232579/",
    sourceTitle: "Cutting Oil - General Discussion (Mobilmet 766)",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2012-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Mobilmet 766",
    manufacturerName: "Mobil",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Ablaufprobleme - Coolant fliesst nicht vollständig zurück, Lines sputtern",
    description: "User-Report: Mobilmet 766 ist eingedickter (anti-misting agents), läuft nicht vollständig vom Werkstück ab, kommt am Tagesende nicht schnell genug zum Sumpf zurück. Folge: Coolant-Lines sputtern, Versorgung wird ungleichmässig. Negativ für unbeaufsichtigte Nachtschichten.",
    symptoms: ["Coolant-Lines sputtern", "Werkstück bleibt benetzt", "ungleichmässige Versorgung"],
    rootCause: "Anti-Mist-Polymere erhöhen Viskosität / Klebrigkeit",
    workaround: "Wechsel zu dünnflüssigerem Schneidöl (z.B. Chevron Bright-Cut NM)",
    preventiveMeasure: "Coolant-Rückläufe steiler dimensionieren; Tray-Geometrie prüfen",
    affectedMaterials: [],
    affectedOperations: ["Lathe Flood Coolant", "Mill Flood Coolant"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://bobistheoilguy.com/forums/threads/mobilmet-426-alternatives.180074/",
    sourceTitle: "Mobilmet 426 alternatives (incl. 766 discussion)",
    sourceAuthor: "BobIsTheOilGuy Community",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Mobilmet 766",
    manufacturerName: "Mobil",
    category: "SHELF_LIFE",
    severity: "LOW",
    title: "Beschränktes Mindesthaltbarkeitsdatum von nur 1 Jahr",
    description: "Foren-Report: Mobilmet 766 hat ein 'best-if-used-before date' von nur 1 Jahr ab Lieferung. Für kleinere Werkstätten mit langsamem Verbrauch (5-Gallon-Pail) problematisch - Lagerstabilität geringer als bei klassischen Schneidölen.",
    symptoms: ["Produkt-Degradation nach 12 Monaten", "Performance-Verlust"],
    rootCause: "Sensitive Esther- oder Polymer-Additive mit begrenzter Stabilität",
    workaround: "Kleinere Gebinde bestellen, kühl/dunkel lagern",
    preventiveMeasure: "FIFO-Lagerprinzip, max. 12 Monate Vorrat",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.chaski.org/homemachinist/viewtopic.php?t=105486",
    sourceTitle: "Mobilmet 766, replace periodically or just top up?",
    sourceAuthor: "Home Machinist Forum",
    sourceDate: "2021-01-01",
    language: "EN",
    isOfficial: false
  },

  // ===== Mobil Mobilmet 423 =====
  {
    productName: "Mobilmet 423",
    manufacturerName: "Mobil",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Sehr dünnflüssig - 'wie Mineralspirits' (User-Report)",
    description: "Anwender, der ein Barrel Mobilmet 423 für Aluminium und niedrig-legierten Stahl gekauft hat, berichtet: Produkt ist 'really thin and runny like mineral spirits'. Für Anwendungen mit Bedarf an höherer Filmdicke (Sägen, schwere Zerspanung) ungeeignet. Mismatch zwischen User-Erwartung und ISO-32-Viskosität.",
    symptoms: ["Geringe Filmdicke", "höherer Verbrauch", "Mist-Bildung"],
    rootCause: "ISO 32 Viskosität (niedrig spezifiziert für Hochgeschwindigkeitsanwendungen)",
    workaround: "Für schwere Zerspanung Mobilmet 766 oder 423-46 (höhere Viskosität)",
    preventiveMeasure: "Viskositätsgrad aus PDS verifizieren bevor Bulk gekauft wird",
    affectedMaterials: ["Aluminium", "C-Stahl"],
    affectedOperations: ["Drehen", "Bohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/cutting-oil-question.394418/",
    sourceTitle: "Cutting Oil Question (Mobilmet 423)",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: false
  },

  // ===== Shell Adrana D 7088 (User berichtet zu Adrana 770) =====
  {
    productName: "Adrana D 7088",
    manufacturerName: "Shell",
    category: "BIOLOGY",
    severity: "HIGH",
    title: "Akute Verkeimung nach Kontamination - 'smelled like outhouse within 2 days'",
    description: "Praxisfall (IndustryArena Haas-Forum): Anwender betrieb Shell Adrana 770 (Adrana-D-Familie) ca. 8 Monate ohne Probleme. Nach Schneiden eines Holzstücks zu Testzwecken stank die Maschine innerhalb von 2 Tagen 'wie ein Plumpsklo'. Nach kompletter Reinigung und Frisch-Befüllung mit gleichem Adrana 770 in gleicher Konzentration kam Geruch innerhalb 6 Wochen zurück: tägliches Skimming nötig, weisse fettige Klumpen, Coolant wechselte von kristall-blau nach grau-milchig-stinkend. Hinweis auf erhöhte Empfindlichkeit der Formulierung gegenüber organischer Kontamination.",
    symptoms: ["Fäkalartiger Geruch", "weisse Fettklumpen", "Verfärbung kristall-blau → grau"],
    rootCause: "Anaerobe Bakterien / Pilze auf organischen Kontaminanten; biostat. Reserve der Formulierung zu gering",
    workaround: "Maschinen-Cleaner spülen, frisch ansetzen, Biozid-Top-up",
    preventiveMeasure: "Keine organischen Kontaminanten (Holz, Papier, Hautcremes) in Sumpf; Sumpfpflege wöchentlich",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 12,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://en.industryarena.com/forum/coolant-tank-cleaning--69155.html",
    sourceTitle: "Coolant tank cleaning - Haas Mills (Shell Adrana 770)",
    sourceAuthor: "IndustryArena Community",
    sourceDate: "2019-01-01",
    language: "EN",
    isOfficial: false
  },

  // ===== Castrol Hysol (Familie) - allgemeine OPERATOR_HEALTH / Dermatitis =====
  {
    productName: "Hysol N",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Castrol-SDS: 'Causes skin irritation, may cause allergic skin reaction'",
    description: "Castrol Hysol-SDS-Familie (USA-Variante 6519/6754 als Indikator) klassifiziert die Produkte explizit als haut-irritierend mit möglicher allergischer Hautreaktion. California Prop 65: Produkte enthalten Chemikalien, die als krebserregend gelistet sind. In Aminhaltigen MWFs Potenzial zur Nitrosamin-Bildung (tierische Karzinogene). Anhaltender oder wiederholter Kontakt entfettet die Haut und führt zu Irritation/Dermatitis.",
    symptoms: ["Hautirritation", "Allergische Hautreaktion", "Dermatitis", "Entfettung"],
    rootCause: "MEA/Amin-Komponenten + Boron + Formaldehyd-Releaser im klassischen Hysol",
    workaround: "Handschuhe (Nitril), Barrier-Cream, Hautschutzplan nach TRGS 401",
    preventiveMeasure: "G24-Vorsorge, Pre-/Post-Work-Hautschutz, Allergiker frühzeitig wechseln",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "SDS",
    sourceUrl: "https://msdspds.castrol.com/ussds/amersdsf.nsf/0/0934718D241496EB80258B2500532E6F/$file/3096860.pdf",
    sourceTitle: "Hysol 6519 Safety Data Sheet (representative Castrol Hysol family)",
    sourceAuthor: "Castrol",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Branchenweite generische Erkenntnisse mit Hysol-Bezug =====
  {
    productName: "Hysol XF",
    manufacturerName: "Castrol",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Allergische Kontaktdermatitis durch Monoethanolamin (MEA) in wassermischbaren KSS",
    description: "Wissenschaftliche Reviews (Springer / Contact Dermatitis): Monoethanolamin (MEA) und Oxidationsprodukte von Harzsäuren sind die wichtigsten Allergene in wassermischbaren KSS. EU CLP: MEA verursacht schwere Hautverätzungen und Augenschäden; REACH-Registrierungen identifizieren mögliche allergische Hautreaktion und Atemwegssymptome bei Inhalation. Castrol Hysol-Familie enthält in vielen Varianten MEA als Rostschutz/Emulgator - direkt relevant.",
    symptoms: ["Allergische Kontaktdermatitis", "Atemwegssymptome", "Augenreizung"],
    rootCause: "MEA als Sensibilisierer (Boric-Acid/MEA/Fettsäure-Kondensat dokumentiert als Allergen)",
    workaround: "MEA-arme oder amin-freie Formulierungen (z.B. Hysol SL XBB)",
    preventiveMeasure: "Patch-Test bei betroffenen Mitarbeitern, MEA-Konzentration im Coolant überwachen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://link.springer.com/rwe/10.1007/978-3-030-36335-2_36",
    sourceTitle: "Contact Allergy to Metalworking Fluids (Springer)",
    sourceAuthor: "Springer Nature / Geier et al.",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Generischer MWF-HP-Outbreak (NIOSH/CDC) als Hintergrund für Hysol/Mobilcut-Linien =====
  {
    productName: "Hysol R",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Hypersensitivity Pneumonitis bei MWF unterhalb OSHA/NIOSH Grenzwerten",
    description: "PubMed/NIOSH-Reviews dokumentieren: HP-Fälle (Hypersensitivity Pneumonitis) traten auch bei Expositionen weit unterhalb der OSHA Permissible Exposure Limit (PEL 5 mg/m³) und sogar NIOSH-REL (0,5 mg/m³) auf. Verursacher häufig Mycobacterium immunogenum oder Endotoxine im MWF-Sumpf - unabhängig von der Marke. Wichtig für Castrol Hysol-Anwender in zentralen Anlagen.",
    symptoms: ["Husten", "Atemnot", "Fieber", "Gewichtsverlust", "Lungeninfiltrate"],
    rootCause: "M. immunogenum, M. chelonae, Gram-negative Bakterien, Endotoxine in MWF-Aerosol",
    workaround: "Maschinen-Encapsulation, HEPA-Mist-Collector, Coolant-Wechsel mit Hard-Cleaning",
    preventiveMeasure: "Endotoxin-Messung (z.B. LAL-Test), G23-Vorsorge, NIOSH-REL 0.5 mg/m³ als Zielwert",
    affectedMaterials: [],
    affectedOperations: ["Zentrale KSS-Systeme"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.cdc.gov/mmwr/preview/mmwrhtml/00043265.htm",
    sourceTitle: "Biopsy-Confirmed Hypersensitivity Pneumonitis in Automobile Production Workers - Michigan, 1994-1995 (CDC MMWR)",
    sourceAuthor: "CDC / NIOSH",
    sourceDate: "1996-07-19",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Mobilcut 230",
    manufacturerName: "Mobil",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Ohio 2001: 12 von 32 Arbeitern (38%) mit HP bei semi-synthetic MWF-Exposition",
    description: "PubMed/CDC: Bei einem Ohio-Werk (Automotive Brake Manufacturing) Okt 2000 - Apr 2001 erfüllten 12 von 32 Maschinisten (38%) die Definition für Hypersensitivity Pneumonitis. Analyse der MWF-Systeme zeigte dominantes Wachstum von Mycobacterium immunogenum. Drei Arbeiter hospitalisiert mit Dyspnoe, Husten, Fatigue, Hypoxie, Lungeninfiltraten. Betraf semi-synthetic MWF wie Mobilcut/Hysol-Klasse - relevanter Branchen-Benchmark für alle semi-synthetic Anwender.",
    symptoms: ["Dyspnoe", "Husten", "Hypoxie", "Lungeninfiltrate", "Gewichtsverlust"],
    rootCause: "Mycobacterium immunogenum-Dominanz im semi-synthetic MWF",
    workaround: "Komplettes Sumpf-Cleaning, M. immunogenum-spezifische Sanierung",
    preventiveMeasure: "Mykobakterien-Test im jährlichen Coolant-Audit; LEV; HEPA-Filtration",
    affectedMaterials: [],
    affectedOperations: ["Brake-Manufacturing", "Engine-Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/12004986/",
    sourceTitle: "Respiratory illness in workers exposed to metalworking fluid contaminated with nontuberculous mycobacteria - Ohio, 2001",
    sourceAuthor: "PubMed/CDC",
    sourceDate: "2002-05-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Cooledge BI =====
  {
    productName: "Cooledge BI",
    manufacturerName: "Castrol",
    category: "REGULATORY",
    severity: "LOW",
    title: "Chlor- und borfrei (Produkt-Positionierung als Reaktion auf REACH/CLP)",
    description: "Castrol PDS Cooledge BI: 'general purpose soluble metalworking fluid, chlorine- and boron-free.' Bewusste Reformulierung wegen REACH-Beschränkungen für Borsäure (SVHC-gelistet als reproduktionstoxisch) und Chlorparaffine (POP/SVHC). Hinweis: Klassische Mitbewerber-Cutting-Fluids mit Borax-Pufferung können bei Konzentrationen >5,5% den 0,1% Bor-Schwellenwert reissen und kennzeichnungspflichtig werden.",
    symptoms: ["Kennzeichnungspflicht REACH/CLP bei Borax-haltigen Konkurrenzprodukten"],
    rootCause: "EU-REACH SVHC-Liste: Borsäure & Borate; CMR-Klassifizierung",
    workaround: "Boron-freie Formulierungen wie Cooledge BI oder Hysol SL XBB",
    preventiveMeasure: "SDS auf Bor-Gehalt prüfen; Reformulierung bei Konzentration >5%",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://msdspds.castrol.com/bpglis/FusionPDS.nsf/Files/B3E509564D0BA26180257796002F9454/$File/450805_XI_en.pdf",
    sourceTitle: "Castrol Cooledge BI PDS",
    sourceAuthor: "Castrol",
    sourceDate: "2014-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Honilo 980 =====
  {
    productName: "Honilo 980",
    manufacturerName: "Castrol",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Chlor-, schwefel- und schwermetallfrei (Hersteller-Positionierung)",
    description: "Castrol Honilo 980 PDS: low-viscosity neat cutting oil, chlorfrei, schwefelfrei, schwermetallfrei. Speziell für Honing/Superfinishing ferrous/non-ferrous. Implizit: Honilo 980 vermeidet bekannte Probleme der Honilo/Aktiv-Schwefel-Familie (Verfärbung Gelbmetall, REACH-Chlorparaffin-Beschränkung). Bei Honing mit höchster Oberflächengüte (Ra < 0,1 µm) sind aktiv-schwefelhaltige Öle nicht geeignet.",
    symptoms: ["Verfärbung Gelbmetalle (bei aktiv-schwefelhaltigen Alternativen)"],
    rootCause: "Schwefel-Gelbmetall-Reaktion → CuS-Schwärzung",
    workaround: "Honilo 980 / 988 für sensitive Honing-Anwendungen",
    preventiveMeasure: "Bei Honing/Superfinishing schwefelfreie Öle verwenden",
    affectedMaterials: ["Kupfer", "Messing", "Bronze"],
    affectedOperations: ["Honen", "Superfinishing"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://msdspds.castrol.com/bpglis/FusionPDS.nsf/Files/FE1575A45958A427802578B6006BEAF8/$File/Honilo%20980%20(US%20ENG).pdf",
    sourceTitle: "Castrol Honilo 980 PDS",
    sourceAuthor: "Castrol",
    sourceDate: "2011-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Alusol XBB =====
  {
    productName: "Alusol XBB",
    manufacturerName: "Castrol",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "XBB-Linie ersetzt klassische Alusol wegen Bor-/Formaldehyd-Reformulierung",
    description: "Castrol-Brochure 'XBB technology brochure': Alusol XBB als Nachfolger der klassischen Alusol-Familie - 'productivity without compromise', formuliert ohne Bor und ohne Formaldehyd-Releaser. Implizit: Klassische Alusol-A/B/B-P bis mind. 2020 enthielten Bor-Verbindungen und Formaldehyd-Abspalter, was REACH-/CLP-Kennzeichnungs- und Sensibilisierungsrisiken auslöste. Bestandsanwender klassischer Alusol sollten Wechsel evaluieren.",
    symptoms: ["REACH-Kennzeichnungspflicht klassische Variante", "Formaldehyd-Sensibilisierung"],
    rootCause: "Borsäure (SVHC, reproduktionstoxisch) + Formaldehyd-abgebende Biozide",
    workaround: "Wechsel auf XBB-Formulierung",
    preventiveMeasure: "Bestands-Alusol auf SDS-Version prüfen; bei Bor-Gehalt >0,1% Wechsel planen",
    affectedMaterials: [],
    affectedOperations: ["Aluminium-Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.castrol.com/content/dam/castrol/master-site/en/global-ia/home/documents/products/industrial-xbb-brochure-us-digital-single-pages-030922.pdf",
    sourceTitle: "Castrol Alusol XBB - Productivity without compromise (Brochure)",
    sourceAuthor: "Castrol",
    sourceDate: "2022-03-09",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobil Vactra (relevant für Coolant-Kontamination) =====
  {
    productName: "Vactra Heavy Med",
    manufacturerName: "Mobil",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Demulgierbarkeit kritisch - kann KSS-Sumpf bei Tackifier-Inkompatibilität verstopfen",
    description: "Foren-Bericht (Practical Machinist): Anwender hatte schlechte Erfahrung beim Wechsel - günstigeres Way-Oil (Tackifier-Substitut) separierte sich und wurde 'thick tar', verstopfte Lube-System, Tisch musste rescraped werden und Lube-Meter ersetzt. Mobil Vactra Numbered Series ist speziell für Trennbarkeit von aqueous coolants ausgelegt. Mixing-Risiko bei Mehrlieferanten-Werkstätten.",
    symptoms: ["Way-Oil-Verdickung zu Tar", "Lube-Line-Verstopfung", "Tisch-Scoring"],
    rootCause: "Inkompatible Tackifier-Polymere zwischen Way-Oil-Marken",
    workaround: "Way-Oil nicht mischen; Single-Source-Strategie",
    preventiveMeasure: "Lube-Pump bei Markenwechsel komplett entleeren und spülen",
    affectedMaterials: [],
    affectedOperations: ["Machine-Slideway-Lubrication"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/vactra-2-waylube-substitution.208022/",
    sourceTitle: "Vactra 2 waylube substitution",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2010-01-01",
    language: "EN",
    isOfficial: false
  },

  // ===== HSE Übergeordnete Quelle für UK-Anwender =====
  {
    productName: "Hysol XF",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "HSE UK: Mist-Exposition als wachsendes Risiko (occupational HP)",
    description: "HSE UK: Occupational hypersensitivity pneumonitis und weitere Atemwegserkrankungen sind ein wachsendes Anliegen durch Mist-Exposition bei Metalworking. Mehrere grosse Outbreaks im UK dokumentiert. HSE empfiehlt strikte LEV, Sumpfpflege, mikrobiologisches Monitoring für ALLE wassermischbaren KSS - inkl. Castrol Hysol-Linie als Marktführer im UK.",
    symptoms: ["EAA", "Asthma", "Husten", "Atemnot"],
    rootCause: "Mist-Aerosole + Bakterien/Endotoxine",
    workaround: "LEV, Encapsulation, HEPA-Mist-Collection",
    preventiveMeasure: "WEL 1 mg/m³ (UK) als Zielwert, monatliche mikrobiologische Tests",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.hse.gov.uk/metalworking/hse.htm",
    sourceTitle: "HSE and Metalworking Fluids",
    sourceAuthor: "UK Health and Safety Executive",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Castrol Variocut G (Sulfo-haltige) Allgemein =====
  {
    productName: "Variocut G 101",
    manufacturerName: "Castrol",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Atemschutz mit Klasse R oder P erforderlich laut Castrol SDS",
    description: "Castrol Variocut G-Familie SDS (G 159 als repräsentativ): Bei unzureichender Lüftung Atemschutz tragen - oil-resistant (Klasse R) oder oil-proof (Klasse P). Bei Ölnebel <50 mg/m³ HEPA-Halbmaske, bei <125 mg/m³ Vollmaske mit Helm und HEPA. Anhaltender oder wiederholter Hautkontakt entfettet und führt zu Irritation/Dermatitis. Cobalt-/Nickel-Werkstücke können den MWF kontaminieren und allergische Hautreaktionen verstärken.",
    symptoms: ["Hautirritation", "Dermatitis", "Atemwegsbelastung bei hohem Mist"],
    rootCause: "Mineralöl + EP-Additive; Aerosol-Bildung",
    workaround: "LEV, Encapsulation, PSA",
    preventiveMeasure: "Mist-Messung, Co/Ni-Kontamination kontrollieren, regelmässiger Coolant-Wechsel",
    affectedMaterials: ["Co-Legierungen", "Ni-Legierungen", "Cr-Legierungen"],
    affectedOperations: ["Tieflochbohren", "Räumen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "SDS",
    sourceUrl: "https://msdspds.castrol.com/ussds/amersdsf.nsf/0/10B405825E2C832680258A22007659F5/$file/3013912.pdf",
    sourceTitle: "Variocut G 159 SDS (representative for G-family)",
    sourceAuthor: "Castrol",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobilcut Series (Familie) =====
  {
    productName: "Mobilcut 142",
    manufacturerName: "Mobil",
    category: "WORKPIECE_STAINS",
    severity: "LOW",
    title: "Chlorfreie biostabile Formulierung speziell für Aluminium-Automotive",
    description: "Mobilcut Series PDS: Biostabile, chlorfreie Fluids 'particularly suitable for aluminum alloys used in the automotive industry.' Implizit: Standard wassermischbare KSS verfärben Automotive-Aluminium-Legierungen. Wechsel von Mobilcut 142/230 auf nicht-spezialisierte Coolants führt regelmässig zu Staining-Reklamationen.",
    symptoms: ["Verfärbung Aluminium", "Staining"],
    rootCause: "Amin/pH-Sensibilität von Aluminium-Legierungen",
    workaround: "Bei Aluminium-Automotive nur low-staining Coolants",
    preventiveMeasure: "Staining-Test mit Probestücken vor Coolant-Wechsel",
    affectedMaterials: ["Aluminium-Automotive-Legierungen"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://hascooil.com/wp-content/uploads/2016/11/MobilCut-Series-pds.pdf",
    sourceTitle: "Mobilcut Series PDS",
    sourceAuthor: "ExxonMobil",
    sourceDate: "2016-11-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mycobakterien-Forschung als regulatorischer Hintergrund =====
  {
    productName: "Hysol MB 50",
    manufacturerName: "Castrol",
    category: "BIOLOGY",
    severity: "HIGH",
    title: "Mycobacterium immunogenum + Endotoxin in MWF triggert HP (Tiermodell bestätigt)",
    description: "PMC/AJRCCM Tiermodell (Mäuse): MWF mit Mykobakterien und Endotoxin induziert Hypersensitivity Pneumonitis. Bestätigt die kausale Rolle dieser Kontaminanten in MWF-bedingten HP-Outbreaks. Relevant für alle semi-synthetic Coolants wie Hysol MB 50 - Mykobakterien-Wachstum in Sumpfsystemen ist generelles Risiko, nicht produktspezifisch, aber semi-synthetics gelten als anfälliger als full synthetics.",
    symptoms: ["HP-Symptome", "Lungengranulome"],
    rootCause: "Nontuberculous Mycobacteria (NTM) + LPS-Endotoxine",
    workaround: "Komplettes Cleaning bei NTM-Nachweis (Standard-Biozide oft unwirksam)",
    preventiveMeasure: "NTM-spezifischer Test (PCR), HEPA-Mist-Filtration, regelmässiger Coolant-Wechsel",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2662953/",
    sourceTitle: "Metalworking Fluid with Mycobacteria and Endotoxin Induces HP in Mice",
    sourceAuthor: "PMC / AJRCCM",
    sourceDate: "2006-04-01",
    language: "EN",
    isOfficial: true
  },

  // ===== Mobilcut 100 generischer Foren-Reuse =====
  {
    productName: "Mobilcut 102",
    manufacturerName: "Mobil",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Bei zu niedriger Konzentration Rostbildung auf C-Stahl/Gusseisen",
    description: "Foren-Bericht: Mobilcut-100-Serie (Soluble Oil) kann bei zu niedriger Konzentration oder schlechter Sumpfpflege auf C-Stahl- und Gusseisen-Werkstücken Flugrost erzeugen, besonders über Nacht oder am Wochenende. Hintergrund: Standard Soluble Oil hat moderate Korrosionsschutz-Reserve; bei Über-Verdünnung versagt der Schutzfilm.",
    symptoms: ["Flugrost auf Werkstücken", "Maschinen-Tisch-Korrosion"],
    rootCause: "Über-Verdünnung, niedriger pH, Tramp-Oil-Verschmutzung",
    workaround: "Konzentration via Refractometer prüfen (min 6-8%), pH > 8.8 halten",
    preventiveMeasure: "Refractometer-Tagesprotokoll, pH-Kontrolle, Tramp-Oil-Skimmer",
    affectedMaterials: ["C-Stahl", "Gusseisen"],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/mobil-cut-coolant.261491/",
    sourceTitle: "Mobil Cut Coolant - General Discussion",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2013-01-01",
    language: "EN",
    isOfficial: false
  },
];
