export default [
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Coolant-Separation bei falschem Mischvorgang",
    description: "Mehrere Anwender berichten, dass TRIM SOL beim direkten Eingiessen ins grosse Wasserreservoir separiert (Konzentrat zuerst statt Wasser zuerst). Sichtbar als ungleichmaessig konzentrierte, milchige Schichten, die sich erst nach Stunden Umlauf homogenisieren. Master Fluid Solutions empfiehlt explizit, zuerst eine kleine Starter-Charge anzumischen und diese dann ins Hauptvolumen einzubringen.",
    symptoms: ["Sichtbare Phasentrennung im Tank", "Konzentration variiert je nach Entnahmestelle", "Milchig-weisse Bereiche oberhalb klarem Wasser"],
    rootCause: "Konzentrat wurde direkt ins Wasser geschuettet ohne Pre-Mix; Emulgatoren konnten sich nicht gleichmaessig verteilen.",
    workaround: "Tank entleeren, korrekt vormischen, neu befuellen.",
    preventiveMeasure: "Mischvorgang nach TRIM-SOL-Anleitung: kleinere Starter-Charge mit Wasser, dann ins Hauptvolumen geben.",
    affectedMaterials: [],
    affectedOperations: ["Befuellen", "Topup"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anybody-have-their-coolant-seperate-in-the-tank.122470/",
    sourceTitle: "Anybody have their coolant separate in the tank?",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Rost an Maschine nach Wechsel auf enthaertetes Wasser",
    description: "Anwender berichten, dass TRIM SOL ploetzlich Rostflecken an Maschinen verursachte, nachdem auf weiches/enthaertetes Wasser umgestellt worden war. Loesung war, den Wasserenthaerter zu umgehen und wieder hartes Wasser zu verwenden, woraufhin der Rost verschwand.",
    symptoms: ["Rostflecken auf Tisch und Vorrichtungen", "Vorher rostfreier Betrieb wird zu rostig"],
    rootCause: "Sehr weiches (enthaertetes) Wasser entzieht Korrosionsinhibitoren ihre Wirksamkeit und wird selbst aggressiv gegen Eisen.",
    workaround: "Wasserenthaerter umgehen, ggf. RO-Wasser verwenden.",
    preventiveMeasure: "Wasserprobe vom Lieferanten bewerten lassen; Wasser-Haerte zwischen ca. 100-200 ppm CaCO3 anstreben.",
    affectedMaterials: ["Steel", "Cast Iron"],
    affectedOperations: ["Milling", "Turning"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-that-never-caused-rust-does-now.230645/",
    sourceTitle: "Coolant that never caused rust, does now?",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Sumpf-Verschlechterung bei Grauguss-Spaenen",
    description: "TRIM SOL ist gemaess Master Fluid Solutions nicht fuer dauerhaften Einsatz auf Grauguss (gray cast iron) oder Sphaeroguss Grade 40/60 ausgelegt. Anwender berichten ueber stark verkuerzte Standzeit (Sumpf 'geht kaputt'), wenn Stahl-/Guss-Spaene unterhalb des Coolant-Levels liegen.",
    symptoms: ["Kurze Sumpf-Lebensdauer bei Guss", "Foul smell innerhalb Wochen", "Bakterienwachstum"],
    rootCause: "Reduktion der Ester/Emulgatoren durch Eisenkatalyse, anaerobe Bedingungen unter Spaenebett.",
    workaround: "Spaeneaustragung verbessern, Sumpf regelmaessig entleeren; alternatives Produkt fuer Guss waehlen.",
    preventiveMeasure: "Fuer reine Gusspartien anderes TRIM-Produkt (z.B. MicroSol 585) verwenden.",
    affectedMaterials: ["Gray Cast Iron", "Nodular Iron"],
    affectedOperations: ["Milling", "Turning"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.masterfluids.com/na/en-us/data-sheet/di.php?pid=SOL",
    sourceTitle: "TRIM SOL Data Sheet / Compatibility Notes",
    sourceAuthor: "Master Fluid Solutions",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Starkes Schaeumen beim Rundschleifen",
    description: "Anwender beim Rundschleifen melden starkes Schaeumen mit TRIM SOL, sodass es ueber den Spaeneruecklauf hinauslief - selbst nach Reduktion der Konzentration von 11% auf 7%. Master Chemical (jetzt Master Fluid Solutions) bietet einen Defoamer-Zusatz; alternativ Konzentration auf 5% senken oder Pump-Kavitation/Vakuumleck am Pumpenfuss pruefen.",
    symptoms: ["Schaum-Ueberlauf am Chip-Tray", "Schaum-Pegel im Tank", "Druckverlust an Pumpe"],
    rootCause: "Hohe Konzentration plus Lufteintrag (oft Pumpen-Kavitation oder Vakuumleck am Saugfuss).",
    workaround: "Konzentration < 6 %, Defoamer vom Hersteller; Pumpenfuss von Spaenen befreien.",
    preventiveMeasure: "Pumpenimpeller sollte 2+ Zoll unter Fluessigkeitsoberflaeche bleiben; regelmaessige Tank-Wartung.",
    affectedMaterials: [],
    affectedOperations: ["Cylindrical Grinding"],
    reportedConcentration: 11,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/trim-sol-and-cylindrical-grinding.123036/",
    sourceTitle: "Trim Sol and Cylindrical Grinding",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM MicroSol 685",
    manufacturerName: "Master Fluid Solutions",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Schaeumen nach Sumpf-Reinigung und Topup",
    description: "Anwender mit Haas VF0 berichten, dass nach kompletter Sumpfreinigung und Wieder-Befuellung mit TRIM MicroSol 585XT/685 bei 9% Konzentration starkes Schaeumen am Spaeneruecklauf auftrat. Empfohlene Konzentration ist 4-10%; das Senken auf 5-6% loeste das Problem haeufig. Weiches Wasser verstaerkt Schaumbildung.",
    symptoms: ["Schaum-Ueberlauf", "Schaumdeckel im Tank", "Geringere Kuehlleistung wegen Lufteintrag"],
    rootCause: "Konzentration nahe Obergrenze in Kombination mit weichem Wasser; foerdert Schaum.",
    workaround: "Konzentration auf 5-6% senken, ggf. Antifoam-Additiv (TRIM TC 184B) als temporaere Massnahme.",
    preventiveMeasure: "Wasserhaerte pruefen; Refraktometer kalibrieren; nicht ueber 8% laufen wenn nicht zwingend.",
    affectedMaterials: [],
    affectedOperations: ["Milling", "High-Pressure Coolant"],
    reportedConcentration: 9,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/haas-machines/458646-coolant-foaming.html",
    sourceTitle: "Coolant Foaming - Haas Machines / TRIM MicroSol",
    sourceAuthor: "CNCZone user",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM E206",
    manufacturerName: "Master Fluid Solutions",
    category: "WORKPIECE_STAINS",
    severity: "MEDIUM",
    title: "Verfaerbung von 7xxx Aluminium nach Edelstahl-Charge",
    description: "Anwender berichten, dass nach dem Bearbeiten von Edelstahl auf einer CNC-Drehmaschine mit TRIM E206 folgende Aluminiumteile (insbesondere hochzinkige 7000er Legierungen) Verfaerbungen zeigen, die nur manuell entfernbar sind. Andere Praktiker erklaeren, chlorierte Coolants verursachen typischerweise solche Flecken auf hochzink Aluminium.",
    symptoms: ["Dunkle/braeunliche Flecken auf 7075", "Schwierig zu entfernen, keine Standard-Cleaner wirken", "Tritt vor allem nach Wechsel von Stahl auf Al auf"],
    rootCause: "Chlor und scharfe EP-Additive in TRIM E206 reagieren mit Zink in 7xxx-Al; Ionen vom Edelstahl koennen Effekt verstaerken.",
    workaround: "Sumpf vor Materialwechsel reinigen; Konzentration im 8-12% Bereich halten; alternative Al-spezifische Produkte (TRIM C290).",
    preventiveMeasure: "Skim regelmaessig, Aerierung, sauberes Wasser, Konzentrat in Wasser nicht umgekehrt; bei Al-Sensitivitaet auf nicht-chlorierten Coolant wechseln.",
    affectedMaterials: ["Aluminum 7075", "Aluminum 2024"],
    affectedOperations: ["Turning", "Milling"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/metalwork-discussion/167130-cnc.html",
    sourceTitle: "Problem Stained aluminum",
    sourceAuthor: "CNCZone user",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM E206",
    manufacturerName: "Master Fluid Solutions",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Phasentrennung im Tank (Coolant separated)",
    description: "Practical-Machinist-Thread 'Trim E206 coolant separated' dokumentiert sichtbare Trennung der Emulsion - hoch konzentrierte Bereiche neben klaren Wasserzonen. Loesungen waren neue Anmischung mit vorgemischter Starter-Charge und Refraktometer-Kontrolle.",
    symptoms: ["Visuelle Schichtung im Tank", "Refraktometer-Werte variieren je Position", "Plastische/oelige Inseln an Oberflaeche"],
    rootCause: "Falsche Mischreihenfolge oder zu hartes/weiches Wasser stoert Emulsifikation; auch Tramp Oil kann Emulsion brechen.",
    workaround: "Tank reinigen, Tramp Oil skimmen, neu mischen.",
    preventiveMeasure: "Konzentrat immer in Wasser (nicht umgekehrt), regelmaessig Tramp Oil entfernen.",
    affectedMaterials: [],
    affectedOperations: ["Milling", "Turning"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/trim-e206-coolant-seperated.322255/",
    sourceTitle: "Trim E206 coolant separated",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM C290",
    manufacturerName: "Master Fluid Solutions",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Konzentrations-Empfindlichkeit fuer Korrosionsschutz auf Aerospace-Aluminium",
    description: "Master Fluid Solutions weist explizit darauf hin, dass C290's Korrosionsschutz auf Aerospace-Al (6061, 7075, 2024) konzentrationsabhaengig ist; Unterkonzentration kann zu Fleckenbildung auf Al fuehren. Anwender in cnczone-Diskussionen ueber TRIM-Synthetics berichten 1% unterhalb Soll = Rostflecken am Tisch, 1% oberhalb = gruenliche Rueckstaende unter Spannmitteln.",
    symptoms: ["Rostflecken unter Konzentration", "Gruenliche Rueckstaende ueber Konzentration", "Klemmende Spannmittel"],
    rootCause: "Synthetisches Inhibitor-System mit engem Konzentrationsfenster.",
    workaround: "Refraktometer taeglich nutzen; Konzentration im engen Sollbereich halten (typ. 6-8%).",
    preventiveMeasure: "Automatische Mischanlage; tagliche Kontrolle.",
    affectedMaterials: ["Aluminum 6061", "Aluminum 7075", "Aluminum 2024"],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.masterfluids.com/na/en-us/products/show-product-description.php?pid=C290",
    sourceTitle: "TRIM C290 Product Description",
    sourceAuthor: "Master Fluid Solutions",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM HyperSol 888NXT",
    manufacturerName: "Master Fluid Solutions",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "Hersteller-Hinweis auf Hautkontakt-Vermeidung",
    description: "Master Fluid Solutions Health-&-Safety-Seite zu HyperSol 888NXT empfiehlt Tragen geeigneter PSA und Vermeidung wiederholten Hautkontakts; Anwender mit empfindlicher Haut koennen ekzematoide Reaktionen entwickeln.",
    symptoms: ["Reizung", "Trockene/rissige Haut bei Dauerexposition"],
    rootCause: "Tenside und alkalisches Milieu wirken entfettend auf Haut.",
    workaround: "Handschuhe (Nitril), Barrierecreme, Pause-Hygiene.",
    preventiveMeasure: "PSA gemaess SDS; Konzentration nicht ueber Soll; Sumpf sauber halten.",
    affectedMaterials: [],
    affectedOperations: ["Aerospace Machining", "Heavy-Duty Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.masterfluids.com/eu/en/products/show-product-health.php?pid=HS888NXT",
    sourceTitle: "TRIM HyperSol 888NXT Health and Safety",
    sourceAuthor: "Master Fluid Solutions",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Anaerobe Bakterien und Geruch bei unbelueftetem Sumpf",
    description: "Practical-Machinist-Diskussionen zu TRIM SOL nennen anaerobe Bakterien als Hauptursache fuer Faeulnisgeruch nach Stillstand. Loesungsansaetze: Fish-Tank-Aerator im Sumpf, UV-Sterilisation, oder geringe Mengen Kupfersulfat (als Notfall-Biozid).",
    symptoms: ["Schwefel-/Faulei-Geruch nach Wochenende", "Schwarzer Belag am Tankboden", "Sinkender pH"],
    rootCause: "Sulfat-reduzierende anaerobe Bakterien (SRB) im sauerstoffarmen Bereich unter Tramp-Oil-Schicht.",
    workaround: "Aeration, Tramp-Oil-Skimmer, Sumpf am Wochenende laufen lassen.",
    preventiveMeasure: "Belueftung (Aquariumpumpe), Skimming, regelmaessige Konzentrationskontrolle, pH > 8.7 halten.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/rancid-coolant.174030/",
    sourceTitle: "Rancid Coolant (TRIM SOL discussion)",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimstar 540",
    manufacturerName: "Cimcool",
    category: "PERFORMANCE",
    severity: "MEDIUM",
    title: "Schlechte Lubrizitaet beim Gewindebohren in Aluminium",
    description: "Anwender berichtet auf Practical Machinist, dass Cimstar 540 beim Tapping von Aluminium zu Aufschmiereffekten am Gewindebohrer fuehrt: Al klebt am Tap, Gewinde wird uebermaessig, Tap-Bruch nach ca. 5 Loechern. Cimcool empfahl zunaechst 10% Konzentration, danach Wechsel auf chloriertes Cimstar 3865.",
    symptoms: ["Aluminium-Aufbauschneide am Tap", "Uebermass im Gewinde", "Tap-Bruch nach ca. 5 Loechern"],
    rootCause: "Geringe EP-/Anti-Welding-Performance der Semisynthetik 540 fuer Al-Tapping.",
    workaround: "Konzentration auf 10% erhoehen oder MQL/Spezial-Tapfluid zusetzen.",
    preventiveMeasure: "Fuer Al-Tapping chloriertes Produkt (Cimstar 3865) oder dediziertes Tapping-Oil einsetzen.",
    affectedMaterials: ["Aluminum"],
    affectedOperations: ["Tapping"],
    reportedConcentration: 10,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/on-cimcool-products-for-coolant.152411/",
    sourceTitle: "? on Cimcool Products for Coolant",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimstar 60C-HFP",
    manufacturerName: "Cimcool",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Starker Geruch im Shop nach wenigen Tagen",
    description: "Practical-Machinist-Anwender melden zu Cimstar 60C-HFP: 'sucks ... smells something awful'. Der Geruch wurde nach wenigen Tagen so stark, dass der Shop fuer Mitarbeiter unangenehm wurde. Andere wechselten daraufhin auf Blaser Synergy 735.",
    symptoms: ["Strenger Geruch nach wenigen Tagen", "Geruchsbelaestigung fuer Mitarbeiter"],
    rootCause: "Vermutlich schnelle Bakterienkolonisation in HFP-Anwendungen mit Aerosolbildung; auch Wechselwirkung mit Tramp Oil moeglich.",
    workaround: "Sumpf-Reinigung, Aeration, Biozid-Zugabe; Wechsel auf alternative Marke.",
    preventiveMeasure: "Konzentration kontrollieren, Skimming, Sumpf-Wartung, ggf. Produkt-Test mit Sample Pail.",
    affectedMaterials: [],
    affectedOperations: ["High Pressure Coolant", "Milling"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-mix-guide-brands-and-practices-asking-if-it-exists-not-offering-advice.409779/",
    sourceTitle: "Coolant mix guide: brands and practices",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimperial 1011",
    manufacturerName: "Cimcool",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Klebrig/fettiger Belag bei Wechsel auf harte Stadtwassersorten",
    description: "CNCZone-/IndustryArena-Thread 'Fresh Coolant becomes sticky and greasy' beschreibt: Cimperial 1011 Green funktionierte jahrelang einwandfrei. Nach Umzug in eine neue Werkstatt mit anderer Wasserquelle wurde der frisch angesetzte Coolant klebrig/fettig, faerbte sich blaeulich, separierte und die Refraktometer-Konzentration fiel. Ursache: hartes Stadtwasser. Loesung: RO-Wasser oder spezifischer Modifier vom Lieferanten.",
    symptoms: ["Klebriger/fettiger Belag", "Blauverfaerbung", "Fallende Refraktometerwerte", "Sichtbare Separation"],
    rootCause: "Hartes Wasser (Ca/Mg-Ionen) zerstoert Emulgatoren und faellt Coolant-Komponenten aus (Seifen-Bildung).",
    workaround: "RO-/DI-Wasser fuer Mischen verwenden, alternativ Hartwasser-Modifier vom Cimcool-Vertreter.",
    preventiveMeasure: "Wasserprobe an Lieferanten senden, Hartwasser-RO-System fuer Coolant-Anmischwasser.",
    affectedMaterials: [],
    affectedOperations: ["Milling", "Turning"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/general-metalwork-discussion/33603-fresh-coolant-becomes-sticky-greasy.html",
    sourceTitle: "Fresh Coolant becomes sticky and greasy (Cimperial 1011)",
    sourceAuthor: "CNCZone / IndustryArena users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimperial 1011",
    manufacturerName: "Cimcool",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Sumpf-Lebensdauer 6-12 Monate bis Geruchsbildung",
    description: "Practical-Machinist-Anwender berichten zu Cimperial 1011: Sumps halten typischerweise nur 6 Monate bis 1 Jahr, bevor sie zu stinken beginnen. Wechsel auf andere Produkte (z.B. Hangsterfer's) ergab laengere Standzeiten.",
    symptoms: ["Geruch nach 6-12 Monaten", "Notwendigkeit zum Komplett-Wechsel"],
    rootCause: "Begrenzte Biostabilitaet der aelteren Soluble-Oil-Formulierung.",
    workaround: "Vor Geruchsentwicklung Sumpf-Service / Komplettwechsel.",
    preventiveMeasure: "Aeration, Tramp-Oil-Skimmen, Konzentration > 6%; oder Wechsel auf neuere/biostabilere Formulierung.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://alt.machines.cnc.narkive.com/oVafNg1v/coolant-the-never-ending-headache-hangsterfer-s-cimcool-trim",
    sourceTitle: "Coolant the never ending headache (Hangsterfer's - Cimcool - Trim)",
    sourceAuthor: "alt.machines.cnc users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimperial 1070",
    manufacturerName: "Cimcool",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Bevorzugt wegen besserer Lubrizitaet und Geruch nach Wechsel von Synthetik",
    description: "Practical-Machinist-Diskussion: ein Shop wechselte von Cimtech 500 (Synthetik) auf Cimperial 1070, weil das Synthetik-Produkt durch alkalischen pH Aluminium aetzte. Cimperial 1070 wird positiv beschrieben (bessere Standzeit, Geruch). Dies dokumentiert indirekt das Aetzproblem der Synthetik-Linie auf Al-Teilen.",
    symptoms: ["Aluminium-Aetzung bei Cimtech 500-Vorgaenger", "Schlechter Geruch beim Vorgaenger"],
    rootCause: "Hoher pH/Alkalinitaet von Synthetik etzt Al; Cimperial 1070 (Soluble Oil) puffert besser.",
    workaround: "Wechsel auf Soluble Oil mit milderem pH-Profil.",
    preventiveMeasure: "Bei Al-lastiger Produktion auf Soluble-Oil oder Al-spezifische Synthetik (Cimtech 320-HFP) gehen.",
    affectedMaterials: ["Aluminum"],
    affectedOperations: ["Milling", "Drilling"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/metalwork-discussion/16382-coolant-using.html",
    sourceTitle: "COOLANT (what are you using?) - CNCZone",
    sourceAuthor: "CNCZone user",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimtech 95",
    manufacturerName: "Cimcool",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Nicht geeignet fuer Magnesium, Buntmetall, Hartmetall",
    description: "Cimcool Cimtech 95 Datenblatt warnt explizit: NICHT verwenden auf Magnesiumlegierungen, Buntmetallen oder Hartmetall. Einsatz auf Mg birgt Risiko fuer H2-Freisetzung; auf Buntmetall Verfaerbung; auf Hartmetall Cobalt-Leaching durch synthetisches Inhibitor-System.",
    symptoms: ["Wasserstoff-Entwicklung an Mg", "Verfaerbung auf Cu/Ms", "Cobalt-Auswaschung an Hartmetall (graue Verfaerbung)"],
    rootCause: "Synthetische Formulierung enthaelt Aminkomplexbildner, die Co loesen; alkalisches Milieu reagiert mit Mg.",
    workaround: "Fuer Mg/Buntmetall/Hartmetall dediziertes Produkt verwenden (z.B. Hocut 5019 fuer Hartmetallschleifen).",
    preventiveMeasure: "Material-Compatibility-Check VOR Coolant-Auswahl; SDS und PDS lesen.",
    affectedMaterials: ["Magnesium", "Brass", "Bronze", "Tungsten Carbide"],
    affectedOperations: ["Grinding"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.centrictool.com/article/grinding-coolants-cimtech-95-cx461a-and-kool-mist",
    sourceTitle: "Centric Grinding Coolants Cimtech 95, CX461A, and Kool Mist",
    sourceAuthor: "Centric Tool / Cimcool",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimtech 320",
    manufacturerName: "Cimcool",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Sticky/Slimy Belag bei alkalischer Synthetik nach Monaten",
    description: "Practical-Machinist-Anwender berichten zu Cimcool-Synthetics (Cimtech 320/495): Anfangs sehr gut, nach ca. 3 Monaten 'varnish' und gooey, klebriger Belag an allen Maschinen-Innenflaechen. Wechsel auf Semi-Synthetik (Cimstar 540) loeste das Problem.",
    symptoms: ["Klebrig-glaenzender Belag innen", "Filter verstopfen", "Schmierschicht auf Spritzschutz"],
    rootCause: "Polymer-Lubricity-Additive in Synthetic Coolants polymerisieren bei Temperatur/Verdunstung und bilden Filme.",
    workaround: "Regelmaessige Reinigung mit Cimcool Cimkleen oder Wechsel auf Semi-Synthetik.",
    preventiveMeasure: "Konzentration strikt einhalten; bei dauerhafter Aerosol-Verdunstung Kondensat zurueckspeisen.",
    affectedMaterials: [],
    affectedOperations: ["Heavy-Duty Machining", "Aerospace"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/switching-coolants-has-anyone-used-cimcool-m310.206997/",
    sourceTitle: "Switching Coolants - Has anyone used CIMCOOL M310",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimtech 510",
    manufacturerName: "Cimcool",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Lackangriff bei Ueberkonzentration",
    description: "Practical-Machinist-Diskussion: Cimtech-Synthetic-Linie kann bei Ueberkonzentration Maschinen-Lack angreifen, ablaesen oder weich machen - typisch fuer Synthetics mit hohem pH/Aminanteil. Anwender berichten ueber 'paint thinner-aehnliche' Wirkung wenn Konzentration aus dem Ruder laeuft.",
    symptoms: ["Lack wird weich", "Lack-Abblaetterung in Tank-Naehe", "Lack-Verfaerbung"],
    rootCause: "Alkaline Amine und Glykole loesen einige Lacksysteme bei Ueberkonzentration.",
    workaround: "Konzentration zureck auf Soll (typ. 4-7%); Lack-Schaden mit 2K-Lack reparieren.",
    preventiveMeasure: "Refraktometer-Disziplin; bei neuer Maschine Lackvertraeglichkeit testen.",
    affectedMaterials: ["Machine Paint"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-and-oil-proof-paint.302405/",
    sourceTitle: "Coolant and oil proof paint",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimstar QUAL",
    manufacturerName: "Cimcool",
    category: "BIOLOGY",
    severity: "LOW",
    title: "Rancidity-Risiko bei nicht eingehaltener Konzentration (Hersteller-Hinweis)",
    description: "Cimcool weist im PIF zu Cimstar Qual Star explizit darauf hin, dass gute Rancidity-Kontrolle nur bei korrekt eingehaltener Konzentration gegeben ist. Anwender im Forum bezeichneten 'Qualstar C' als unbefriedigend bei Vernachlaessigung der Konzentration.",
    symptoms: ["Geruch bei Unterkonzentration", "Verkuerzte Sumpfstandzeit"],
    rootCause: "Biozidpaket greift nur im engen Konzentrationsfenster (typ. 6-8%); Unterkonzentration = unzureichende Inhibitor-Wirkung.",
    workaround: "Konzentrationskontrolle taeglich; ggf. Tank-Side-Additive zur Stabilisierung.",
    preventiveMeasure: "Refraktometer + automatische Anmischung; Sumpf-Logging.",
    affectedMaterials: [],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "http://www.cimcool.com/wp-content/uploads/manage-msds-pif/pif/CIMSTAR QUALSTAR XL.pdf",
    sourceTitle: "Cimstar Qual Star XL PIF",
    sourceAuthor: "Cimcool",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimcool C140",
    manufacturerName: "Cimcool",
    category: "CORROSION",
    severity: "LOW",
    title: "Rostbildung an Maschine bei Pink-Pail-Cimcool-Produkten",
    description: "Practical-Machinist-Anwender berichtet, dass ein Kollege mit einem 'pink pail' Cimcool-Produkt deutliche Rostbildung auf der Maschine bekam. Forenmehrheit erklaert dies meist mit falscher Verduennung oder unzureichendem Mischen, doch das Problem trat reproduzierbar auf, bis Konzentration nachgebessert war.",
    symptoms: ["Rost auf Tisch", "Rost an blanken Spannmitteln", "Korrosion am Werkstueck"],
    rootCause: "Unterkonzentration unter ca. 5% lass Korrosionsschutz unwirksam werden; Konzentrat nicht ausreichend dispergiert.",
    workaround: "Refraktometer-Pruefung, Konzentration auf Soll, Maschine entrosten.",
    preventiveMeasure: "Auto-Dosing-Anlage, taegliches Konzentrations-Logging.",
    affectedMaterials: ["Steel", "Cast Iron"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/switching-coolants-has-anyone-used-cimcool-m310.206997/",
    sourceTitle: "Pink-pail Cimcool rusted machine (anecdote)",
    sourceAuthor: "Practical Machinist user",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Hautreizung / Sensibilisierung / Atemwegssymptome (Hersteller-SDS)",
    description: "Hocut 795-H SDS warnt explizit: wiederholter/laengerer Hautkontakt kann Hautreizung, Dermatitis und Sensibilisierung bei empfindlichen Personen verursachen. Symptome moeglicher allergischer Reaktionen: Hautausschlag, Juckreiz, Schwellung, Atembeschwerden, Kribbeln an Haenden/Fuessen, Schwindel, Brustschmerzen, Muskelschmerzen, Hitzewallungen.",
    symptoms: ["Hautausschlag", "Juckreiz", "Atembeschwerden", "Schwellung", "Kribbeln Haende/Fuesse"],
    rootCause: "Bestandteile (Emulgatoren, EP-Additive, Biozide) koennen Kontakt- oder allergische Dermatitis ausloesen; Aerosole koennen Atemwege reizen.",
    workaround: "Sofortige PSA, Hautwaesche; bei anhaltenden Symptomen Arbeitsplatz wechseln/Arzt.",
    preventiveMeasure: "Nitril-Handschuhe, Schutzbrille, Aerosol-Absaugung, Barriere-Creme, Konzentration im Soll halten.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "SDS",
    sourceUrl: "https://www1.mscdirect.com/MSDS/MSDS00028/65349094-20201128.PDF",
    sourceTitle: "Hocut 795-H Safety Data Sheet (rev. 2019-09-01 v.7)",
    sourceAuthor: "Quaker Houghton",
    sourceDate: "2019-09-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 795 MP-B",
    manufacturerName: "Quaker Houghton",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Brauner wachsiger Belag an Maschine und reduzierte Standzeit",
    description: "Practical-Machinist-Thread 'Hocut 795B issues' (User 'Royal' u.a.): Anwender, die jahrelang erfolgreich Hocut 795B fuhren, beobachten plotzlich brauner wachsiger Belag an Maschinen-Innenflaechen und kuerzere Standzeit. Hersteller-Vertreter erklaerte es als 'Maschinen-Fett'; doch Anwender beobachteten es auch bei Maschinen mit rotem Fett (also nicht Fett). Hoehere Konzentration brachte keine Besserung. Vermutung: schleichende Formula-Aenderung oder Drum jenseits Shelf-Life.",
    symptoms: ["Brauner wachsiger Belag", "Reduzierte Standzeit", "Schmierschicht an Spritzschutz", "Anbackungen am Werkstueck"],
    rootCause: "Vermutete Reformulierung; alternativ ueberlagertes Konzentrat (Hersteller-Statement 'shelf life ueberschritten').",
    workaround: "Sumpf entleeren, ultrasonic cleaning, neues Drum mit pruefbarer Charge; alternativ Wechsel auf 795-H oder MP.",
    preventiveMeasure: "Charge/Shelf-Life beim Lieferanten pruefen; Lab-Analyse vom Anwender als Trigger fuer Lieferanten-Audit.",
    affectedMaterials: ["Aluminum 6061", "Aluminum 7075"],
    affectedOperations: ["Aerospace Machining", "Heavy-Duty Milling"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/hocut-795b-issues.361622/",
    sourceTitle: "Hocut 795B issues",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 795 MP-B",
    manufacturerName: "Quaker Houghton",
    category: "FILTRATION",
    severity: "LOW",
    title: "Emulsifier 'frisst' Tramp Oil - schwer skimmbar bei 795-H",
    description: "Vergleichsdiskussion im Practical-Machinist-Thread: Die Emulgatoren in Hocut 795-H sind sehr stark - das fuehrt dazu, dass Tramp-Oil aus Schlittenfuehrungen sich nicht skimmen laesst, sondern in die Emulsion eingebaut wird. Folge: kontinuierliche Drift der Coolant-Qualitaet bei Maschinen mit Way-Lube-Leckage. Andere Varianten (795-KB) erlauben besseres Skimmen.",
    symptoms: ["Tramp Oil kann nicht abgeschoepft werden", "Coolant wird mit Zeit truebe/dunkel", "Konzentrations-Drift"],
    rootCause: "Aggressive Emulgatoren binden Way-Lube/Hydraulikoel.",
    workaround: "Wechsel auf Hocut 795-KB/MP fuer leichteres Skimming; Way-Lube-Leckage reduzieren.",
    preventiveMeasure: "Way-Lube-Verbrauch monitoren; Coolant mit Tramp-Oil-Rejektion waehlen wo Way-Lube hoch ist.",
    affectedMaterials: [],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-hocut-795-kb.121133/",
    sourceTitle: "Coolant, Hocut 795 kb",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Cast-Aluminium-Mikroporositaet absorbiert Oelphase",
    description: "Practical-Machinist-Thread 'Cast Aluminum Scavenges Oil out of Coolant': MIC6-Cast-Al hat ueberall Mikroporen; beim Aushoehlen der Pockets wirken diese als Schwaemme fuer die Oel-Phase einer Semisynthetik-Emulsion wie Hocut 795-B. Folge: Coolant verarmt schnell an Oel, Konzentration im Tank steigt scheinbar (Wasser bleibt zurueck), Standzeit sinkt.",
    symptoms: ["Schnelles Absinken der Oel-Faction", "Hoher Concentrate-Verbrauch", "Werkstuecke 'saugen' Coolant"],
    rootCause: "Mikroporositaet von Cast Al absorbiert Oel-Phase praeferentiell.",
    workaround: "Niedrigere Oel-Coolant-Familie (mehr Synthetik) waehlen oder Top-Up mit erhoehter Konzentration.",
    preventiveMeasure: "Bei viel MIC6-Volumen TRIM C290 oder vollsynthetisches Aerospace-Produkt evaluieren.",
    affectedMaterials: ["Cast Aluminum MIC6"],
    affectedOperations: ["Pocket Milling"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/cast-aluminum-scavenges-oil-out-of-coolant.447319/",
    sourceTitle: "Cast Aluminum Scavenges Oil out of Coolant",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 4260",
    manufacturerName: "Quaker Houghton",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Eingeschraenkt auf Low/Medium Duty - hohe Anforderungen koennen ueberfordern",
    description: "Quaker Houghton TDS: Hocut 4260 ist explizit fuer 'low to medium duty' Aerospace-Bearbeitung ausgelegt. Bei Heavy-Duty-Operationen (Ti-Vollnut, hochbelastete Inconel-Bearbeitung) kann die Lubrizitaet ungenuegend sein. BAE-AMS-AM00-00-01-Freigabe gilt fuer typische Airframe-Anwendungen; Heavy-Duty erfordert 4940/795-B.",
    symptoms: ["Standzeit-Drop bei harten Materialien", "Erhoehte Standzeit beim Wechsel auf 4940/795B"],
    rootCause: "Boron-/Formaldehyd-freie Formulierung mit konservativer EP-Beladung.",
    workaround: "Fuer Heavy-Duty auf Hocut 4940 oder 795-B wechseln.",
    preventiveMeasure: "Anwendungsklasse vor Auswahl mit Quaker Houghton abklaeren.",
    affectedMaterials: ["Titanium", "Inconel"],
    affectedOperations: ["Heavy-Duty Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://home.quakerhoughton.com/wp-content/uploads/2022/03/tds_HOCUT-4260_AM_EN.pdf",
    sourceTitle: "HOCUT 4260 Technical Data Sheet",
    sourceAuthor: "Quaker Houghton",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Generelle KSS-Dermatitis und Atemwegsrisiken (OSHA/NIOSH)",
    description: "OSHA Metalworking Fluids - Health Effects Seite listet allergische und reizende Kontaktdermatitis sowie Asthma/Bronchitis/Hypersensitivity-Pneumonitis als dokumentierte Risiken bei wassermischbaren KSS wie Hocut 795-Serie. NIOSH empfiehlt MWF-Aerosol-TWA von 0.4 mg/m3 (thorakal) bzw. 0.5 mg/m3 (Gesamtstaub) ueber 10 Std./Tag.",
    symptoms: ["Allergische Kontaktdermatitis", "Irritative Dermatitis", "Asthma/Bronchitis", "Hypersensitivity Pneumonitis (selten)"],
    rootCause: "Aerosol-Exposition, Endotoxine aus Bakterien, sensibilisierende Inhaltsstoffe (Biozide, Emulgatoren).",
    workaround: "Aerosol-Absaugung, PSA, Sumpf-Mikrobiologie kontrollieren.",
    preventiveMeasure: "NIOSH-PEL einhalten, Health Surveillance, regelmaessige Bakterien-Dipslides.",
    affectedMaterials: [],
    affectedOperations: ["High-Pressure Coolant", "Misting Operations"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.osha.gov/metalworking-fluids/health-effects",
    sourceTitle: "OSHA - Metalworking Fluids Health Effects",
    sourceAuthor: "U.S. OSHA",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Hypersensitivity Pneumonitis durch mikrobiell kontaminierte KSS (CDC/NIOSH HHE)",
    description: "NIOSH HHE-Reports dokumentieren Faelle von Hypersensitivity Pneumonitis (HP) bei Bearbeitern mit Exposition gegenueber kontaminierten wassermischbaren KSS. Auch wenn nicht produktspezifisch fuer TRIM SOL, betrifft Risiko jeden Soluble-Oil/Semi-Synthetik-Sumpf mit unzureichender Mikrobiologie-Kontrolle.",
    symptoms: ["Husten", "Atemnot", "Fieber nach Schichtende", "Lungenfunktionsverlust ueber Monate"],
    rootCause: "Mycobacterium immunogenum, Endotoxine aus Gram-negativen Bakterien, mikrobielle Antigene in Aerosolen.",
    workaround: "Sumpf-Service, Mitarbeiter aus Exposition, medizinische Abklaerung.",
    preventiveMeasure: "Regelmaessige Bakterien-/Endotoxin-Messung, Aerosol-Absaugung, Biozid-Management, Mitarbeiter-Schulung.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.cdc.gov/niosh/hhe/reports/pdfs/2014-0170-3263.pdf",
    sourceTitle: "NIOSH HHE Report 2014-0170-3263 - Metalworking Fluid Exposure and Dermatitis",
    sourceAuthor: "U.S. CDC/NIOSH",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 4260",
    manufacturerName: "Quaker Houghton",
    category: "WORKPIECE_STAINS",
    severity: "LOW",
    title: "Aerospace-Aluminium Stain-Praevention - Konzentrationsabhaengig",
    description: "Quaker Houghton Hocut 4260 Datenblatt betont Inhibition von Aluminium-Staining und Sumpf-Reinheit - jedoch konzentrationsabhaengig. Anwender mit zu niedriger Konzentration berichten in allgemeinen Aerospace-Foren ueber leichte Staining bei sensitiven Legierungen (2024, 7075), wenn Werkstuecke unmittelbar nach Bearbeitung nicht abgetrocknet werden.",
    symptoms: ["Leichte Flecken auf 2024/7075 wenn Coolant verdunstet", "Dunkle Schatten nach Trocknung"],
    rootCause: "Konzentrations-Unterschreitung; Kontakt mit eintrocknendem Coolant katalysiert Oxidation hochzinkiger Al-Legierungen.",
    workaround: "Werkstuecke direkt nach Bearbeitung mit DI-Wasser abspuelen und trocknen.",
    preventiveMeasure: "Konzentration auf TDS-Mittelwert halten; Stillstand-Werkstuecke abdecken.",
    affectedMaterials: ["Aluminum 2024", "Aluminum 7075"],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://home.quakerhoughton.com/wp-content/hub/Files/bro_hocut-4260_aerospace_overview_EN_GL_A4.pdf",
    sourceTitle: "HOCUT 4260 Aerospace Overview",
    sourceAuthor: "Quaker Houghton",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimperial 1010",
    manufacturerName: "Cimcool",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Hartwasser-Empfindlichkeit der klassischen Soluble-Oil-Linie",
    description: "Cimperial 1010/1011 sind klassische Soluble Oils der gleichen Familie; CNCZone-Threads zur 1011-Variante belegen Hartwasser-Empfindlichkeit (Klebrigkeit, blaeuliche Verfaerbung, Refraktometer-Drift). Cimcool empfiehlt bei Hartwasser entweder modifiziertes Produkt oder RO-Wasser zum Anmischen.",
    symptoms: ["Klebriger Belag bei Hartwasser", "Konzentration faellt am Refraktometer", "Sichtbare Seifenflocken"],
    rootCause: "Calcium/Magnesium-Ionen reagieren mit Anionen-Emulgatoren - Kalkseifen-Ausfaellung.",
    workaround: "Hartwasser-Modifier vom Vertreter, RO-Wasser fuer Topup.",
    preventiveMeasure: "Wasseranalyse vor Erstanwendung.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://en.industryarena.com/forum/fresh-coolant-becomes-sticky-greasy--33603.html",
    sourceTitle: "Fresh Coolant becomes sticky and greasy (Cimperial 10x family)",
    sourceAuthor: "IndustryArena users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimperial 1070",
    manufacturerName: "Cimcool",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Nicht geeignet fuer Magnesiumlegierungen",
    description: "Cimcool PIF Cimperial 1070 weist explizit aus: NICHT fuer Magnesiumlegierungen. Reaktion mit Mg kann Wasserstoff-Entwicklung verursachen (Brandgefahr). Fuer Edelstahl, gehaertete Staehle, Exoten und meisten Al-Legierungen freigegeben.",
    symptoms: ["H2-Entwicklung an Mg-Spaenen", "Selbsterhitzung an Mg-Spaenen im Container"],
    rootCause: "Mg + H2O -> Mg(OH)2 + H2; alkalische Coolant-Komponenten beschleunigen Reaktion.",
    workaround: "Fuer Mg dediziertes Schneidoel oder MQL.",
    preventiveMeasure: "Material-Compatibility-Check; Mg-Spaene getrennt sammeln; SDS lesen.",
    affectedMaterials: ["Magnesium"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.cimcool.com.au/PIF_pdfs/Cimperial/CIMPERIAL_1070_ENG.pdf",
    sourceTitle: "Cimperial 1070 Product Information Flyer",
    sourceAuthor: "Cimcool",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "STABILITY",
    severity: "LOW",
    title: "Lange Standzeit aber empfindlich auf Stahl-Spaene unter Coolant-Level",
    description: "Practical-Machinist-User berichten: TRIM SOL halt in Al-Anwendungen sehr lange (5+ Jahre Sumpf), aber wenn Stahl-Spaene unterhalb des Coolant-Levels liegen bleiben, geht der Sumpf 'eventually bad' - Faulgase, Geruch, gesunkene Konzentration.",
    symptoms: ["Geruch trotz lang gepflegtem Sumpf", "Schwarze Spaeneschicht am Boden", "pH-Drop"],
    rootCause: "Sulfat-reduzierende Bakterien (SRB) im sauerstoffarmen Bereich unter Stahlspaeneschicht; Eisenionen katalysieren Emulsifier-Abbau.",
    workaround: "Spaene regelmaessig vakuumieren; Boden-Skimmer; Wochenend-Pumpen.",
    preventiveMeasure: "Effiziente Spaene-Foerderung; magnetische Separation bei Stahl; Boden-Aerator.",
    affectedMaterials: ["Steel"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/metalwork-discussion/138240-cnc.html",
    sourceTitle: "What coolant do you like and why?",
    sourceAuthor: "CNCZone users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "CORROSION",
    severity: "LOW",
    title: "Boeing BAC-5008 Approval - Stain-frei nur bei Soll-Konzentration",
    description: "Hocut 795-B/H haelt Boeing-BAC-5008-Freigabe (Klassen 1-6) und wird als 'corrosion protection without staining' beworben. Hersteller-Hinweis im TDS: Stain-Freiheit gilt fuer den Soll-Konzentrationsbereich; ausserhalb des Bereichs treten Staining-Risiken auf - besonders an 7075-T6 und 2024.",
    symptoms: ["Staining bei Unterkonzentration", "Korrosion bei Sumpf-Drift"],
    rootCause: "Inhibitor-System wirkt im engen Konzentrationsfenster; aerospaceige Hochzink-Al sind sensitiv.",
    workaround: "Konzentration im Soll-Bereich halten (typ. 6-10%).",
    preventiveMeasure: "Auto-Dosing; tagliche Refraktometrie + Korrekturfaktor.",
    affectedMaterials: ["Aluminum 7075-T6", "Aluminum 2024"],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://home.quakerhoughton.com/wp-content/uploads/2022/03/TDS_HOCUT-795-B_EN.pdf",
    sourceTitle: "HOCUT 795 B Technical Data Sheet",
    sourceAuthor: "Quaker Houghton",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimstar PRO",
    manufacturerName: "Cimcool",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Synthetic-Coolants etzen Aluminium bei Sumpf-Ueberalterung",
    description: "Practical-Machinist-User berichten allgemein zur Cimcool-Synthetic-Linie (Cimtech, Cimstar PRO-Familie): alkalischer pH (typ. 9.2-9.6) kann Al aetzen, besonders bei langer Standzeit (CO2-Aufnahme/pH-Drift) oder bei Werkstuecken mit Verweildauer im Coolant. Wechsel auf Cimperial 1070 (Soluble Oil mit milderem pH) loeste Aetzproblem.",
    symptoms: ["Mattgeaetzte Oberflaeche an Al-Werkstuecken", "Wei.licher Belag nach Trocknung", "Maeasiv-Druckanzeichen"],
    rootCause: "Alkalischer pH plus Amin-/Glykol-Anteile loesen Al-Oxidschicht und greifen Grundmetall an.",
    workaround: "Werkstuecke nicht im Coolant ablegen; nach Bearbeitung mit DI-Wasser spuelen und trocknen.",
    preventiveMeasure: "Al-spezifisches Produkt (Cimtech 320-HFP, TRIM C290) verwenden; pH unter 9.3 halten.",
    affectedMaterials: ["Aluminum"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/metalwork-discussion/16382-coolant-using.html",
    sourceTitle: "COOLANT discussion - Cimcool synthetic vs Cimperial soluble oil",
    sourceAuthor: "CNCZone users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM C290",
    manufacturerName: "Master Fluid Solutions",
    category: "BIOLOGY",
    severity: "LOW",
    title: "Synthetik-Aerospace-Al-Coolants ohne Oel-Bestandteile koennen Rost auf Maschinenteilen verursachen",
    description: "Generischer Hinweis aus Forum-Diskussion zu TRIM-Synthetics (C290 ist Synthetic for Aluminum) und Trim C350-Praxisfall: Volle Synthetics ohne Oel-Bestandteil schuetzen Werkstueck gut, aber Maschinenteile (Tisch, Tool-Taper) koennen rosten, weil die schmierende Oelfilm-Schicht fehlt. Loesung war Semi-Synthetik mit etwas Oelanteil.",
    symptoms: ["Rost auf Tool-Taper", "Rost auf Tisch nach Stillstand", "Rost auf Vises"],
    rootCause: "Vollsynthetic ohne Oelfilm laesst Stahlteile nach Eintrocknung ungeschuetzt.",
    workaround: "Maschine nach Schichtende mit Spindel-Schutzkappe; regelmaessiges Einlegen von Way-Oil.",
    preventiveMeasure: "Bei viel Stahlguss-Bearbeitung Semi-Synthetik mit oelhaltiger Phase einsetzen.",
    affectedMaterials: ["Steel", "Cast Iron"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.cnczone.com/forums/uncategorised-metalworking-machines/174564-trim-c350-coolant-rusting-issues-haas-mini.html",
    sourceTitle: "Trim C350 Coolant - Rusting Issues - HAAS Mini Mill (analog to C290)",
    sourceAuthor: "CNCZone users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cindol 305D",
    manufacturerName: "Quaker Houghton",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Soluble Coolant - korrekte Konzentration kritisch fuer Bio-Stabilitaet",
    description: "Quaker Houghton TDS Cindol 305D: bewirbt 'excellent rust preventive properties and biostability' fuer trouble-free operation - jedoch implizit konzentrationsabhaengig. Anwender ohne Refraktometer-Disziplin riskieren bei Unterkonzentration sowohl Korrosion als auch verkuerzte Standzeit, da der Inhibitor-Effekt unter ca. 5% nachlaesst.",
    symptoms: ["Geruch bei Unterkonzentration", "Korrosion an Werkstueck/Maschine", "Verkuerzte Standzeit"],
    rootCause: "Soluble-Oil-Inhibitor-System wirkt erst ueber Mindest-Konzentration.",
    workaround: "Konzentration auf TDS-Soll bringen.",
    preventiveMeasure: "Tagliches Konzentrations-Logging; Refraktometer-Korrekturfaktor anwenden.",
    affectedMaterials: ["Steel", "Cast Iron"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://dtsindustrial.com/media/productattach/c/i/cimstar_540.pdf",
    sourceTitle: "Cindol 305D Product Description (via Distributor)",
    sourceAuthor: "Quaker Houghton / Toolprocure",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "STABILITY",
    severity: "LOW",
    title: "Konzentrations-Probleme verursachen 80% der Trouble-Calls (Hersteller-Bulletin)",
    description: "Master Fluid Solutions Blog (2021-11-23) erklaert offiziell: 'well over 80% of the trouble calls received are directly or indirectly attributable to poor concentration control.' Gilt fuer alle TRIM-Produkte einschliesslich TRIM SOL/MicroSol/E206 - die meisten Coolant-Probleme entstehen durch falsche Konzentration, nicht durch das Produkt selbst.",
    symptoms: ["Vielfaeltige Symptome (Korrosion, Geruch, Stain, Foam) ruckverfolgbar auf falsche Konzentration"],
    rootCause: "Mangelnde Refraktometer-Disziplin, falsche Korrekturfaktoren, ungenaue Auto-Dosier-Anlagen.",
    workaround: "Tagliches Konzentrations-Log mit Refraktometer.",
    preventiveMeasure: "Schulung Operatoren; Auto-Mixer mit Soll-Korrekturfaktor; Wochenend-Topup mit Mix nicht Wasser.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.masterfluids.com/blog/2021/11/23/4-common-coolant-maintenance-problems-and-how-to-solve-them/",
    sourceTitle: "4 Common Coolant Maintenance Problems and How to Solve Them",
    sourceAuthor: "Master Fluid Solutions",
    sourceDate: "2021-11-23",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "BIOLOGY",
    severity: "LOW",
    title: "Hard-Water-Compatibility und Bio-Stabilitaet als Hersteller-Versprechen",
    description: "Hocut 795-H TDS: 'compatible with hard water, clean-running and biostable assuring long, odor-free sump life'. Anwender bestaetigen oft lange Standzeit - dennoch berichtet ein Subset Geruchsentwicklung bei Werkzeugmaschinen mit hohem Way-Lube-Eintrag (Tramp Oil), die das Bio-Stable-Versprechen unterminieren.",
    symptoms: ["Vereinzelt Geruchsentwicklung trotz 'biostable' Etikett", "Way-Lube-Vermengung im Tank"],
    rootCause: "Tramp Oil verdraengt Biozid-Aktivitaet; anaerobe Zonen entstehen.",
    workaround: "Tramp-Oil-Skimmer installieren; Way-Lube-Verbrauch reduzieren.",
    preventiveMeasure: "Way-Lube-Niveau am Tank pruefen; Coalescer im Sumpf.",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://dtsindustrial.com/media/productattach/h/o/hocut_795-h_pds_3.pdf",
    sourceTitle: "Hocut 795-H Product Data Sheet",
    sourceAuthor: "Quaker Houghton",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimperial 1011",
    manufacturerName: "Cimcool",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Nicht fuer Mg-Legierungen freigegeben (SDS-Hinweis)",
    description: "Cimperial 1011 MSDS und PIF: das Produkt ist freigegeben fuer Carbon Steel, HSS, Cast Steels, Alloyed Steels, Tool Steels, Stainless Steel, Cast Iron und most non-ferrous alloys - explizit NICHT fuer Magnesiumlegierungen.",
    symptoms: ["H2-Entwicklung beim Kontakt mit Mg-Spaenen", "Brandgefahr bei Magnesiumbearbeitung"],
    rootCause: "Wassergehalt + alkalische Komponenten reagieren mit Mg.",
    workaround: "Mg getrennt mit dediziertem Schneidoel.",
    preventiveMeasure: "Material-Compatibility-Check vor Auswahl.",
    affectedMaterials: ["Magnesium"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "http://www1.mscdirect.com/MSDS/MSDS00024/71455745-20070518.PDF",
    sourceTitle: "CIMPERIAL 1011 Product Information / SDS",
    sourceAuthor: "Cimcool",
    sourceDate: "2007-05-18",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "TRIM MicroSol 685XT",
    manufacturerName: "Master Fluid Solutions",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Mindestkonzentration 7.5% fuer beste Standzeit/Korrosionsschutz",
    description: "Master Fluid Solutions Application-Notes: 'running at or above 7.5% concentration offers the best sump life and corrosion inhibition' fuer MicroSol 685/685XT. Anwender, die zur Kostenreduktion bei 5-6% laufen, riskieren verkuerzte Sumpf-Standzeit und Rost - oft erst nach Monaten sichtbar.",
    symptoms: ["Korrosion an Tisch/Vises nach Wochen", "Kurzere Sumpf-Lebensdauer als erwartet"],
    rootCause: "Unterkonzentration laesst Inhibitor-System unwirksam werden.",
    workaround: "Konzentration auf 7.5%-9% anheben.",
    preventiveMeasure: "Auto-Mixer; Refraktometer-Disziplin; Operator-Schulung.",
    affectedMaterials: ["Steel", "Cast Iron"],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.masterfluids.com/na/en-us/products/show-product-concentrations-coolants.php?pid=MS685XT",
    sourceTitle: "TRIM MicroSol 685XT Recommended Concentrations",
    sourceAuthor: "Master Fluid Solutions",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Anwender bemerkt formula-bedingte Aenderung in juengerer Zeit",
    description: "Practical-Machinist-Anwender: 'jahrelang gluecklich mit Hocut 795B, bis sie glauben, die Formel sei geandert worden'. Symptome (brauner wachsiger Belag, kuerzere Standzeit) traten ohne Aenderung der Anwendungspraxis auf. Hersteller-Reps gaben unterschiedliche Ursachen-Erklaerungen (Maschinen-Fett, Shelf-Life).",
    symptoms: ["Plotzliche Performance-Aenderung ohne Aenderung in Praxis", "Brauner Belag", "Standzeit-Drop"],
    rootCause: "Hypothese Formula-Anpassung (z.B. wegen REACH/EU-Verbotsstoff-Substitution); Quaker Houghton hat keine offizielle Aenderung kommuniziert.",
    workaround: "Charge/Batch-Nummer pruefen; bei Anhalt Probe an Hersteller einsenden.",
    preventiveMeasure: "Coolant-Audit bei jedem Drum-Wechsel; Hersteller-Sample-Pail vor Wechsel zur Charge.",
    affectedMaterials: [],
    affectedOperations: ["Aerospace Machining"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/hocut-795b-issues.361622/",
    sourceTitle: "Hocut 795B issues - 'formula changed?'",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "TRIM SOL",
    manufacturerName: "Master Fluid Solutions",
    category: "REGULATORY",
    severity: "LOW",
    title: "Allgemeines KSS-Aerosol-Limit NIOSH 0.4 mg/m3 - gilt auch fuer TRIM SOL Mist",
    description: "NIOSH-Empfehlung (98-102): Aerosole wassermischbarer KSS auf 0.4 mg/m3 (thorakal) bzw. 0.5 mg/m3 (Gesamtstaub) TWA ueber 10h/Tag, 40h/Woche limitieren. TRIM SOL als Soluble Oil-Emulsion fallt unter diese Empfehlung. Maschinen ohne Aerosol-Absaugung koennen das Limit schnell ueberschreiten.",
    symptoms: ["Mist-Wolken in der Werkshalle", "Husten/Niesen bei Operatoren", "Beschlag auf Brillen/Decken"],
    rootCause: "High-Pressure-Coolant-Anwendungen ohne Misting-Filter; ungenuegende Hallenbelueftung.",
    workaround: "Aerosol-Absaugung an Maschine; Hallen-Lufttechnik.",
    preventiveMeasure: "Aerosol-Messung; Misting-Filter; Kabinen-Einhausung; PSA.",
    affectedMaterials: [],
    affectedOperations: ["High-Pressure Coolant", "Misting Operations"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.cdc.gov/niosh/docs/98-102/default.html",
    sourceTitle: "NIOSH Occupational Exposure to Metalworking Fluids (98-102)",
    sourceAuthor: "U.S. CDC/NIOSH",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Cimstar 60C-HFP",
    manufacturerName: "Cimcool",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Wechselempfehlung wegen geruchs- und Performance-Problemen auf Blaser Synergy 735",
    description: "Practical-Machinist-Thread: Anwender hat Cimstar 60C-HFP wegen anhaltender Geruchsprobleme/'sucks' getestet und ist auf Blaser Synergy 735 gewechselt - mit deutlich besserem Ergebnis. Dokumentiert Marktbewegung weg von 60C-HFP fuer geruchsensitive Umgebungen.",
    symptoms: ["Strenger Geruch", "Mitarbeiter-Beschwerden", "Wechsel auf Wettbewerbsprodukt"],
    rootCause: "Vermutlich Wechselwirkung der HFP-Aerosol-Formulierung mit Sumpf-Tramp-Oil und Bakterien.",
    workaround: "Sumpf-Reinigung, Aeration; ggf. Wechsel auf bio-stabileres Produkt.",
    preventiveMeasure: "Vor Volldeployment Sample-Pail-Test in einer Maschine ueber 4-6 Wochen.",
    affectedMaterials: [],
    affectedOperations: ["High-Pressure Coolant"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/blaser-coolant-blasocut-2000-bc935sw.290221/page-2",
    sourceTitle: "Blaser Synergy 735 vs Cimstar 60C-HFP discussion",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Cimkleen 1707",
    manufacturerName: "Cimcool",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Industrielle Reiniger - typische Augen-/Hautreizungs-Warnung (allgemein)",
    description: "Cimkleen-Reiniger-Linie von Cimcool: industrielle alkalische Cleaner mit Tensiden zur Sumpf-Reinigung. Generelle SDS-Klassifikation alkalischer Industriereiniger: Skin Irritant Cat. 2, Eye Damage/Irritation Cat. 1 - Risiko fuer Veraetzung bei direktem Kontakt. Operatoren bei Sumpf-Service besonders gefaehrdet.",
    symptoms: ["Rote/brennende Haut", "Augenrotung", "Veraetzungen bei Spritzern"],
    rootCause: "Alkalische Cleaner mit pH > 11 und Tensiden.",
    workaround: "Sofortiges Spuelen mit Wasser; Arzt bei Augenkontakt.",
    preventiveMeasure: "Chemikalien-Schutzbrille, Handschuhe, Schuerze; Augendusche in Naehe der Sumpf-Station.",
    affectedMaterials: [],
    affectedOperations: ["Sump Cleaning"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.cimcool.com/home/products",
    sourceTitle: "Cimcool Cimkleen Cleaner Product Line",
    sourceAuthor: "Cimcool",
    sourceDate: null,
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hocut 795-H",
    manufacturerName: "Quaker Houghton",
    category: "RESIDUES",
    severity: "LOW",
    title: "Ultrasonic-Cleaning nach Hocut-Belag noetig",
    description: "Practical-Machinist-Thread 'Ultrasonic Cleaners' diskutiert Reinigung nach Hocut 795-Anwendung. Anwender berichten von hartnaeckigen Belaegen, die nur mit Ultraschall- oder dediziertem alkalischen Reiniger entfernbar sind, besonders an Werkstueck-Bohrungen und unter Spannfutter.",
    symptoms: ["Hartnaeckiger Coolant-Rueckstand", "Belag unter Spannfutter", "Klebrige Schicht in Sackloechern"],
    rootCause: "Emulgator-Rueckstaende und Bo-Salze trocknen zu festem Film ein.",
    workaround: "Ultraschall-Reiniger mit alkalischem Reiniger; Hocut-Spuelfluessigkeit.",
    preventiveMeasure: "Direkte DI-Spuelung nach Bearbeitung; Coolant-Konzentration im Soll halten.",
    affectedMaterials: [],
    affectedOperations: ["Cleaning", "Deburring"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/ultrasonic-cleaners.426903/",
    sourceTitle: "Ultrasonic Cleaners for Hocut residue",
    sourceAuthor: "Practical Machinist users",
    sourceDate: null,
    language: "EN",
    isOfficial: false
  }
];
