export default [
  {
    productName: "Ecocool R 2030",
    manufacturerName: "Fuchs",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Schaumbildung trotz Entschäumer bei längerer Maschinenlaufzeit",
    description: "Forenuser berichtet, dass Fuchs Ecocool R-HCM (verwandte Serie) trotz bereits enthaltenem Entschäumer nach längerer Maschinenlaufzeit zu schäumen beginnt. Begleitet von Verdacht auf pH-Drift und nachlassenden Korrosionsschutz.",
    symptoms: ["Schaumbildung", "Korrosionsschutz nachlassend", "Geruchsbildung"],
    rootCause: "Konzentrationsabfall und/oder Wassereintrag, mögliche bakterielle Belastung",
    workaround: "Konzentration messen und nachstellen, pH prüfen, Fremdöl entfernen",
    preventiveMeasure: "Regelmäßige Refraktometer- und pH-Kontrolle, Fremdölabschöpfung",
    affectedMaterials: [],
    affectedOperations: ["Fräsen", "Drehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://forum.zerspanungsbude.net/viewtopic.php?p=817089",
    sourceTitle: "Stinkendes und Schäumendes KSS - Zerspanungsbude",
    sourceAuthor: "Zerspanungsbude Forum-User",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Ecocool R 2030",
    manufacturerName: "Fuchs",
    category: "STABILITY",
    severity: "LOW",
    title: "Konzentrationsempfehlung 5-12% je nach Werkstoff",
    description: "Laut Produktdatenblatt sind je nach Werkstoff stark unterschiedliche Konzentrationen nötig: Stahl Zerspanen 5-8%, Aluminium Zerspanen bis 12%. Zu niedrige Konzentration führt zu unzureichendem Korrosions- und Bakterienschutz.",
    symptoms: ["Korrosion bei zu niedriger Konzentration", "Bakterienwachstum"],
    rootCause: "Unterdosierung gegenüber Werkstoffanforderung",
    workaround: "Konzentration werkstoffspezifisch anpassen",
    preventiveMeasure: "Refraktometerkontrolle, Mindestkonzentration 5%",
    affectedMaterials: ["Aluminium", "Stahl"],
    affectedOperations: ["Zerspanen", "Schleifen"],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://shop.schusterundsohn.de/wp-content/uploads/2023/01/PDB-Fuchs-Ecocool-R-2030.pdf",
    sourceTitle: "ECOCOOL R - 2030 Produktdatenblatt",
    sourceAuthor: "Fuchs Schmierstoffe GmbH",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Ecocool XEP",
    manufacturerName: "Fuchs",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Biologische Aktivität bei Maschinenstillstand und Tramp-Öl-Eintrag",
    description: "Laut Fuchs-Hinweisen erfordern wassermischbare ECOCOOL-Produkte besondere Aufmerksamkeit bei Produktionsstillstand. Tramp-Öle und andere Verunreinigungen führen zu erhöhter biologischer Aktivität und Geruchsbildung. Mindestkonzentration 3-4% wird empfohlen, ab Bakterien >10³ ist Biozid-Behandlung nötig.",
    symptoms: ["Geruchsbildung", "Bakterienwachstum >10³", "pH-Abfall"],
    rootCause: "Stillstand, Fremdöleintrag, Unterdosierung",
    workaround: "Renoclean SGC 62/72 mit 1-2% vor Abschaltung; Konzentration auf 4% erhöhen",
    preventiveMeasure: "Regelmäßige Bakterien- und pH-Kontrolle, Fremdölabscheidung, Belüftung bei Stillstand",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 4,
    reportedPh: 9,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/products/product-program/metal-processing-lubricants/water-miscible-coolants-tips/",
    sourceTitle: "Water-miscible Coolants - Tips | FUCHS LUBRICANTS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 705 B",
    manufacturerName: "Fuchs",
    category: "WORKPIECE_STAINS",
    severity: "MEDIUM",
    title: "Klarheits- und Schaumkontrolle bei Aluminium-Bearbeitung",
    description: "Ecocool 705 I (verwandter Aluminium-KSS) ist speziell für Anwendungen entwickelt, bei denen Klarheit und Schaumkontrolle kritisch sind - was indirekt belegt, dass Standard-KSS in der 700er Reihe hier Trübung und Schaum verursachen können.",
    symptoms: ["Trübung", "Schaum auf Aluminium-Anwendungen"],
    rootCause: "Standard-Formulierung nicht optimal für Aluminium-spezifische Klarheit",
    workaround: "Spezialprodukt 705 I für kritische Aluminium-Anwendungen",
    preventiveMeasure: "Aluminium-spezifische Variante wählen, Wasserqualität kontrollieren",
    affectedMaterials: ["Aluminium"],
    affectedOperations: ["Zerspanen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/brands/a-k/ecocool/",
    sourceTitle: "ECOCOOL | FUCHS LUBRICANTS CO. (United States)",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 6112 BF",
    manufacturerName: "Fuchs",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Aluminium-Verträglichkeit erfordert Vorabprüfung bei kritischen Legierungen",
    description: "Fuchs weist für die ECOCOOL MM BF Familie (boron-/biozidfreie Multifunktions-KSS) ausdrücklich darauf hin, dass mit kritischen Aluminium-Legierungen Verträglichkeitstests durchgeführt werden müssen, obwohl das Produkt grundsätzlich für gängige Aluminium-Legierungen geeignet ist.",
    symptoms: ["Verfärbungen", "Korrosion auf empfindlichen Aluminium-Legierungen"],
    rootCause: "Boron-/biozidfreie Formulierung weniger universell aluminiumverträglich",
    workaround: "Compatibility-Test vor Serienproduktion durchführen",
    preventiveMeasure: "Probelauf auf einzelnem Werkstück, Stainprüfung nach 24h",
    affectedMaterials: ["Aluminium kritische Legierungen"],
    affectedOperations: ["Fräsen", "Drehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/uk/en/product/product/19638-ECOCOOL-MM-BF/",
    sourceTitle: "ECOCOOL MM BF | Metal processing | FUCHS LUBRICANTS (UK) PLC",
    sourceAuthor: "Fuchs Lubricants UK",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 6112 BF",
    manufacturerName: "Fuchs",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "Hautirritation bei Ecocool-Serie ohne Schutzmaßnahmen",
    description: "Bediener in Forenposts berichten von rissiger, schmerzender Haut und Kopfschmerzen bei der Arbeit mit Fuchs Ecocool 711 (verwandte Serie), unabhängig vom Mischverhältnis. Ein Fuchs-Vertreter habe empfohlen, mit niedriger Konzentration zu starten und zu erhöhen.",
    symptoms: ["Rissige Fingerhaut", "Kopfschmerzen", "Hautreizung"],
    rootCause: "Inhaltsstoffe (Alkalität, Emulgatoren) auch im konformen Bereich potenziell hautreizend",
    workaround: "Niedrige Konzentration starten, schrittweise erhöhen, PSA verwenden",
    preventiveMeasure: "Schutzhandschuhe, regelmäßiges Reinigen, Hautschutzplan TRGS 401",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.yellowbullet.com/threads/cnc-machinits-coolant-question.462392/",
    sourceTitle: "CNC machinits coolant question | Yellow Bullet Forums",
    sourceAuthor: "Yellow Bullet Forum-User",
    sourceDate: "2018-06-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ecocool 6116 BF",
    manufacturerName: "Fuchs",
    category: "REGULATORY",
    severity: "LOW",
    title: "Boron-freie Formulierung als Antwort auf Reprotoxizitäts-Einstufung",
    description: "Die BF-Serie (Boron-Free) wurde von Fuchs entwickelt, nachdem Bor-Verbindungen wegen Reproduktionstoxizität reguliert wurden. Klassische bor-haltige KSS sind heute in vielen Anwendungen unerwünscht oder unzulässig.",
    symptoms: ["Regulatorische Einschränkung"],
    rootCause: "Bor-Verbindungen als reproduktionstoxisch eingestuft (CLP)",
    workaround: "Auf BF-Variante wechseln",
    preventiveMeasure: "SDB regelmäßig auf aktuelle Einstufungen prüfen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.cutwel.co.uk/205l-ecocool-mm-bf-semi-synthetic-water-miscible-multifunctional-cutting-fluid-coolant-suitable-for-cast-iron-and-aluminium-boron-biocide-chlorine-free-fuchs-fuchs-601384639",
    sourceTitle: "ECOCOOL MM BF (Cutwel) - Boron, Biocide & Chlorine Free",
    sourceAuthor: "Cutwel/Fuchs",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocut HSG 905 LE",
    manufacturerName: "Fuchs",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "Ölnebel und Verdampfung als Hauptthema bei HSG-Serie",
    description: "Fuchs selbst hebt für die ECOCUT HSG-Reihe (z.B. HSG 3032, 211 HD) Ölnebel und Verdampfungsverluste als zentrales Optimierungsthema hervor. Das impliziert, dass Standard-Schleiföle ohne Low-Misting-Additive bei Schleifen, Tieflochbohren und Räumen erhebliche Aerosolbelastung verursachen.",
    symptoms: ["Ölnebel", "Atemwegsbelastung", "Verdampfungsverluste"],
    rootCause: "Hohe Spindeldrehzahlen, niedrige Basisöl-Viskosität, fehlende Misting-Additive",
    workaround: "Low-Misting-Variante (HSG 211 HD/LE) einsetzen, Absaugung verbessern",
    preventiveMeasure: "Kapselung, Mistabsaugung mit Elektrofilter, Atemschutz",
    affectedMaterials: [],
    affectedOperations: ["Schleifen", "Tieflochbohren", "Verzahnungsschleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/mx/en/product/product/144711-ecocut-hsg-3032/",
    sourceTitle: "ECOCUT HSG 3032 | Metal processing | FUCHS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocut SCS 22",
    manufacturerName: "Fuchs",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Chlorfreie SD-22-Variante speziell für Yellow Metals empfohlen",
    description: "Fuchs Ecocut SD-22 (verwandte SCS/SD-Serie, 22cSt) ist explizit für 'yellow metals' und Aluminium geeignet, was darauf hinweist, dass aktive Schwefel- oder chlorhaltige Schneidöle Verfärbung an Buntmetallen verursachen können.",
    symptoms: ["Verfärbung an Messing/Kupfer durch aktive Additive"],
    rootCause: "Aktive Schwefel/Chlor-Additive reagieren mit Buntmetallen",
    workaround: "Chlorfreie SD-/SCS-Variante für Buntmetalle wählen",
    preventiveMeasure: "Werkstoff-Additive-Matrix prüfen, EP-Stufe nur wo nötig",
    affectedMaterials: ["Messing", "Kupfer", "Bronze", "Aluminium"],
    affectedOperations: ["Drehen", "Bohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://trucuttools.co.uk/fuchs-ecocut-sd-22-chlorine-free-neat-cutting-oil-205ltr/",
    sourceTitle: "Fuchs Ecocut SD-22 Chlorine Free Neat Cutting Oil",
    sourceAuthor: "TrucutTools",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ecocut Mikro 82",
    manufacturerName: "Fuchs",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "MMS-Schmierstoff verdampft - Wirkung stark anwendungsabhängig",
    description: "Ecocut Mikro Plus 82 ist ein Minimal-Mengen-Schmierstoff auf Fettalkoholbasis, der nahezu rückstandsfrei verdampft. Fuchs weist darauf hin, dass die Effektivität stark von Anwendung, Werkstück-Vorbehandlung und externer Verschmutzung abhängt - generelle Aussagen zur Funktion sind nicht möglich.",
    symptoms: ["Variable Kühlwirkung", "Unzureichende Schmierung bei falscher Applikation"],
    rootCause: "MMS-System sehr empfindlich für Düsenwinkel/Luftdruck/Dosierung",
    workaround: "Düse präzise auf Schneidkante richten, Dosierung experimentell ermitteln",
    preventiveMeasure: "Schulung der Bediener, regelmäßige Düsenkontrolle, Fuchs-App-Beratung",
    affectedMaterials: ["Aluminium", "Stahl", "Gusseisen"],
    affectedOperations: ["MMS-Bearbeitung", "Sägen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/de/de/produkt/product/147958-ECOCUT-MIKRO-PLUS-82/",
    sourceTitle: "ECOCUT MIKRO PLUS 82 | Metallbearbeitungsschmierstoffe | FUCHS",
    sourceAuthor: "Fuchs Schmierstoffe GmbH",
    sourceDate: "2024-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Renoform MZAN 51 N",
    manufacturerName: "Fuchs",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Chlorhaltiges Feinstanz-Öl erfordert alkalische Nachreinigung",
    description: "Renoform MZAN 51 H ist ein chlorhaltiges Hochleistungs-Öl für Feinschneiden und Tiefziehen. Rückstände auf Werkstücken müssen mit alkalischen Reinigern oder Lösemitteln entfernt werden - andernfalls Korrosion und Beschichtungsprobleme.",
    symptoms: ["Klebrige Rückstände auf Werkstück", "Probleme bei nachfolgender Beschichtung"],
    rootCause: "Chlorparaffin-Additive sind viskos und haften stark",
    workaround: "Alkalische Reinigung (Bonderite C-AK, Renoclean SMC) oder Lösemittel",
    preventiveMeasure: "Reinigungsschritt vor Beschichten/Lagern fest einplanen",
    affectedMaterials: ["Stahl", "Hochlegierte Werkstoffe"],
    affectedOperations: ["Feinstanzen", "Tiefziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.hazmioil.cz/PI/2006/ptc_PI2-7288.pdf",
    sourceTitle: "Renoform MZAN 51 Produktinformation",
    sourceAuthor: "Fuchs",
    sourceDate: "2006-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Renoform MZAN 60",
    manufacturerName: "Fuchs",
    category: "REGULATORY",
    severity: "HIGH",
    title: "Chlorparaffin-Risiko bei MZAN-Familie - SCCP sind SVHC unter REACH",
    description: "Renoform MZAN/OS-Serie enthält in mehreren Varianten 'very long chain chlorinated paraffins'. Kurzkettige (SCCP) sind als SVHC unter REACH eingestuft; auch mittelkettige (MCCP) stehen unter Beobachtung. Anwender müssen genau prüfen, welche Kettenlänge im jeweiligen Renoform-Produkt enthalten ist.",
    symptoms: ["Regulatorisches Risiko", "Erschwerte Entsorgung"],
    rootCause: "Chlorparaffin-Klassen werden zunehmend reguliert",
    workaround: "VLCCP-Variante prüfen, sukzessive auf chlorfreie Renoform-Alternativen umstellen",
    preventiveMeasure: "SDB-Updates verfolgen, Lieferantenbestätigung zu SCCP/MCCP einholen",
    affectedMaterials: [],
    affectedOperations: ["Feinstanzen", "Tiefziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/product/product/119542-renoform-os-2808/",
    sourceTitle: "RENOFORM OS 2808 | Metal processing | FUCHS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Renoform HBL",
    manufacturerName: "Fuchs",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Hochviskose Umformschmierstoffe erfordern definierten Reinigungsprozess",
    description: "Verwandte HBO-Produkte (Renoform HBO 859/4, HBO 2222 HV) der Renoform-Familie für Tiefziehen, Feinstanzen und Stanzen sind hochviskose Prozessmedien, die ohne nachfolgende Reinigung Rückstände auf den Werkstücken hinterlassen.",
    symptoms: ["Filmrückstand", "Verschmutzung der nachgelagerten Schweiß/Klebprozesse"],
    rootCause: "Hohe Grundölviskosität, hohe Additivlast für extreme Umformkräfte",
    workaround: "Definierten Wasch-/Entfettungsschritt einplanen",
    preventiveMeasure: "Renoclean-System integrieren; Auftragsmenge optimieren",
    affectedMaterials: ["Stahl", "Edelstahl"],
    affectedOperations: ["Tiefziehen", "Feinstanzen", "Streckziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://oelluxx24.de/industrieoel/umformschmierstoffe/renoform-hbo-2222-hv",
    sourceTitle: "Renoform HBO 2222 HV 205L Fass | oelluxx24",
    sourceAuthor: "oelluxx24",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Renocool 6116 BF",
    manufacturerName: "Fuchs",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Biozidfreie Formulierungen brauchen striktes Konzentrations- und Pflegeregime",
    description: "Fuchs empfiehlt für die biozid- und borfreien Renocool/Ecocool-Serien explizit Mindestkonzentration 3-4% und kontinuierliche Bakterienkontrolle. Bei Bakterien >10³ ist Biozid-Behandlung (Renoclean SGC 62/72) trotz BF-Bezeichnung notwendig.",
    symptoms: ["Bakterienanstieg ohne Biozidbasis", "Geruchsbildung am Wochenende"],
    rootCause: "Fehlende eingebaute Biozide; Empfindlichkeit für Stillstand und Fremdöl",
    workaround: "Wochenend-Belüftung, Fremdölskimmer, Renoclean SGC 1-2% vor Abschaltung",
    preventiveMeasure: "Wöchentliche Bakterien-Dipslides, Refraktometer, Fremdölbilanz",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 4,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/products/product-program/metal-processing-lubricants/water-miscible-coolants-tips/",
    sourceTitle: "Water-miscible Coolants - Tips | FUCHS LUBRICANTS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Renocool S 51",
    manufacturerName: "Fuchs",
    category: "STABILITY",
    severity: "LOW",
    title: "pH-Bereich 8,8-9,2 muss eingehalten werden",
    description: "Fuchs gibt für die Renocool/Ecocool-Familie einen pH-Bereich von 8,8-9,2 vor (pH-neutrale Synthetics wie ECOCOOL SYN 2175 separat bei 7,0-8,0). Bei pH-Abfall: Korrekturmaßnahme mit 'pH Conditioner #4'.",
    symptoms: ["pH-Drift unter 8,8", "Geruchsbildung", "Korrosionsrisiko"],
    rootCause: "Bakterieller Säureabbau, Fremdöl-Eintrag, Wassereindampfung",
    workaround: "pH Conditioner #4 dosieren, Bakterienlevel prüfen",
    preventiveMeasure: "Wöchentliche pH-Messung, Frischwasser deion qualität",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: 9,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/products/product-program/metal-processing-lubricants/water-miscible-coolants-tips/",
    sourceTitle: "Water-miscible Coolants - Tips | FUCHS LUBRICANTS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite C-MC 1100",
    manufacturerName: "Henkel",
    category: "RESIDUES",
    severity: "LOW",
    title: "Trocknungstemperatur 50-55°C zur Rückstandsentfernung erforderlich",
    description: "Henkel gibt für vergleichbare Bonderite C-MC Reiniger an, dass Rückstände 'in einem Strom warmer Luft oder in einem belüfteten Trockenofen bei 50 bis 55°C' entfernt werden. Ohne diesen Trocknungsschritt verbleiben Reiniger-Reste auf der Oberfläche.",
    symptoms: ["Wasserflecken", "Reinigerrückstände", "Probleme bei Folge-Lackierung"],
    rootCause: "Nasse Bauteile mit Reiniger-Resten trocknen ohne Wärme schlecht ab",
    workaround: "Aktive Trocknung 50-55°C, Druckluft-Abblasen",
    preventiveMeasure: "Reinigungslinie immer mit Heißluft-Trockenzone planen",
    affectedMaterials: ["Stahl", "Buntmetall"],
    affectedOperations: ["Industriereinigung", "Vorbehandlung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.gluespec.com/Materials/SpecSheet/8d4d3fe1-e755-4b41-9a7a-060a09837328",
    sourceTitle: "Technical Data Sheet BONDERITE C-MC 1000 (LIXTON 1000 NEU)",
    sourceAuthor: "Henkel",
    sourceDate: "2020-04-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite L-MR 21420",
    manufacturerName: "Henkel",
    category: "REGULATORY",
    severity: "LOW",
    title: "Bor-, Chlor-, S-, P-freie Formulierung als Antwort auf Reprotox-Bedenken",
    description: "Henkel positioniert seine bor-freien Bonderite-L-MR-Reihe (z.B. 21895, 21165) explizit gegen die Bor-Reprotoxizitäts-Einstufung. Anwender älterer borhaltiger Multan/Bonderite-Varianten müssen migrieren, wenn nationale/CLP-Regeln das verlangen.",
    symptoms: ["Regulatorische Anforderung zur Substitution"],
    rootCause: "Bor-Verbindungen als reproduktionstoxisch (CMR) eingestuft",
    workaround: "Auf bor-freie L-MR 214xx-Reihe wechseln",
    preventiveMeasure: "Lieferanten-Roadmap bor-frei anfordern, Substitutionsprüfung dokumentieren",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.henkel.com/press-and-media/press-releases-and-kits/2022-07-27-henkel-s-boron-free-bonderite-range-the-ideal-combination-of-cost-savings-sustainability-and-performance-for-metalworking-1710950",
    sourceTitle: "Henkel's boron-free Bonderite range",
    sourceAuthor: "Henkel Press",
    sourceDate: "2022-07-27",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite C-AK 4181",
    manufacturerName: "Henkel",
    category: "WORKPIECE_STAINS",
    severity: "MEDIUM",
    title: "Übertemperatur und Überdosierung verursachen Anlauffarbe/Verfärbung an Messing",
    description: "Henkel weist im TDB explizit darauf hin: 'Zu hohe Konzentration, Temperatur oder Zeit kann zu Anlauf-/Verfärbung an Messing führen' (übertragen aus C-AK ALTREX 24 AERO). Anwender müssen Konzentration und Badtemperatur strikt im Sollbereich halten.",
    symptoms: ["Anlauffarbe auf Messing", "Hautreizung bei Spritzer"],
    rootCause: "Übermäßige Alkalität greift Buntmetall an",
    workaround: "Konzentration reduzieren, Tauchzeit verkürzen, Temperatur senken",
    preventiveMeasure: "Titration mindestens wöchentlich, Temperaturlogger am Bad",
    affectedMaterials: ["Messing", "Buntmetalle"],
    affectedOperations: ["Tauchreinigung", "Spritzreinigung"],
    reportedConcentration: null,
    reportedPh: 12,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.conro.com/downloads/Manuals/Bonderite-C-AK-Altrex-24-AERO-Alkaline-Cleaner-TDS.pdf",
    sourceTitle: "Technical Process Bulletin BONDERITE C-AK ALTREX 24 AERO",
    sourceAuthor: "Henkel/Conro",
    sourceDate: "2018-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite C-IC 1140-1",
    manufacturerName: "Henkel",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Saure Reiniger der C-IC-Familie sind hautätzend",
    description: "Henkel C-IC-Familie (saure Industriereiniger zur Entfernung von Oxidschichten/Walzzunder) ist säurebasiert und kann bei Hautkontakt schwere Verätzungen verursachen. Vergleichbare Produkte (C-IC 18010, C-IC Smutgo) tragen entsprechende GHS-Kennzeichen.",
    symptoms: ["Hautverätzung", "Augenverätzung", "Atemwegsreizung durch Säurenebel"],
    rootCause: "Niedriger pH (<2) zur Effektivität gegen Eisenoxid",
    workaround: "Säurefeste PSA (Handschuhe, Schürze, Schutzbrille, Gesichtsschutz)",
    preventiveMeasure: "Geschlossene Anlagen, Absaugung, Notduschen am Arbeitsplatz",
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Beizen", "Entzunderung"],
    reportedConcentration: null,
    reportedPh: 2,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://next.henkel-adhesives.com/cz/en/products/industrial-sealants/central-pdp.html/bonderite-c-ic-18010-paste/SAP_IB-121802.html",
    sourceTitle: "BONDERITE C-IC 18010 PASTE | Henkel Adhesives",
    sourceAuthor: "Henkel Adhesives",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite L-FM 5180",
    manufacturerName: "Henkel",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Forming-Lubricants hinterlassen filmartige Rückstände",
    description: "Verwandte Bonderite L-FM-Produkte (L-FM 234, L-FM 2004, L-FM PRETREAT AERO) sind als trockene oder feuchte Schmierfilme konzipiert, die explizit als Pre-Treatment-Schicht auf dem Bauteil verbleiben. Vor Lackierung/Schweißung ist daher zwingend Reinigung nötig.",
    symptoms: ["Lack-Haftungsprobleme", "Schweißporen", "Klebprozess-Versagen"],
    rootCause: "Bewusster Schmierfilm soll im Umformprozess verbleiben",
    workaround: "Alkalische Reinigung (Bonderite C-AK) zwischen Umform- und Folgeschritt",
    preventiveMeasure: "Prozesskette mit Reinigungsstufe definieren",
    affectedMaterials: ["Stahlblech", "Aluminiumblech"],
    affectedOperations: ["Tiefziehen", "Streckziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://webaps.ellsworth.com/edl/Actions/GetLibraryFile.aspx?document=12319&language=en",
    sourceTitle: "Technical Process Bulletin BONDERITE L-FM PRETREAT AERO LUBRICANT FORMING",
    sourceAuthor: "Henkel",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Bonderite C-NE 5258",
    manufacturerName: "Henkel",
    category: "FOAM",
    severity: "LOW",
    title: "Neutralreiniger der C-NE-Familie auch bei KSS-Kontamination schaumarm",
    description: "Henkel hebt für BONDERITE C-NE 5088 explizit hervor: 'auch bei starker KSS-Kontamination treten keine Schaumprobleme auf' - was indirekt zeigt, dass viele Neutralreiniger sehr wohl unter KSS-Eintrag stark schäumen.",
    symptoms: ["Schaumbildung bei Reinigern mit KSS-Belastung"],
    rootCause: "Eingeschleppte Tenside aus dem KSS schäumen im Reinigerbad",
    workaround: "Auf C-NE 5088-Variante mit defoamerstabiler Tensid-Mischung wechseln",
    preventiveMeasure: "Bauteile zwischen KSS-Prozess und Reinigung gut abtropfen lassen",
    affectedMaterials: [],
    affectedOperations: ["Spritzreinigung", "Tauchreinigung"],
    reportedConcentration: null,
    reportedPh: 7,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.henkel-adhesives.com/my/en/product/metal-process-cleaners/bonderite_c-ne_50880.html",
    sourceTitle: "BONDERITE C-NE 5088 - Industrial cleaner",
    sourceAuthor: "Henkel Adhesives",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Multan 100",
    manufacturerName: "Henkel",
    category: "BIOLOGY",
    severity: "HIGH",
    title: "Klassische Multan-Emulsionen: jährlicher Komplettwechsel wegen Bakterien-Split",
    description: "Walter AG-Fallstudie: 'Starke Geruchsentwicklung bei längeren Maschinenausfallzeiten' mit Multan 71-2 (verwandte Multan-Familie). Emulsionen zerfielen bakteriell, jährlicher kompletter Tausch nötig. Lösung war Wechsel auf bactericidfreie patentierte Emulgatortechnologie.",
    symptoms: ["Penetranter Geruch nach Stillstand", "Emulsions-Split", "pH-Abfall"],
    rootCause: "Bakterienwachstum besonders in Stillstandszeiten",
    workaround: "Wechsel auf bactericidfreie Multan-/Bonderite-L-MR-Variante",
    preventiveMeasure: "Mindestkonz. 5% initial / 0,5% nachfüllen, regelmäßige Bakterienprüfung",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://pwemag.co.uk/news/fullstory.php/aid/828/Cutting_fluid_problem_solved.html",
    sourceTitle: "Cutting fluid problem solved - Plant & Works Engineering",
    sourceAuthor: "PWE Magazine",
    sourceDate: "2013-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Multan 65-3 RD",
    manufacturerName: "Henkel",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Formaldehyd-Depotbiozide als Hauptgrund für Hautsensibilisierung",
    description: "Henkel selbst beschreibt, dass klassische Multan-/Bonderite-KSS mit bactericiden Zusätzen (insb. Formaldehyd-Depotbiozide) Hautirritationen und Sensibilisierungen auslösen können. Daher wurde die bactericidfreie Multan-Plattform entwickelt.",
    symptoms: ["Hautirritation", "Sensibilisierung mit zunehmender Expositionsdauer"],
    rootCause: "Formaldehyd-Splitter und Biozide reagieren mit Hautproteinen",
    workaround: "Wechsel auf bactericidfreie Multan/Bonderite L-MR Variante",
    preventiveMeasure: "Hautschutzplan TRGS 401, Handschuhe, Pre-Work-Cream",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.mta.org.uk/whats-new/members-news/bactericide-free-cutting-fluid-henkel-stays-bacteria-free",
    sourceTitle: "Bactericide-free cutting fluid from Henkel, stays bacteria free | MTA",
    sourceAuthor: "Manufacturing Technologies Association (Henkel-Quelle)",
    sourceDate: "2018-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Multan 100",
    manufacturerName: "Henkel",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Tramp-Öl-Eintrag schwächt klassische Emulsionsstabilität",
    description: "Henkel adressiert in der Multan-Reihe explizit Tramp-Öl-Rejection: klassische Emulsionen werden durch Maschinen-Hydraulik- oder Wegeöl-Einträge geschwächt, splitten und müssen häufiger gewechselt werden.",
    symptoms: ["Emulsionsbruch", "Filterverstopfung", "Geruch"],
    rootCause: "Tramp-Öl bindet Emulgatoren, destabilisiert Mizellen",
    workaround: "Skimmer/Bandskimmer installieren, regelmäßige Reinigung",
    preventiveMeasure: "Spalt-Dichtungen prüfen, Hydraulikleckage abstellen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.chempoint.com/products/henkel/bonderite-lubricants/bonderite-metal-removal-lubricants/bonderite-l-mr-9103",
    sourceTitle: "BONDERITE L-MR 9103 (formerly MULTAN 9103) - ChemPoint",
    sourceAuthor: "ChemPoint/Henkel",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Petroform NCS 5",
    manufacturerName: "Petrofer",
    category: "RESIDUES",
    severity: "LOW",
    title: "Stanzöl-Familie soll rückstandsfrei verdampfen - in der Praxis bleiben Filme",
    description: "Petrofer wirbt für die Stanzöl-Range mit 'verdampft rückstandsfrei'. In der Praxis bleibt jedoch häufig ein dünner Film, der bei nachfolgendem Punkt- oder Laserschweißen Probleme verursachen kann.",
    symptoms: ["Schweißspritzer", "Lackhaftungs-Probleme"],
    rootCause: "Rückstand bei zu hoher Auftragsmenge oder unvollständiger Trocknung",
    workaround: "Auftragsmenge reduzieren (MMS-Walze), Trocknungszone integrieren",
    preventiveMeasure: "Walzenauftrag statt Sprühen, Vorabreinigung bei kritischen Folgeprozessen",
    affectedMaterials: ["Stahlblech"],
    affectedOperations: ["Stanzen", "Folgeverbund-Werkzeug"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://petrofer.com/wp-content/uploads/2024/01/Pamphlet_05_metal-forming-lubricants_EN_062019_LoRes.pdf",
    sourceTitle: "Metal Forming Lubricants (Pamphlet) - PETROFER",
    sourceAuthor: "Petrofer Chemie",
    sourceDate: "2019-06-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Isocut Sol M",
    manufacturerName: "Petrofer",
    category: "STABILITY",
    severity: "LOW",
    title: "Wasserqualität entscheidend für Emulsionsstabilität",
    description: "Petrofer Datenblätter weisen darauf hin, dass die Wasserqualität (Härte, Salzgehalt) entscheidend für die Emulsionsstabilität der Isocut-Sol-Familie ist. Zu hartes Wasser zerstört die Emulsion durch Ausfällung der Emulgatoren ('scum formation').",
    symptoms: ["Kalkseifen-Niederschlag", "Filterverstopfung", "Schmierfilmverlust"],
    rootCause: "Ca/Mg-Ionen fällen anionische Emulgatoren aus",
    workaround: "Auf weiches Wasser (Härte <15°dH) umstellen, ggf. Ionenaustauscher",
    preventiveMeasure: "Wasserhärte vor Erstansatz und beim Nachfüllen messen",
    affectedMaterials: [],
    affectedOperations: ["Zerspanen", "Schleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.petrofer.com/en/product-range/metal-cutting-fluids/",
    sourceTitle: "Metal Cutting Fluids - PETROFER",
    sourceAuthor: "Petrofer",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Isocut Sol K",
    manufacturerName: "Petrofer",
    category: "FOAM",
    severity: "LOW",
    title: "Schaumbildung bei sehr weichem oder vollentsalztem Wasser",
    description: "Allgemein bekannte Problematik (auch Petrofer-relevant): Sehr weiches oder demineralisiertes Wasser führt zu niedriger Oberflächenspannung der Emulsion und damit zu instabilem Schaum. Tritt besonders bei frisch angesetzten Bädern auf.",
    symptoms: ["Großblasiger Schaum", "Überlauf am Tank"],
    rootCause: "Zu niedrige Oberflächenspannung durch fehlende Mineralisierung",
    workaround: "Konditionierwasser auf 5-15°dH einstellen, Entschäumer dosieren",
    preventiveMeasure: "Frischwasser nicht vollentsalzt, sondern teilenthärtet einsetzen",
    affectedMaterials: [],
    affectedOperations: ["Zerspanen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://will-fill.com/de/kss-K%C3%BChlschmierstoff-Schaum-Probleme",
    sourceTitle: "Kühlschmierstoff Schaum Probleme - Will-Fill",
    sourceAuthor: "Will-Fill",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Isocool 6 GR",
    manufacturerName: "Petrofer",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Wasser zu alkalisch fuehrt zu weissem Belag an Schleifmaschine",
    description: "Bei Grinding-Coolants wie Isocool weist die Branchenliteratur (allgemein gueltig fuer mineraloelfreie Schleifloesungen) darauf hin, dass zu alkalisches Prozesswasser zu weissem Belag (Kalkseifen) an der Maschine fuehrt und zu saures Wasser stahlbasierte Werkzeuge/Rollen rosten laesst.",
    symptoms: ["Weisser Belag", "Rost an Rollen", "Filterzusetzung"],
    rootCause: "pH-Drift des Prozesswassers",
    workaround: "pH und Wasserhaerte pruefen und einstellen",
    preventiveMeasure: "Wasseraufbereitung, Soll-pH 8,5-9,2",
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Schleifen", "Rollschleifen"],
    reportedConcentration: null,
    reportedPh: 9,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.nortonabrasives.com/en-us/resources/expertise/critical-coolant-factors-roll-grinding",
    sourceTitle: "Critical Coolant Factors in Roll Grinding | Norton Abrasives",
    sourceAuthor: "Norton Abrasives",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Isofloc D 1000",
    manufacturerName: "Petrofer",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Dielektrika mit aromatischen Anteilen sind arbeitshygienisch problematisch",
    description: "EDM-Dielektrika der Isofloc-Klasse (sowie deren Wettbewerber) sind laut Patentliteratur entweder mit hoher Aromatenkonzentration belastet (arbeitsschutzrelevant) oder zeigen reduzierte Erosionsleistung. Anwender müssen je nach Variante Atemschutz und Absaugung sicherstellen.",
    symptoms: ["Aromatische Dämpfe", "Geruchsbelastung", "Hautkontakt-Risiko"],
    rootCause: "Mineralöl-Basis mit aromatischen Anteilen, niedriger Flammpunkt",
    workaround: "Hydrierte / dearomatisierte Variante (Petrofer Isofloc D 1000 LE etc.)",
    preventiveMeasure: "Maschinenkapselung, Absaugung, Hautschutz, Brandschutz",
    affectedMaterials: [],
    affectedOperations: ["Senkerosion", "Drahterosion"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/6048474",
    sourceTitle: "Dielectric fluid for the machining of metal by means of spark erosion (Patent)",
    sourceAuthor: "USPTO Patentliteratur",
    sourceDate: "2000-04-11",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Isofloc P 60",
    manufacturerName: "Petrofer",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "EDM-Dielektrika: Brand- und Explosionsschutz strikt einhalten",
    description: "EDM-Dielektrika können bei zu hohen Temperaturen entzünden. Die elektrischen Funken erzeugen lokal sehr hohe Temperaturen, was bei mangelnder Bad-Überdeckung oder Flammpunkt-Unterschreitung zum Brand führen kann.",
    symptoms: ["Brand im Arbeitsraum", "Verkohlung"],
    rootCause: "Funken in Kontakt mit zu wenig Dielektrikum oder zu niedrigem Flammpunkt",
    workaround: "Bad-Füllstand-Wächter, automatische Löschung",
    preventiveMeasure: "Flammpunkt >100°C wählen, Bad-Überdeckung der Elektrode >40mm",
    affectedMaterials: [],
    affectedOperations: ["Senkerosion"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "OTHER",
    sourceUrl: "https://www.cyskmc.com/EDM-Spark-Erosion-Machine-Safety-Electrostatic-and-Fire-Prevention",
    sourceTitle: "EDM Spark Erosion Machine Safety: Electrostatic and Fire Prevention",
    sourceAuthor: "CYSKMC",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Isodraw OL 75",
    manufacturerName: "Petrofer",
    category: "RESIDUES",
    severity: "LOW",
    title: "Drahtzieh-Öle hinterlassen Film, Reinigungsschritt zwingend",
    description: "Petrofer Stanz-/Zieh-Öle der Isodraw-Familie sind als persistente Schmierfilme konzipiert. Vor Galvanik, Lackierung oder Schweißung ist eine alkalische oder lösemittelbasierte Reinigung notwendig.",
    symptoms: ["Beschichtungsfehler", "Anhaftungen"],
    rootCause: "Bewusster Hochleistungs-Schmierfilm im Drahtziehprozess",
    workaround: "Alkalische Reinigung vor Folgeprozess",
    preventiveMeasure: "Reinigungs-Stufe in Prozesskette einplanen",
    affectedMaterials: ["Stahldraht", "Edelstahldraht"],
    affectedOperations: ["Drahtziehen", "Rohrziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://petrofer.com/products/metal-forming-lubricants/",
    sourceTitle: "Metal Forming Lubricants - PETROFER",
    sourceAuthor: "Petrofer",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ultracut Evo 250",
    manufacturerName: "ROCOL",
    category: "PERFORMANCE",
    severity: "MEDIUM",
    title: "60:1 Verduennung Herstellerangabe in Praxis nur fuer Schleifen tauglich",
    description: "Practical-Machinist-Forenuser berichten, dass ROCOL-Vertreter eine Verduennung 60:1 fuer allgemeines Zerspanen empfahlen, jedoch: 'rusting was a nightmare and the so called 60:1 was for grinding, its more akin to the usual 5% for a conventional cutting process if you dont want rapid tool wear and flash rusting'. Hinweis: Forum bezieht sich auf Ultracut Clear/Plus, ROCOL bestaetigt jedoch dass EVO-Variante das Rost-Problem nicht hat.",
    symptoms: ["Rost auf Werkstuecken", "Schneller Werkzeugverschleiss", "Flash-Rost"],
    rootCause: "Zu hohe Verduennung fuer Drehen/Fraesen-Bedingungen",
    workaround: "20:1 bis 40:1 je nach Werkstoff und Schaerfegrad (laut ROCOL-Datenblatt)",
    preventiveMeasure: "Refraktometer-Kontrolle, Vendoremfehlung mit Werkstuck-Erprobung verifizieren",
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Drehen", "Fraesen", "Schleifen"],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/rocol-ultracut-clear-any-good.308891/",
    sourceTitle: "Rocol Ultracut clear ! Any good??? | Practical Machinist",
    sourceAuthor: "Practical Machinist Forum-User",
    sourceDate: "2017-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ultracut Clear 1",
    manufacturerName: "ROCOL",
    category: "CORROSION",
    severity: "HIGH",
    title: "Rost und Flash-Rust bei werksempfohlener Verduennung",
    description: "Practical-Machinist-User berichten explizit fuer ROCOL Ultracut Clear/Plus: 'rusting was a fucking nightmare' bei der Herstellervorgabe 60:1. ROCOL-Vertreter bestaetigte intern dass diese Verduennung fuer Schleifen gedacht ist. Praxisbedarf fuer Drehen/Fraesen liegt bei ca. 5% (20:1).",
    symptoms: ["Rost auf bearbeiteten Flaechen", "Flash-Rust ueber Nacht"],
    rootCause: "Zu duenne Emulsion -> unzureichender Korrosionsschutz",
    workaround: "Konzentration auf 5% (20:1) anheben",
    preventiveMeasure: "Refraktometer, Konzentrationsempfehlung des Herstellers nicht ungeprueft uebernehmen",
    affectedMaterials: ["Stahl", "Gusseisen"],
    affectedOperations: ["Drehen", "Fraesen"],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/rocol-ultracut-clear-any-good.308891/",
    sourceTitle: "Rocol Ultracut clear ! Any good??? | Practical Machinist",
    sourceAuthor: "Practical Machinist Forum-User",
    sourceDate: "2017-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ultracut Evo 250",
    manufacturerName: "ROCOL",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "EVO-Reihe gezielt ohne Biozide/Hautsensibilisatoren entwickelt",
    description: "ROCOL ULTRACUT EVO Familie ist laut Hersteller frei von Bioziden und Hautsensibilisatoren - explizit als Antwort auf wiederkehrende Hautirritations-Beschwerden bei klassischen Ultracut-Varianten (mit Bioziden, z.B. Ultracut Longlife mit Skin Irritation H-Statement im SDS).",
    symptoms: ["Hautreizung bei Vorgaengerprodukten"],
    rootCause: "Biozide und Konservierungsmittel in klassischen Wassermischbaren",
    workaround: "Wechsel auf EVO-Reihe (255/280)",
    preventiveMeasure: "SDB pruefen auf Skin-Sens H317 / Skin-Irr H315",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rocol.com/products/ultracut-evo-250",
    sourceTitle: "Long life, operator friendly, water soluble cutting fluid - ULTRACUT EVO 250",
    sourceAuthor: "ROCOL",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ultracut Edm 1",
    manufacturerName: "ROCOL",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Reduzierter Verbrauch nur bei korrekter Top-Up-Verduennung",
    description: "ROCOL Case Study (Ultracut EVO 255): durch korrekte Top-Up-Verduennung (40:1 statt 19:1) konnte Verbrauch von 41.000 L/Jahr auf 20.048 L/Jahr fast halbiert werden - das setzt jedoch Refraktometer-Disziplin voraus, andernfalls leidet entweder Bearbeitungsleistung oder Verbrauch.",
    symptoms: ["Ueberhoehter Verbrauch durch falsche Nachdosierung"],
    rootCause: "Bediener fuellt mit Konzentrat statt Top-Up-Verduennung nach",
    workaround: "Automatische Mischdosieranlage, Top-Up bei 1-2% statt 5%",
    preventiveMeasure: "Schulung Bediener, Refraktometer am Tank",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 2,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://www.amedm.co.uk/reducing-the-cost-of-our-metal-cutting-coolant-while-maintaining-high-quality-machining-by-working-with-msc-and-rocol/",
    sourceTitle: "Reducing the cost of our metal cutting coolant ... with MSC and Rocol - A&M",
    sourceAuthor: "A&M EDM",
    sourceDate: "2021-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ultraclean Bio",
    manufacturerName: "ROCOL",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Alkalischer Reiniger verursacht schwere Haut- und Augenveraetzung",
    description: "ROCOL Ultraclean 2000 (Cousin-Produkt der Bio-Variante, gleicher Tensid-Aufbau) ist GHS-Kategorie 1A: 'causes severe skin burns and eye damage'. Trotz 'water-based' und 'biologisch abbaubar' ist umfassende PSA Pflicht.",
    symptoms: ["Hautveraetzung", "Augenveraetzung"],
    rootCause: "Hochalkalische Tensidmischung (pH >12)",
    workaround: "Kein direkter Hautkontakt, geschlossenes System",
    preventiveMeasure: "Schutzhandschuhe (Nitril), Schutzbrille, Schuerze, Augendusche",
    affectedMaterials: [],
    affectedOperations: ["Industriereinigung"],
    reportedConcentration: null,
    reportedPh: 12,
    sourceType: "SDS",
    sourceUrl: "https://www.rocol.com/datasheets/download/clp/6/ULTRACLEAN%202000",
    sourceTitle: "ULTRACLEAN 2000 Safety Data Sheet",
    sourceAuthor: "ROCOL",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool R 2030",
    manufacturerName: "Fuchs",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Hartes oder salzhaltiges Wasser foerdert Korrosion durch Salzanreicherung",
    description: "Allgemeine KSS-Problematik mit direkter Relevanz fuer Ecocool R 2030 (bestaetigt durch Will-Fill und Jokisch): 'Salzansammlung in der Emulsion durch Anreicherung von Salzen aus dem Wasser oder aus Metallspaenen; hohe Salzkonzentration kann Emulsionsstabilitaet negativ beeinflussen und zu Korrosion fuehren'.",
    symptoms: ["Flugrost auf Werkstuecken", "Salzkrusten am Tankrand"],
    rootCause: "Wasserhärte und Bearbeitungsabrieb reichern Cl-/SO4- an",
    workaround: "Teilweise Frischwasser-Zugabe, Tank-Wechsel bei hoher Leitfaehigkeit",
    preventiveMeasure: "Leitfaehigkeit < 5000 µS/cm, Frischwasserqualitaet ueberwachen",
    affectedMaterials: ["Stahl", "Gusseisen"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://will-fill.com/de/kss-K%C3%BChlschmierstoff-Korrosionsprobleme",
    sourceTitle: "Kühlschmierstoff Korrosionsprobleme - Will-Fill",
    sourceAuthor: "Will-Fill",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Bonderite L-MR 21420",
    manufacturerName: "Henkel",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Bactericid-freie Formulierung erfordert konsequente Pflege",
    description: "Henkels bactericid-freie Bonderite-L-MR-Familie (21420/21895/21165) setzt auf patentierte Emulgatortechnologie. Damit das ohne Bakterien-Eskalation funktioniert, sind Mindest-Konzentration, regelmaessige pH-Kontrolle und Tramp-Oil-Skimming essentiell.",
    symptoms: ["Bakterienanstieg ohne Biozid-Basis", "pH-Drift"],
    rootCause: "Kein eingebautes Biozid, daher empfindlich fuer Wasseruebertrag und Fremdoel",
    workaround: "Refraktometer-/pH-Disziplin, Tramp-Oil-Skimmer",
    preventiveMeasure: "5% Initial / 0,5% Top-up; Dipslides woechentlich",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: 9,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.henkel-adhesives.com/eg/en/industries/metals/metal-machining-and-forming/machining-and-grinding/bonderite-l-mr-bactericide-free-cutting-fluids.html",
    sourceTitle: "BONDERITE L-MR Bactericide-free Cutting Fluids - Henkel",
    sourceAuthor: "Henkel Adhesives",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Multan 100",
    manufacturerName: "Henkel",
    category: "FOAM",
    severity: "LOW",
    title: "Patentierte Emulgator-Technologie verhindert Schaum auch bei Demin-Wasser",
    description: "Henkel beschreibt im Multan-71-2-Case (Walter AG): 'keine Schaumbildung, auch mit destilliertem Wasser' - das ist eine bewusste Antwort auf die typische Schwaeche aelterer Multan/Bonderite-Emulsionen, die bei vollentsalztem Wasser stark schaeumten.",
    symptoms: ["Schaum bei Demin-Wasser (Vorgaengerprodukte)"],
    rootCause: "Niedrige Oberflaechenspannung bei vollentsalztem Wasser",
    workaround: "Wechsel auf Multan 71-2 / Bonderite L-MR 21XXX",
    preventiveMeasure: "Bei Verbleib auf Altprodukt: Teilenthaertung des Frischwassers",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://pwemag.co.uk/news/fullstory.php/aid/828/Cutting_fluid_problem_solved.html",
    sourceTitle: "Cutting fluid problem solved - Plant & Works Engineering",
    sourceAuthor: "PWE Magazine / Walter AG",
    sourceDate: "2013-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Ultracut Evo 250",
    manufacturerName: "ROCOL",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Lebensdauer-Optimierung erfordert Vorab-Maschinenreinigung",
    description: "ROCOL betont im Datenblatt: 'optimum fluid life is obtained by adequate initial machine cleaning, correct dilution control and regular maintenance of the fluid, particularly prior to weekends and shutdown periods.' Wer ungereinigte Tanks nutzt, hat verkuerzte Standzeit.",
    symptoms: ["Verkuerzte Standzeit", "Bakterienkontamination aus Altbelag"],
    rootCause: "Restkontamination im Tank aus Vor-KSS",
    workaround: "Komplette Tankreinigung mit Systemreiniger vor Wechsel",
    preventiveMeasure: "Wartung vor Wochenende, ggf. Wochenend-Umwaelzung",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rocol.com/datasheets/download/tds/6/ultracut%20evo%20250",
    sourceTitle: "Technical Data ULTRACUT EVO 250",
    sourceAuthor: "ROCOL",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool R 2030",
    manufacturerName: "Fuchs",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "KOOLRite-Anwender berichten von Geruchsfreiheit nach Wechsel von Ecocool",
    description: "Eine Chicago-Anlage wechselte von Fuchs ECOCOOL (Soluble) auf KOOLRite 2290, weil die Alternative 'Geruchsprobleme eliminierte' und gleichzeitig die Bearbeitungsleistung beibehielt. Indirekter Beleg fuer Geruchsproblematik in der Ecocool-Familie unter realen Werkstattbedingungen.",
    symptoms: ["Geruchsbildung", "Verkuerzte Standzeit"],
    rootCause: "Bakterielle Kontamination und/oder Tankmanagement",
    workaround: "Wechsel auf Alternativprodukt oder striktere Bakterienkontrolle",
    preventiveMeasure: "Bakterien-Dipslides, pH-Monitoring",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "USER_REPORT",
    sourceUrl: "https://koolrite.com/testimonials.php",
    sourceTitle: "Machine Coolant Success Stories | KOOLRite",
    sourceAuthor: "KOOLRite (Anwenderzitat)",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Bonderite C-AK 4181",
    manufacturerName: "Henkel",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Betriebstemperatur > 50°C fuer Effektivitaet noetig",
    description: "Henkel gibt fuer die C-AK-Reinigerfamilie an, dass die empfohlenen Betriebstemperaturen oft >50°C liegen muessen, damit die Tenside und alkalischen Komponenten wirksam OEle und Polierpasten loesen. Kalter Betrieb fuehrt zu mangelhafter Reinigung.",
    symptoms: ["Restoel auf Bauteilen", "Unzureichende Vorbereitung fuer Beschichtung"],
    rootCause: "Tenside nicht aktiviert bei kalter Anwendung",
    workaround: "Bad-Temperatur 50-60°C einstellen",
    preventiveMeasure: "Thermostat-geregelter Reinigungstank",
    affectedMaterials: ["Aluminium"],
    affectedOperations: ["Tauchreinigung", "Spritzreinigung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.silmid.com/knowledge-centre/aerospace-cleaning-content/bonderite-c-ak/",
    sourceTitle: "Bonderite C-AK Cleaner & Pretreatment Guide | Silmid",
    sourceAuthor: "Silmid/Henkel",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Renoform MZAN 51 N",
    manufacturerName: "Fuchs",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Chlorparaffin-haltige Stanz-/Drawing-Oele koennen Kontaktdermatitis ausloesen",
    description: "Klinische Fallstudie (PMC) dokumentiert allergische Kontaktdermatitis bei einem Bediener, der ein Stanzoel mit Mineraloel, Chlorparaffinen, EP- und Korrosionsschutz-Additiven verwendete - exakt die Zusammensetzung der MZAN-Reihe. EP-Additive und Konservierer wirken hautreizend.",
    symptoms: ["Kontaktdermatitis", "Sensibilisierung"],
    rootCause: "EP-Additive und Chlorparaffine in Hautkontakt",
    workaround: "PSA, chlorfreie Renoform-Alternativen pruefen",
    preventiveMeasure: "Hautschutzplan TRGS 401, geschlossene Maschinen",
    affectedMaterials: [],
    affectedOperations: ["Feinstanzen", "Tiefziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC153490/",
    sourceTitle: "Two cases of occupational allergic contact dermatitis from a cycloaliphatic epoxy resin in a neat oil",
    sourceAuthor: "PMC Case Report",
    sourceDate: "2003-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 705 B",
    manufacturerName: "Fuchs",
    category: "FOAM",
    severity: "LOW",
    title: "Ecocool 705 I wirbt mit Klarheits- und Schaumkontrolle - 705 B Standard nicht",
    description: "Fuchs hebt explizit fuer Ecocool 705 I (Aluminium-Variante) hervor, dass sie 'fuer Anwendungen geeignet ist, bei denen Klarheit und Schaumkontrolle kritisch sind'. Im Umkehrschluss: Standard-Varianten der 700er-Serie koennen bei kritischen Aluminium-Anwendungen zu Truebung/Schaum neigen.",
    symptoms: ["Schaum auf Aluminium-Werkstuecken", "Truebung des KSS"],
    rootCause: "Standard-Formulierung ohne spezielle Aluminium-Klarheitsadditive",
    workaround: "Bei kritischen Anwendungen auf 705 I oder Alustar BF wechseln",
    preventiveMeasure: "Aluminium-spezifische Variante in der Auslegung beruecksichtigen",
    affectedMaterials: ["Aluminium"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.silmid.com/dsweb/Get/Document-386156/ECOCOOL",
    sourceTitle: "ECOCOOL Brochure (Silmid)",
    sourceAuthor: "Fuchs / Silmid",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 6112 BF",
    manufacturerName: "Fuchs",
    category: "STABILITY",
    severity: "LOW",
    title: "Tramp-Oel-Eintrag schneidet KSS von Umgebung ab und treibt biologische Aktivitaet",
    description: "Fuchs warnt explizit: 'Tramp oils or other contaminants can lead to increased biological activity and odors' bei wassermischbaren Ecocool-KSS. Fremdoel-Eintrag bildet Film auf der Oberflaeche, isoliert das KSS-Bad und foerdert anaerobe Bakterien (uebler Geruch).",
    symptoms: ["Geruch (anaerobe Bakterien)", "Oel-Film auf KSS"],
    rootCause: "Tramp-Oel aus Hydraulik/Wegeoel auf Bad-Oberflaeche",
    workaround: "Skimmer (Band/Disk), regelmaessiges Abschoepfen",
    preventiveMeasure: "Wegeöl-Verbrauch kontrollieren, Dichtungen pruefen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/products/product-program/metal-processing-lubricants/water-miscible-coolants-tips/",
    sourceTitle: "Water-miscible Coolants - Tips | FUCHS LUBRICANTS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Renoform HE 50",
    manufacturerName: "Fuchs",
    category: "RESIDUES",
    severity: "MEDIUM",
    title: "Hochdruck-Umformschmierstoffe (Hydroforming) brauchen alkalische Nachreinigung",
    description: "Renoform-Hochdruck-Umformschmierstoffe (HE-Serie) werden bei IHU (Innenhochdruck-Umformung) eingesetzt. Wie alle Renoform-Forming-Oils ist nach dem Prozess alkalische Reinigung notwendig, sonst stoeren Schmierreste KTL/Lackierung und Schweissen.",
    symptoms: ["KTL-Krater", "Lackhaftungs-Probleme", "Schweissporen"],
    rootCause: "Persistenter Schmierfilm fuer IHU-Druecke bis 4000 bar",
    workaround: "Alkalischer Reiniger (Renoclean SMC / Bonderite C-AK)",
    preventiveMeasure: "Reinigungsstufe fest in Prozesskette einplanen",
    affectedMaterials: ["Stahl", "Aluminium"],
    affectedOperations: ["Hydroforming", "IHU"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/de/en/brands-and-product-lines/r-z/renoform/",
    sourceTitle: "Lubricants for Forming Processes | RENOFORM | FUCHS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Renoform TC 6",
    manufacturerName: "Fuchs",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Renoform-Reihe fuer Tube/Cone-Forming auf Cold-Header optimiert",
    description: "Fuchs Renoform-Familie ist explizit fuer 'schwierige Kaltumformoperationen auf Cold-Headern und Cold-Part-/Tube-Formern' konzipiert. Wenn diese Praeferenz nicht beachtet wird (z.B. bei generischem Tiefziehen), kommt es zu Verschleiss und Riefenbildung.",
    symptoms: ["Schmiermittelversagen", "Werkzeugverschleiss"],
    rootCause: "Falsche Auswahl: TC-Variante nicht fuer alle Umformprozesse geeignet",
    workaround: "Mit Fuchs-Anwendungstechnik Prozessabgleich machen",
    preventiveMeasure: "Renoform-Selector nutzen, Probelauf mit Verschleissmessung",
    affectedMaterials: ["Stahl", "Edelstahl"],
    affectedOperations: ["Kalt-Stauchen", "Rohrumformen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/product/product/154004-RENOFORM-EXT-319-HT/",
    sourceTitle: "RENOFORM EXT 319 HT | Metal processing | FUCHS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool XEP",
    manufacturerName: "Fuchs",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Ecocool 711/715 nicht fuer Messing und Kupfer freigegeben",
    description: "Fuchs gibt fuer Ecocool 711 und 715 (verwandte Aerospace-Familie wie XEP) explizit an: 'not recommended for brass or other copper alloys, and not recommended for brass or copper substrates'. Bei Mixed-Material-Bearbeitung mit Buntmetallen kommt es zu Verfaerbung.",
    symptoms: ["Verfaerbung Messing/Kupfer", "Grauschleier"],
    rootCause: "Amin- bzw. Boron-Komponenten reagieren mit Cu-Legierungen",
    workaround: "Auf Ecocool 400/420 (yellow-metal-vertraeglich) wechseln",
    preventiveMeasure: "Werkstoff-Verträglichkeitsmatrix vor Einsatz pruefen",
    affectedMaterials: ["Messing", "Kupfer", "Bronze"],
    affectedOperations: ["Drehen", "Fraesen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/us/en/product/product/134410-ECOCOOL-711/",
    sourceTitle: "ECOCOOL 711 | Metal processing | FUCHS LUBRICANTS",
    sourceAuthor: "Fuchs Lubricants",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ecocool 6112 BF",
    manufacturerName: "Fuchs",
    category: "STABILITY",
    severity: "LOW",
    title: "Wirksamkeit haengt stark von Anwendung, Werkstueck-Vorbehandlung und Verschmutzung ab",
    description: "Fuchs gibt selbst zu Protokoll: 'The effectiveness of products depends on many factors, particularly the specific application, product application, operating conditions, component pre-treatment, and external contamination.' Generische Aussagen zur Korrosionsbestaendigkeit oder Standzeit sind nicht moeglich.",
    symptoms: ["Variable Standzeit", "Variable Korrosionsschutzleistung"],
    rootCause: "Komplexe Abhaengigkeiten - kein Linear-Modell",
    workaround: "Anwendungsspezifische Erprobung, KSS-Wartungsplan",
    preventiveMeasure: "Strukturierter KSS-Pflegeplan nach TRGS 611",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.fuchs.com/at/de/produkt/product/56490-ECOCOOL-ALUSTAR-BF/",
    sourceTitle: "ECOCOOL ALUSTAR BF | Metallbearbeitung | FUCHS",
    sourceAuthor: "Fuchs Schmierstoffe",
    sourceDate: "2024-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Bonderite C-MC 1100",
    manufacturerName: "Henkel",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Mikrobielles Wachstum in wassermischbaren Systemen verursacht Geruch und Pumpenprobleme",
    description: "Henkel selbst beschreibt fuer die wassermischbare Bonderite-Range: 'microbial growth can become a real problem in water-based systems leading to obnoxious odors, residues and pumping issues in machining fluid systems generally.' Diese Praxis gilt fuer C-MC-Reiniger ebenso wie fuer L-MR-KSS.",
    symptoms: ["Uebler Geruch", "Pumpenverklebung", "Rueckstaende im System"],
    rootCause: "Bakterien-/Pilzbefall in wasserbasiertem Reinigerbad",
    workaround: "Reinigung mit Bonderite C-NE / regelmaessiger Komplettwechsel",
    preventiveMeasure: "Bad-Belueftung, regelmaessige Bakterien-Dipslides",
    affectedMaterials: [],
    affectedOperations: ["Industriereinigung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.chempoint.com/en-emea/insights/henkel-bonderite-machining-fluids-101",
    sourceTitle: "Henkel BONDERITE Machining Fluids 101 - ChemPoint",
    sourceAuthor: "ChemPoint/Henkel",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Ultracut Edm 1",
    manufacturerName: "ROCOL",
    category: "FILTRATION",
    severity: "MEDIUM",
    title: "EDM-Erosion: schlechte Spülung führt zu Carbon-Aufbau auf Elektrode",
    description: "Allgemeine, herstellerunabhaengige EDM-Praxis (gilt auch fuer Ultracut Edm 1): 'poor chip removal can cause the discharge point to concentrate in certain areas, leading to local heat accumulation and potential carbon formation and burns on the electrode surface.' Filtration und Spuelung sind kritisch.",
    symptoms: ["Carbon/Verkohlung auf Elektrode", "Brand-Stellen am Werkstueck"],
    rootCause: "Unzureichende Spuelung/Filtration im Funkenkanal",
    workaround: "Hoeherer Spueldruck, Pulsspuelung, Filter wechseln",
    preventiveMeasure: "Filter-Druckdiff. monitoren, Erodierloecher in Elektrode optimieren",
    affectedMaterials: [],
    affectedOperations: ["Senkerosion", "Drahterosion"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "OTHER",
    sourceUrl: "https://www.dmncedm.com/common-problems-and-solutions-of-wire-edm-machines.html",
    sourceTitle: "Wire Cut EDM Machine Issues & Solutions",
    sourceAuthor: "DMNC-EDM",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Isocut Sol M",
    manufacturerName: "Petrofer",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Isocut Al-Variante explizit fuer Buntmetalle - Standard Sol M nicht universell",
    description: "Petrofer bietet bewusst eine 'Isocut Al'-Variante fuer Nichteisen-Metalle mit Korrosionsschutz an. Das impliziert: die Standard-Isocut-Sol-Familie (M/K) ist nicht ohne Erprobung fuer alle Buntmetalle freigegeben.",
    symptoms: ["Verfaerbung Buntmetall", "Anlauffarben"],
    rootCause: "Standard-EP-Additive (S, Cl) reagieren mit Cu/Zn",
    workaround: "Isocut Al-Variante einsetzen, oder Bauteilreinigung direkt nach Bearbeitung",
    preventiveMeasure: "Werkstoff-Verträglichkeitstest vor Serieneinsatz",
    affectedMaterials: ["Messing", "Bronze", "Kupfer"],
    affectedOperations: ["Drehen", "Fraesen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.petrofer.com/en/product-range/metal-cutting-fluids/",
    sourceTitle: "Metal Cutting Fluids - PETROFER",
    sourceAuthor: "Petrofer",
    sourceDate: "2024-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Multan 65-3 RD",
    manufacturerName: "Henkel",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Alte Multan-Generation: jaehrlicher Komplettwechsel des Kuehlbades noetig",
    description: "Konkretes Anwender-Beispiel (Walter AG via Henkel-Case): 'Das Unternehmen musste das gesamte Kuehlbad einmal im Jahr austauschen, weil die Emulsionen aufgrund hoher bakterieller Kontamination splitteten' - mit klassischen Multan-Varianten. Mit Multan 71-2 (bactericidfreie Plattform) konnte stabiler Betrieb ueber 18 Monate ohne Wechsel erreicht werden.",
    symptoms: ["Emulsionsbruch", "Pflicht-Komplettwechsel pro Jahr"],
    rootCause: "Bakterien-Eskalation und Emulsions-Split bei klassischer Multan-Generation",
    workaround: "Umstieg auf bactericidfreie Multan 71-2 / Bonderite L-MR 21420 etc.",
    preventiveMeasure: "Lieferanten-Pruefung auf bactericidfreie Aktuell-Variante",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://www.mta.org.uk/whats-new/members-news/bactericide-free-cutting-fluid-henkel-stays-bacteria-free",
    sourceTitle: "Bactericide-free cutting fluid from Henkel, stays bacteria free | MTA",
    sourceAuthor: "MTA / Henkel Case Study",
    sourceDate: "2018-01-01",
    language: "EN",
    isOfficial: true
  },
];
