export default [
  {
    productName: "Hycut ET 46",
    manufacturerName: "Oemeta",
    category: "FOAM",
    severity: "HIGH",
    title: "Schaum und Fremdöl-Probleme bei extrem hartem Wasser (35 °dH)",
    description: "Vor Umstellung auf Hycut hatte Gehring beim Honen massive Schaum- und Fremdölprobleme mit dem Vorgängerprodukt. Mischwasser mit 35 °dH und 60 mg/l Chlorid; Vorgänger benötigte >10 % Konzentration. Mit Hycut ET 46 + Additiv BX bei 3–4 % (Zerspanung) bzw. 1–3 % (Schleifen) stabilisiert; Standzeit von 9 Monaten auf ca. 2,5 Jahre, Werkzeugstandzeit 2,5-fach.",
    symptoms: ["Schaumbildung", "Fremdölakkumulation", "kurze Standzeit", "hoher Verbrauch"],
    rootCause: "Hartes Wasser mit hohem Chloridanteil destabilisierte den Vorgänger-KSS; Mineralöl-Vorgänger emulgierte Leckölmengen ein",
    workaround: "Umstellung auf Esteröl-Zweikomponentensystem mit Skimmer für Fremdöl",
    preventiveMeasure: "Esteröl-KSS, separate Skimmer-Strategie, separate Dosierung von Öl- und Additivkomponente",
    affectedMaterials: ["Stahl", "Edelstahl", "Aluminium", "Grauguss"],
    affectedOperations: ["Honen", "Zerspanung", "Schleifen"],
    reportedConcentration: 3.5,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oemeta.com/the-coolant-people/erfolgreiche-partnerschaften/gehring",
    sourceTitle: "Anwendungsbericht Gehring & Oemeta",
    sourceAuthor: "Oemeta",
    sourceDate: "2014-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hycut Plus",
    manufacturerName: "Oemeta",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Temperatur-Instabilität führt zu Konsistenz-Schwankungen über Nacht",
    description: "MillCon GmbH (NÖ) berichtet, dass beim Vorgängerprodukt KSS-Konsistenz über Nacht durch Temperaturschwankungen kippte; mehrtägige Stillstände für Reinigung waren nötig. Mit Hycut über zentrale Lubot-Versorgung wurde Temperatur und Qualität stabilisiert.",
    symptoms: ["Konsistenz-Veränderung", "Stillstand für Reinigung (bis zu 2 Tage)", "Korrekturen am Werkstück"],
    rootCause: "Temperaturschwankungen im dezentralen KSS-System",
    workaround: "Zentrale temperierte Lubot-Versorgung",
    preventiveMeasure: "Modulare Hycut-Lösung mit konstanter Temperatur und Qualitätskontrolle",
    affectedMaterials: ["Aluminium"],
    affectedOperations: ["Fräsen", "Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.zerspanungstechnik.com/bericht/schmierungkuehlung/in_groen_kss_dimensionen_denken-2020-05-18",
    sourceTitle: "Hycut von Oemeta - In großen KSS-Dimensionen denken",
    sourceAuthor: "Zerspanungstechnik.com",
    sourceDate: "2020-05-18",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Hycut ET 46",
    manufacturerName: "Oemeta",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Vorgänger-KSS verursachte Dermatitis und Rauchprobleme — Umstellung auf Hycut behob beides",
    description: "Ein Practical-Machinist-Anwender berichtet: Werkstatt stellte vor ca. 3 Jahren von Cimcool auf Oemeta um, da Mitarbeiter unter Dermatitis litten und es starke Rauchbildung gab. Nach Umstellung auf Hycut waren beide Probleme weg.",
    symptoms: ["Dermatitis", "Rauchbildung", "Hautreizung"],
    rootCause: "Vorgängerprodukt enthielt aggressivere Tenside/Biozide; Mineralöl-Aerosol verursachte Rauchbildung",
    workaround: "Umstellung auf esterölbasiertes Hycut-System",
    preventiveMeasure: "Esteröl-basierte KSS mit niedrigerer Aerosolbildung; bessere Hautverträglichkeit",
    affectedMaterials: [],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anybody-using-hycut-a-2-component-cutting-fluid.257799/",
    sourceTitle: "Anybody using Hycut - a 2 component cutting fluid? - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2021-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hycut ET 46",
    manufacturerName: "Oemeta",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Rostbildung an Stahlteilen während längerer Maschinenstandzeit",
    description: "Practical-Machinist-Anwender: 'If not for the rust issue, the product was the best multiuse coolant I have ever used.' Bei längeren Stillstandzeiten und unzureichender Korrosionsschutz-Additivdosierung trat Rostbildung auf Stahlteilen auf.",
    symptoms: ["Flugrost", "Korrosion an Werkstücken bei Standzeit"],
    rootCause: "Zwei-Komponenten-System erfordert exakte Dosierung des Additivs; bei zu niedrigem Additivanteil sinkt Korrosionsschutz",
    workaround: "Additiv-Konzentration regelmäßig prüfen und korrekt nachdosieren",
    preventiveMeasure: "Tägliche Kontrolle der beiden Komponenten (Öl- und Additivanteil) per Refraktometer und Titration",
    affectedMaterials: ["Stahl"],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anybody-using-hycut-a-2-component-cutting-fluid.257799/",
    sourceTitle: "Anybody using Hycut - a 2 component cutting fluid? - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2020-06-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hycut Plus",
    manufacturerName: "Oemeta",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Hoher Aufwand bei Dosierungskontrolle wegen Zwei-Komponenten-System",
    description: "Anwender (13 CNC-Drehmaschinen, 16 CNC-Fräsmaschinen) berichtet, dass Hycut als Zwei-Komponenten-Produkt zusätzlichen Mess- und Pflegeaufwand verursacht: Konzentrationen sowohl des Additivs als auch der Schneidkomponente müssen separat geprüft werden. Trotzdem 'definite improvement over anything else we have used'.",
    symptoms: ["höherer Prüfaufwand", "Komplexität der Konzentrationsmessung"],
    rootCause: "Zwei-Komponenten-Konzept (Öl + Additiv) erfordert duale Messmethoden",
    workaround: "Routine etablieren mit Refraktometer (Öl) + Titration (Additiv)",
    preventiveMeasure: "Schulung der KSS-Betreuer, regelmäßige Stichproben",
    affectedMaterials: ["Stahl", "Edelstahl"],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anybody-using-hycut-a-2-component-cutting-fluid.257799/",
    sourceTitle: "Anybody using Hycut - a 2 component cutting fluid? - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hycut Plus",
    manufacturerName: "Oemeta",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Verdoppelung der Werkzeugstandzeit bei 316 Edelstahl",
    description: "Practical-Machinist-Anwender: Nach Umstellung von wassermischbarem Öl auf Hycut 'night and day in performance' mit 'easily double insert life' bei Bearbeitung von 316 Edelstahl.",
    symptoms: ["vorher kurze Standzeit", "nach Umstellung verdoppelt"],
    rootCause: "Höhere Schmierfähigkeit des Esteröl-Konzepts",
    workaround: null,
    preventiveMeasure: "Esteröl-Zweikomponentensystem für anspruchsvolle Werkstoffe",
    affectedMaterials: ["Edelstahl 316"],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/anybody-using-hycut-a-2-component-cutting-fluid.257799/",
    sourceTitle: "Anybody using Hycut - a 2 component cutting fluid? - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2021-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Sintogrind FE",
    manufacturerName: "oelheld",
    category: "TOOL_WEAR",
    severity: "MEDIUM",
    title: "Cobalt-Auswaschung beim Hartmetallschleifen wird durch Sintogrind TTK verhindert",
    description: "Trako-Werkzeuge stellte bei Herstellung von Trakomill-Fräsern auf Sintogrind TTK um, um beste Oberflächengüten, höhere Schleifscheibenstandzeit und vor allem Verhinderung der Cobalt-Auswaschung zu erreichen. Vorgängerprodukte zeigten Cobalt-Auswaschung beim Schleifen von Hartmetall.",
    symptoms: ["Cobalt-Auswaschung", "schlechte Oberfläche", "geringe Schleifscheibenstandzeit"],
    rootCause: "Konventionelle Schleiföle ohne PAO-Basis enthalten Komponenten, die Cobalt aus Hartmetallbindung lösen",
    workaround: "Wechsel zu PAO-basiertem synthetischem Schleiföl mit speziellem Cobalt-Inhibitor",
    preventiveMeasure: "Sintogrind TTK auf Polyalphaolefin-Basis für Hartmetall- und HSS-Bearbeitung",
    affectedMaterials: ["Hartmetall", "Werkzeugstahl", "Titan", "Aluminium", "CFK"],
    affectedOperations: ["Schleifen", "Werkzeugschleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://www.fertigung.de/schwerpunkt/schleifen/warum-trako-werkzeuge-sintogrind-ttk-von-oelheld-einsetzt-839.html",
    sourceTitle: "Warum Trako-Werkzeuge Sintogrind TTK von Oelheld einsetzt",
    sourceAuthor: "fertigung.de",
    sourceDate: "2022-05-19",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Sintogrind FZ",
    manufacturerName: "oelheld",
    category: "PERFORMANCE",
    severity: "MEDIUM",
    title: "Sintogrind IG 540 löste Produktionsengpässe bei CTC Indien",
    description: "Indischer Werkzeughersteller CTC nutzt Sintogrind IG 540 zur Verzahnungs-, Profil-, Außen- und Innenrundschleifen von Hartmetall, HSS, CBN, PKD, Cermet und Keramik. Vorher: längere Bearbeitungszeiten, schwankende Oberflächenqualität, hoher Wartungsaufwand. Mit Sintogrind IG 540 (PAO-Basis) wurde Prozessstabilität für Großserien erreicht.",
    symptoms: ["lange Bearbeitungszeiten", "schwankende Oberflächengüte", "hoher Wartungsaufwand"],
    rootCause: "Ungeeignete Viskosität/Standzeit des Vorgänger-Schleiföls",
    workaround: null,
    preventiveMeasure: "PAO-basiertes Multifunktions-Schleiföl mit langer Standzeit",
    affectedMaterials: ["Hartmetall", "HSS", "CBN", "PKD", "Cermet", "Keramik"],
    affectedOperations: ["Profilschleifen", "Außenrundschleifen", "Innenrundschleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://mav.industrie.de/anlagen-verfahren/wo-praezision-auf-perfektion-trifft/",
    sourceTitle: "Indischer Werkzeughersteller CTC nutzt Schleiföl von Oelheld",
    sourceAuthor: "MAV Industrie",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Sintilo 22 W",
    manufacturerName: "oelheld",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Allgemeine Schaumbildung bei wassermischbaren KSS — oelheld-FAQ empfiehlt Ursachenanalyse",
    description: "oelheld dokumentiert in der FAQ für wassermischbare KSS (Sintilo-Familie u.a.): Schaumbildung wird durch niedrigen Tankfüllstand, Lufteinzug oder zu hohe Konzentration verursacht. Maßnahmen: Konzentration prüfen/reduzieren, Lufteinzug eliminieren, Tankfüllstand sichern, ggf. Entschäumer.",
    symptoms: ["Schaum", "Überlauf", "schlechte Spülwirkung"],
    rootCause: "Zu hohe Konzentration, niedriger Tankfüllstand, Lufteinzug bei Pumpen",
    workaround: "Konzentration auf empfohlenen Wert reduzieren, Tankfüllstand >75 % halten",
    preventiveMeasure: "Wöchentliche Konzentrationskontrolle per Refraktometer, Sichtprüfung Lufteinzug",
    affectedMaterials: [],
    affectedOperations: ["Drehen", "Fräsen", "Schleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/service/faq/massnahmen-zur-problembehebung-bei-wassermischbaren-kuehlschmierstoffen/",
    sourceTitle: "Maßnahmen zur Problembehebung bei wassermischbaren Kühlschmierstoffen",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Sintilo 67",
    manufacturerName: "oelheld",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Pilz-/Bakterienbefall bei wassermischbaren oelheld-KSS — Ursachenkatalog",
    description: "oelheld-FAQ benennt für wassermischbare KSS (inkl. Sintilo-Serie) als Ursachen für mikrobiellen Befall: belastetes Mischwasser, niedrige pH-Werte, lange Stillstandzeiten. Folge: Geruch, kurze Standzeit, schlechte Korrosionsschutzwirkung.",
    symptoms: ["Geruch", "Trübung", "pH-Abfall", "kurze Standzeit"],
    rootCause: "Belastetes Mischwasser, pH-Wert <8.5, anaerobe Bedingungen bei Stillstand",
    workaround: "pH-Wert anheben (pH 9), KSS umpumpen/belüften, Tank reinigen",
    preventiveMeasure: "Wasserqualität prüfen (Keimzahl), regelmäßige Umwälzung auch bei Stillstand, KSS-Pflege gemäß TRGS 611",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: 8.5,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/service/faq/massnahmen-zur-problembehebung-bei-wassermischbaren-kuehlschmierstoffen/",
    sourceTitle: "Maßnahmen zur Problembehebung bei wassermischbaren Kühlschmierstoffen",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Sintilo S-3",
    manufacturerName: "oelheld",
    category: "WORKPIECE_STAINS",
    severity: "MEDIUM",
    title: "Verfärbungen bei wassermischbaren KSS — Ursachenanalyse",
    description: "oelheld dokumentiert in FAQ Verfärbungen: Grün-blau bei Kupferbearbeitung, rosa bei Hartmetall/PKD (gelöstes Cobalt — krebserregend), grau beim KSS-Wechsel oder Graphit, braun durch Fremölaufnahme (Hydraulik-/Bahnöl). Bei Rosa-Verfärbung sofortige Korrektur nötig wegen Krebsrisiko.",
    symptoms: ["Rosa-Verfärbung", "Grünstich", "Braunfärbung", "Grau-Trübung"],
    rootCause: "Metallabrieb/Cobalt-Auswaschung, Fremdöleintrag aus Maschinenleckagen, Graphitstaub",
    workaround: "Bei Rosa-Verfärbung: Cobalt-Inhibitor zusetzen oder KSS wechseln; bei Braunfärbung Skimmer einsetzen",
    preventiveMeasure: "Maschinenleckagen beheben, Cobalt-geeignete Inhibitoren verwenden (z.B. AquaTec 5001 für Hartmetall)",
    affectedMaterials: ["Kupfer", "Hartmetall", "Buntmetalle"],
    affectedOperations: ["Drehen", "Fräsen", "Schleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/service/faq/kuehlschmierstoff-farbe/",
    sourceTitle: "Kühlschmierstoff verfärbt",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hocut 3380",
    manufacturerName: "oelheld",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Hocut 3380 für hochlegierte Stähle und schwer zerspanbare Werkstoffe — bor-frei mit langer Standzeit",
    description: "Hocut 3380 ist ein bor-freier Hochleistungs-KSS mit hoher Schmierfähigkeit für Titan, Inconel und Legierungsstähle. Speziell für Weichwasser-Anwendungen designed; geringe Schaumneigung für moderne Hochdruck-KSS-Zuführsysteme. Bor-frei verlängert Standzeit ohne regelmäßige Biozidzugabe.",
    symptoms: [],
    rootCause: null,
    workaround: null,
    preventiveMeasure: "Bor-freie Formulierung ohne regelmäßige Biozid-Nachdosierung; geeignet für Weichwasser",
    affectedMaterials: ["Titan", "Inconel", "Legierungsstahl"],
    affectedOperations: ["schwere Zerspanung", "Hochdruck-Bearbeitung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.kernow-oils.co.uk/products/houghton-hocut-3380/",
    sourceTitle: "Quaker Houghton Hocut 3380 - Kernow Oils",
    sourceAuthor: "Kernow Oils",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Rhenus FU 51",
    manufacturerName: "Rhenus Lub",
    category: "REGULATORY",
    severity: "LOW",
    title: "Amin- und borsäurefreie Formulierung verhindert Nitrosamin-Bildung gem. TRGS 611",
    description: "Rhenus FU 51 ist Teil der amin- und borsäurefreien Generation. Hintergrund: TRGS 611 (BAuA) schreibt Verwendungsbeschränkungen für KSS vor, bei denen N-Nitrosamine auftreten können. Sekundäre Amine können sich zu krebserregenden Nitrosaminen wandeln. Rhenus FU 51 vermeidet dieses Risiko konstruktiv.",
    symptoms: [],
    rootCause: "Konventionelle KSS mit sekundären Aminen können Nitrosamine bilden (krebserregend)",
    workaround: null,
    preventiveMeasure: "Wahl eines amin- und borsäurefreien KSS; FU 51 erfüllt TRGS 611 ohne Zusatzmaßnahmen",
    affectedMaterials: ["Stahl", "Guss", "Aluminium", "Nickelbasis"],
    affectedOperations: ["Bohren", "Drehen", "Fräsen", "Sägen", "Reiben", "Tiefbohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/produkt/rhenus-fu-51/",
    sourceTitle: "rhenus FU 51 | Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Rhenus FU 60",
    manufacturerName: "Rhenus Lub",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Esteröl-basiert, amin-/borsäurefrei — Luftfahrtfreigaben (Airbus, Safran, Embraer)",
    description: "Rhenus FU 60 ist esterölbasiert, amin- und borsäurefrei, WGK 1, gute Hautverträglichkeit. Für Silumin-Aluminium, zähe Stähle, Titanlegierungen, Nickelbasis. Praxis-Aspekt: Luftfahrtfreigaben Airbus/Safran/Embraer erfordern lückenlose Dokumentation der Inhaltsstoffe; konventionelle Mineralöl-KSS verlieren häufig solche Freigaben.",
    symptoms: [],
    rootCause: null,
    workaround: null,
    preventiveMeasure: "Esteröl-Basis und Aminefreiheit für anspruchsvolle Branchen (Luftfahrt, Medizintechnik)",
    affectedMaterials: ["Aluminium-Silumin", "Stahl", "Titanlegierungen", "Nickelbasis"],
    affectedOperations: ["Bohren", "Drehen", "Fräsen", "Wälzfräsen", "Räumen", "Tiefbohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/produkt/rhenus-fu-60/",
    sourceTitle: "Rhenus FU 60 Neat Cutting Oil for Machining | Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Rhenus FU 53",
    manufacturerName: "Rhenus Lub",
    category: "FOAM",
    severity: "LOW",
    title: "FU 53 W bewirbt 'besonders schaumarm' und 'bakterizidfrei' — Anwendungsschwerpunkt Aluminium und Stahl",
    description: "Rhenus FU 53 W ist EP-Kühlschmierstoff für schwere Zerspanung von Stahl, Guss und Aluminium, ohne Bakterizide. Aluminiumkorrosion bleibt bei ungeeigneten KSS ein bekanntes Problem (Weißrost, Kontaktkorrosion) — FU 53 W ist speziell für Aluminium-Verträglichkeit ausgelegt.",
    symptoms: ["potenzielle Weißrostbildung bei ungeeigneten KSS"],
    rootCause: "pH-Instabilität greift Oxidschicht an; falsche KSS-Wahl",
    workaround: null,
    preventiveMeasure: "KSS gezielt für Aluminium auswählen, pH-Wert kontrollieren (8.8-9.2), Konzentration einhalten",
    affectedMaterials: ["Aluminium", "Stahl", "Guss"],
    affectedOperations: ["schwere Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.hpmtechnologie.de/produkt/rhenus-fu-53-w",
    sourceTitle: "rhenus FU 53 W | Wassermischbarer Kühlschmierstoff",
    sourceAuthor: "HPM Technologie",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Rhenus r-meta CN 100",
    manufacturerName: "Rhenus Lub",
    category: "OPERATOR_HEALTH",
    severity: "HIGH",
    title: "Cobalt-Auswaschung bei Hartmetall — amin-freier KSS gem. TRGS 561 empfohlen",
    description: "Bei Hartmetallbearbeitung werden Cobalt-Ionen aus dem Bindemittel gelöst (Cobalt-Leaching) — gesundheitsgefährdend (krebsverdächtig). BAuA/TRGS 561 empfiehlt amin-freie, gegen Buntmetalle/Hartmetalle inhibierte KSS. Amine verstärken die Cobalt-Auswaschung erheblich. Rhenus r-meta-Linie ist für diese Anforderung formuliert.",
    symptoms: ["Rosa-Verfärbung KSS", "erhöhte Cobalt-Konzentration im KSS-Aerosol", "Atemwegsreizung"],
    rootCause: "Amine in KSS komplexieren Cobalt und erhöhen Lösungsrate aus Hartmetallbindung",
    workaround: "Amin-freier KSS mit Buntmetall-Inhibitor (komplexiert Cobalt-Ionen → filterbar)",
    preventiveMeasure: "Konsequente Verwendung spezialformulierter, amin-freier KSS gem. TRGS 561",
    affectedMaterials: ["Hartmetall (Wolframcarbid/Cobalt)", "PKD"],
    affectedOperations: ["Schleifen", "Schärfen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "REGULATORY",
    sourceUrl: "https://www.baua.de/DE/Angebote/Regelwerk/TRGS/TRGS-611",
    sourceTitle: "TRGS 611 / TRGS 561 BAuA",
    sourceAuthor: "BAuA",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Rhenus FU 800",
    manufacturerName: "Rhenus Lub",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Vorgänger-KSS mit Formaldehyd-Depots (1B-Karzinogen) — FU 800 als formaldehydfreie Alternative",
    description: "Rhenus FU 800 (Markteinführung KSS-Messe Stuttgart 05.–07.05.2015) wurde als Antwort auf gesundheitliche Bedenken konzipiert: Formaldehyd-Depots in vielen klassischen KSS wirken bakterizid, sind aber als 1B-Karzinogen eingestuft. FU 800 verzichtet auf Amine, Borsäure und Formaldehyd-Depots; weiterhin uneingeschränkte Performance in Praxistests.",
    symptoms: ["Formaldehyd-Exposition", "potenzielle Karzinogenität klassischer KSS"],
    rootCause: "Klassische KSS verwenden Formaldehyd-Depots zur Bakteriostatik",
    workaround: null,
    preventiveMeasure: "Verwendung von KSS ohne Formaldehyd-Depots, Amine und Borsäure",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/rhenus-fu-800-premiere-at-the-kss-trade-fair/",
    sourceTitle: "Rhenus FU 800 at KSS: Formaldehyde-Free | Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2015-05-05",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Eni Aquamet HD 10",
    manufacturerName: "Eni",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Aquamet HD EP-FAD: chlorfrei, formaldehyd-abspalterfrei — empfohlene Konzentration variiert stark nach Anwendung",
    description: "Eni aquamet HD EP-FAD ist mineralölhaltig, chlorfrei, formaldehyd-abspalterfrei, mit polaren Wirkstoffen. Konzentrations-Empfehlung: 5±1 % normal, 7-10 % schwere Zerspanung, 4 % Schleifen — Praxis: bei zu niedriger Konzentration Korrosions- und Standzeitprobleme; bei zu hoher Konzentration Schaum und Hautirritationen.",
    symptoms: ["bei Unter-/Überdosierung: Korrosion oder Schaum"],
    rootCause: "Falsche Konzentration für jeweilige Operation",
    workaround: "Konzentration operationsspezifisch einstellen",
    preventiveMeasure: "Tägliche Refraktometer-Kontrolle, operationsspezifische Dosierung",
    affectedMaterials: ["Aluminium", "Stahl", "Guss"],
    affectedOperations: ["mittlere Zerspanung", "schwere Zerspanung", "Schleifen"],
    reportedConcentration: 5,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.baumannoil.de/eni-aquamet-ay-abf-fad-fass",
    sourceTitle: "Eni Aquamet HD EP - FAD",
    sourceAuthor: "BaumannOil",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Eni Aquamet KS",
    manufacturerName: "Eni",
    category: "OPERATOR_HEALTH",
    severity: "MEDIUM",
    title: "Aquamet LMK 2020 Plus enthält 3-Iodo-2-propinylbutylcarbamat (IPBC) — Allergie-Risiko gemäß SDB",
    description: "Sicherheitsdatenblatt Eni aquamet LMK 2020 Plus weist 3-Iodo-2-propinylbutylcarbamat (Biozid IPBC) aus, der bei sensibilisierten Personen allergische Hautreaktionen auslösen kann. Auch wenn Aquamet-Linie auf reduzierten Biozid-Anteil ausgelegt ist, bleibt Restrisiko. SDB-Hinweis: 'Kann allergische Reaktion verursachen'.",
    symptoms: ["Hautreizung", "Kontaktdermatitis bei Sensibilisierten"],
    rootCause: "IPBC als Konservierungsmittel mit allergenem Potenzial",
    workaround: "Hautschutz (Handschuhe), Hautschutz-/Pflegeplan TRGS 401",
    preventiveMeasure: "Hautschutzpläne, persönliche Schutzausrüstung; Vermeidung längeren Hautkontakts",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: 9.8,
    sourceType: "SDS",
    sourceUrl: "https://oel-engel.de/mediafiles/Sicherheitsdatenblatt/MSDS18540_Eni_aquamet_LMK_2020_Plus.pdf",
    sourceTitle: "SDS Eni aquamet LMK 2020 Plus",
    sourceAuthor: "Eni / Enilive",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Eni Aquamet HD 10",
    manufacturerName: "Eni",
    category: "STABILITY",
    severity: "LOW",
    title: "Anmischreihenfolge kritisch: Produkt in Wasser, nie umgekehrt — sonst Emulsionsinstabilität",
    description: "Eni-SDB-Hinweis und Herstellerempfehlung: Aquamet-Produkte stets in das Wasser geben, nie Wasser in das Konzentrat. Falsche Reihenfolge verursacht Phasentrennung, klumpiges Konzentrat, Emulsionsinstabilität. Lagertemperatur 5-30 °C in geschlossenen Behältern.",
    symptoms: ["Emulsions-Auftrennung", "Verklumpung beim Anmischen"],
    rootCause: "Falsche Anmischreihenfolge oder Lagerung außerhalb 5-30 °C",
    workaround: "KSS frisch anmischen, Konzentrat in Wasser einrühren, Mischpumpe verwenden",
    preventiveMeasure: "Personalschulung Anmischvorgang, Mischautomat einsetzen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "SDS",
    sourceUrl: "https://oel-engel.de/mediafiles/Sicherheitsdatenblatt/MSDS18540_Eni_aquamet_LMK_2020_Plus.pdf",
    sourceTitle: "SDS Eni aquamet LMK 2020 Plus",
    sourceAuthor: "Eni / Enilive",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Sintilo 22 W",
    manufacturerName: "oelheld",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Korrosion bei zu niedrigem pH-Wert oder unzureichender Konzentration",
    description: "oelheld-FAQ: Korrosionsfälle bei wassermischbaren KSS treten primär bei pH-Wert <8.8 oder Unterdosierung auf. Folge: Flugrost auf Werkstücken, Maschinenbett, Späne. Maßnahmen: Konzentration prüfen, pH-Wert anheben, frischen KSS nachdosieren.",
    symptoms: ["Flugrost", "Korrosion an Werkstücken", "Korrosion an Maschinenbett"],
    rootCause: "pH-Wert zu niedrig (<8.8) oder Konzentration unter Mindestwert",
    workaround: "Konzentration anheben auf ≥5 %, pH per Booster auf 9.0+ anheben",
    preventiveMeasure: "Wöchentliche pH- und Konzentrationskontrolle",
    affectedMaterials: ["Stahl", "Guss"],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: 8.8,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/service/faq/massnahmen-zur-problembehebung-bei-wassermischbaren-kuehlschmierstoffen/",
    sourceTitle: "Maßnahmen zur Problembehebung bei wassermischbaren Kühlschmierstoffen",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hocut 3380",
    manufacturerName: "oelheld",
    category: "FOAM",
    severity: "LOW",
    title: "Niedrige Schaumneigung speziell für moderne Hochdruck-KSS-Zuführsysteme",
    description: "Hocut 3380 ist für moderne Hochdruck-KSS-Anwendungen entwickelt: niedrige Schaumneigung essentiell, da Hochdrucksysteme (40-80 bar) Schaum sonst massiv verstärken. Schaumprobleme bei Standard-KSS sind eine der häufigsten Ursachen für Maschinen-Stopps bei Hochdruck-Bearbeitung.",
    symptoms: [],
    rootCause: "Standard-KSS schäumt unter Hochdruck stark; ungeeignet für moderne Anwendungen",
    workaround: null,
    preventiveMeasure: "Hochdruck-optimierte Bor-freie Formulierung mit reduzierter Schaumneigung",
    affectedMaterials: ["Titan", "Inconel", "Legierungsstahl"],
    affectedOperations: ["Hochdruck-Tiefbohren", "Hochdruck-Bearbeitung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.thelubricationstore.com/product/hocut-3380/",
    sourceTitle: "Hocut 3380 from Quaker Houghton - The Lubrication Store",
    sourceAuthor: "The Lubrication Store",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hocut 3380",
    manufacturerName: "oelheld",
    category: "SHELF_LIFE",
    severity: "MEDIUM",
    title: "Hocut-Produktreihe: dokumentierter brauner Wachs-Belag bei abgelaufenem Konzentrat",
    description: "Forum-Berichte für Hocut 795-Linie (zugehörige Quaker-Houghton-Familie): Anwender mit langjährigem Hocut-Einsatz berichten plötzlich ab ca. 2018 von braunem wachsartigen Belag in Maschinen. Herstellertechniker (Houghton) bestätigten: Produkt-Shelf-Life ca. 6 Monate; abgelaufenes Konzentrat verursacht das Problem. Übertragbar auf Hocut 3380 wegen verwandter Bor-freier Chemie.",
    symptoms: ["brauner Wachs-Belag in Maschinen", "Trennung der Emulsion", "verkürzte Standzeit"],
    rootCause: "Konzentrat über Mindesthaltbarkeit (6 Monate); Komponenten beginnen zu separieren",
    workaround: "Charge prüfen (Date Code), bei überaltertem Konzentrat ersetzen",
    preventiveMeasure: "FIFO-Lagerhaltung des Konzentrats, Date Code dokumentieren, Kanister-Rotation",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/hocut-795b-issues.361622/",
    sourceTitle: "Hocut 795B issues - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Jokisch LB-100",
    manufacturerName: "Jokisch",
    category: "OPERATOR_HEALTH",
    severity: "LOW",
    title: "LB-100 Schweißtrennmittel — Sicherheitsdatenblatt-relevante Inhaltsstoffe für Hautkontakt",
    description: "Jokisch LB-100 (anti-spatter liquid) ist als Schweißtrennmittel ausgelegt. SDS dokumentiert übliche PSA-Hinweise; bei häufigem Hautkontakt empfiehlt SDS Handschuhe und Augenschutz. Spritzer auf Werkstücken können bei nachfolgender KSS-Anwendung als 'Fremdstoff' wirken und KSS-Standzeit reduzieren.",
    symptoms: ["Hautirritation bei direktem Kontakt", "potenzielle KSS-Kontamination"],
    rootCause: "Anti-Spatter-Liquid kann KSS bei Übertrag in Maschine einbringen",
    workaround: "Werkstücke vor Zerspanung reinigen, Trennung von Schweiß- und Zerspanungsbereich",
    preventiveMeasure: "PSA-Plan, klare Bereichstrennung, Reinigungsroutine vor KSS-Kontakt",
    affectedMaterials: [],
    affectedOperations: ["Schweißen vor Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "SDS",
    sourceUrl: "https://www.haskellcorp.com/SDS/Aerosols/jokisch%20lb-100%20liquid.pdf",
    sourceTitle: "Jokisch LB-100 Liquid MSDS",
    sourceAuthor: "Jokisch / Haskell",
    sourceDate: "2020-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Jokisch S 50",
    manufacturerName: "Jokisch",
    category: "BIOLOGY",
    severity: "LOW",
    title: "Jokisch wassermischbare KSS: gute Biostabilität nach Herstellerangabe, aber TRGS-Pflege erforderlich",
    description: "Jokisch dokumentiert für seine wassermischbare KSS-Linie 'gute Langzeit-Stabilität und hohe Resistenz gegen Pilze und Bakterien'. Trotzdem: Anwender müssen TRGS 611 (KSS-Pflege) einhalten — sonst verkürzte Standzeit, Geruch, pH-Abfall. Im Forum (Zerspanungsbude) berichten Anwender, dass auch Jokisch-KSS bei mangelnder Pflege nach 3-6 Monaten kippen kann.",
    symptoms: ["Geruch nach 3+ Monaten ohne Pflege", "pH-Abfall", "Schaum"],
    rootCause: "Mangelnde KSS-Pflege (kein Umpumpen, keine Konzentrations-/pH-Kontrolle)",
    workaround: "Wöchentliche KSS-Pflege, Skimmer, Umpumpen während Stillstandzeiten",
    preventiveMeasure: "TRGS 611 Pflegekonzept etablieren, wöchentliche Messprotokolle",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.jokisch-fluids.de/catalog/de/kuehlschmierstoffe/mineraloelhaltige-ks/",
    sourceTitle: "Mineralölhaltige KSS | Jokisch GmbH",
    sourceAuthor: "Jokisch",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Jokisch B-CUT 80",
    manufacturerName: "Jokisch",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Jokisch Schneidöl-Linie: hohe Hautverträglichkeit nach Herstellerangabe (Monos Atos N2B/N3S)",
    description: "Jokisch dokumentiert hohe Hautverträglichkeit der Schneidöle Monos Atos N2B/N3S 'aufgrund der Komponentenauswahl'. Zerspanungsbude-Forum bestätigt für ehemaliges Alpha 93 (jetzt SOLIS AMBO N3S): 'verfärbt Leichtmetalle nicht, geruchlos'. Übertragbar auf B-CUT 80 als verwandte mineralölhaltige Schneidöl-Linie.",
    symptoms: [],
    rootCause: null,
    workaround: null,
    preventiveMeasure: "Wahl mineralölfreier Schneidöle für höhere Hautverträglichkeit",
    affectedMaterials: ["Aluminium", "Leichtmetalle"],
    affectedOperations: ["Bohren", "Drehen", "Gewindeschneiden"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://forum.zerspanungsbude.net/viewtopic.php?t=67093&start=50",
    sourceTitle: "Gutes und günstiges Schneidöl - Zerspanungsbude",
    sourceAuthor: "Zerspanungsbude Community",
    sourceDate: "2023-01-27",
    language: "DE",
    isOfficial: false
  },
  {
    productName: "Hycool 75 PRO",
    manufacturerName: "Oemeta",
    category: "COMPATIBILITY",
    severity: "LOW",
    title: "Oemeta verweist für stainfähige Aluminium-Legierungen explizit auf Novamet 900 statt Standard-Hycut",
    description: "Oemeta-Produkthinweis: Bei verstainungsanfälligen Aluminium-Legierungen (NE-Metalle, Zn-haltige Al-Legierungen) ist Novamet 900 (nicht Standard-Hycut-Familie) empfohlen. Hintergrund: Esteröl-Komponenten von Hycut können Verfärbung verursachen bei bestimmten Al-Legierungen mit Zinkanteil.",
    symptoms: ["Verfärbung bei Zn-haltigem Aluminium", "potenzielle Fleckbildung"],
    rootCause: "Aggressive Esteröl-Tenside reagieren mit Zink in Aluminiumlegierungen",
    workaround: "Wechsel zu Novamet 900 für stainfähige Legierungen",
    preventiveMeasure: "Vorab-Verträglichkeitstest mit Werkstoff-Probestück; geeignete KSS-Variante wählen",
    affectedMaterials: ["Zn-haltige Aluminium-Legierungen", "NE-Metalle"],
    affectedOperations: ["Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oemeta.com/us/products-services/product/novamet-900",
    sourceTitle: "NOVAMET 900 - Oemeta",
    sourceAuthor: "Oemeta",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hycut 100",
    manufacturerName: "Oemeta",
    category: "STABILITY",
    severity: "MEDIUM",
    title: "Mikrobielle Kontamination via Wasserqualität — Oemeta-Empfehlung: regelmäßige Wasserprüfung",
    description: "Oemeta dokumentiert: Mikroorganismen gelangen primär über Wasser und Luft in KSS-Systeme. Verunreinigte Rohrleitungen oder Anschlüsse sind häufige Eintrittspunkte. Hycut-Produkte erreichen lange Standzeit nur bei sauberer Wasserqualität und korrekter Konzentration; sonst klassische Mikrobenprobleme trotz formaldehyd-freier Konzeption.",
    symptoms: ["Mikrobenwachstum", "Geruch", "pH-Abfall"],
    rootCause: "Kontaminiertes Mischwasser oder Leitungssystem; Stillstandzeiten ohne Umpumpen",
    workaround: "Wasserqualität (Keimzahl) prüfen, Leitungen reinigen, Stillstands-Umwälzung",
    preventiveMeasure: "Quartalsweise Wasserqualitätsprüfung, Leitungs-Spülung, Dip-Slide-Tests monatlich",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oemeta.com/the-coolant-people/erfolgreiche-partnerschaften/gehring",
    sourceTitle: "Oemeta Hycut Anwendungsbericht - Mikrobiologie-Hinweis",
    sourceAuthor: "Oemeta",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hycut 50",
    manufacturerName: "Oemeta",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Hycut: Schaumprobleme bei weichem Wasser — Oemeta-Defoamer ADDI-PROX AF/C empfohlen",
    description: "Hycut-Linie ist auf Schaumarmut auch bei niedriger Wasserhärte ausgelegt, aber in Regionen mit sehr weichem Wasser (<8 °dH) kann Schaumbildung auftreten. Oemeta empfiehlt ADDI-PROX AF/C (kalziumbasierter Entschäumer) als langfristige Maßnahme statt Silikon-basierter Schnell-Lösungen, die Lackierprobleme verursachen können.",
    symptoms: ["Schaum bei weichem Wasser", "Überlauf am Tank"],
    rootCause: "Sehr weiches Wasser (<8 °dH) hat keine Mineralien zur Schaumdämpfung",
    workaround: "ADDI-PROX AF/C als langfristigen Entschäumer dosieren (kalziumbasiert)",
    preventiveMeasure: "Wasserhärte prüfen, ggf. leichte Aufhärtung auf 10-15 °dH oder Entschäumer dauerhaft mitführen",
    affectedMaterials: [],
    affectedOperations: ["Hochdruck-Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.techtool.com/products/oemeta-addi-prox-af-c",
    sourceTitle: "Oemeta ADDI-PROX AF/C Defoamer - Tech Tool",
    sourceAuthor: "Tech Tool",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Hycut Plus",
    manufacturerName: "Oemeta",
    category: "BIOLOGY",
    severity: "MEDIUM",
    title: "Anaerobe Bakterien ('Rotten egg' Geruch) durch Fremdölkappe im KSS-Tank",
    description: "Dokumentierter Mechanismus: Bahnöl/Hydraulikleckagen bilden auf KSS eine luftdichte Kappe, die Sauerstoff ausschließt — perfekter Nährboden für anaerobe Bakterien (Schwefelwasserstoff-Geruch). Hycut-Vorteil: Mineral-Fremdöle werden NICHT emulgiert (Esteröl-Emulgatoren sind selektiv) — Skimmer können sie leicht abscheiden.",
    symptoms: ["Schwefelwasserstoff-Geruch", "anaerobe Bakterienblüte", "schwarz-grünliche Trübung"],
    rootCause: "Mineralöl-Leckagen bilden Sauerstoffsperre auf KSS-Oberfläche",
    workaround: "Skimmer einsetzen, KSS umpumpen/belüften, Maschinenleckagen beheben",
    preventiveMeasure: "Bahn-/Hydraulikleckagen reparieren, Skimmer dauerhaft betreiben, Esteröl-KSS wählen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.techtool.com/pages/tramp-oil-removal",
    sourceTitle: "Tramp Oil - Causes & Removal - Tech Tool / Oemeta",
    sourceAuthor: "Tech Tool / Oemeta",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Sintogrind TT 22",
    manufacturerName: "oelheld",
    category: "TOOL_WEAR",
    severity: "LOW",
    title: "Synthetisches Schleiföl der TT-Serie: niedrige Verdunstung und Nebelbildung",
    description: "oelheld dokumentiert für Sintogrind-Schleiföle (TT, TTK): niedrige Verdunstungs- und Vernebelungsraten, extrem schaumarm, schubresistent und alterungsbeständig. Bei Vorgängerprodukten mit höherem Mineralölanteil traten häufig Aerosol-Probleme auf, die TRGS 900 (Arbeitsplatzgrenzwerte) überschritten.",
    symptoms: ["Aerosol-Bildung", "Ölnebel über Arbeitsplatz"],
    rootCause: "Mineralöl-basierte Schleiföle verdunsten/vernebeln stärker als synthetische PAO-Öle",
    workaround: "PAO-basierte Schleiföle (Sintogrind-Linie) statt Mineralöl-Basis",
    preventiveMeasure: "Synthetische Basisöle wählen, Maschinen-Absaugung dimensionieren, Arbeitsplatzgrenzwerte messen",
    affectedMaterials: ["Hartmetall", "HSS", "CBN", "PKD"],
    affectedOperations: ["Hochgeschwindigkeits-Schleifen", "Werkzeug-Schleifen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/produkte/schmierstoffe-metallbearbeitung/schleifoel/sintogrind-schleifoel/",
    sourceTitle: "SintoGrind - Schleiföl | oelheld",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Sintoplan SPN",
    manufacturerName: "oelheld",
    category: "RESIDUES",
    severity: "LOW",
    title: "Rückstandsfreie Verdampfung von Sintoplan-Stanz-/Ziehölen ab ca. 320°C",
    description: "oelheld dokumentiert für Sintoplan-Serie (Stanz-/Tiefziehöle): Basis aus synthetischen Kohlenwasserstoffen hoher Reinheit, die ab ca. 320 °C rückstandsfrei verdampfen. Im Vergleich zu Vorgängerprodukten +15 % Werkzeugstandzeit; deutlich reduzierte Adhäsionsneigung von Aluminium am Stanzwerkzeug.",
    symptoms: ["bei Vorgängern: Rückstände nach Wärmebehandlung", "Aluminium-Klebung am Werkzeug"],
    rootCause: "Mineralöl-basierte Stanzöle hinterlassen kohleartige Rückstände bei Wärmeprozessen",
    workaround: null,
    preventiveMeasure: "Synthetische rückstandsfreie Stanzöle der Sintoplan-Serie",
    affectedMaterials: ["Aluminium Al99.00-Al99.98", "AlMg1", "AlMg3", "AlMgSi1", "Stahl bis 18 mm"],
    affectedOperations: ["Stanzen", "Tiefziehen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/service/faq/wissenschaftliche-berichte/rueckstandsfreie-stanz-und-ziehoele-mit-hoher-viskositaet/",
    sourceTitle: "Rückstandsfreie Stanz- und Ziehöle - oelheld",
    sourceAuthor: "oelheld",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Rhenus FU 1100",
    manufacturerName: "Rhenus Lub",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Rhenus FU 700er/1000er-Serie auf Skin-Schutz und pH-Stabilität ausgelegt — Bewerbung 'Hautschutz aktiv'",
    description: "Rhenus dokumentiert für seine amin- und borsäurefreien FU-Serien (FU 700er, FU 1000er-Familien): aktive Hautschutz-Wirkung, niedrige Allergiepotenz, pH-stabile Pufferung. Hintergrund: ältere Generationen klassischer KSS verursachen dokumentiert Kontaktekzeme bei längerem Hautkontakt.",
    symptoms: ["bei Vorgänger-Generation: Hautekzem", "Allergiepotenzial"],
    rootCause: "Amine und Borsäure-Verbindungen in klassischen KSS — Allergiepotenzial",
    workaround: "Wahl amin-/borsäurefreier KSS, Hautschutzplan gem. TRGS 401",
    preventiveMeasure: "Modern formulierte FU-Reihe mit aktiv hautschützenden Komponenten",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/actively-protects-the-skin-even-with-use-of-coolants/",
    sourceTitle: "Actively protects the skin even with use of coolants - Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Rhenus FU 7600",
    manufacturerName: "Rhenus Lub",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Schaumvermeidung bei Hochdruck — Rhenus-Linie u.a. TS 421 wirbt mit fast keinem Schaum auch bei Weichwasser",
    description: "Rhenus dokumentiert: Schaumbildung steigt bei weichem Mischwasser. Hochdruck-optimierte Produkte (TS 421, FU 7600-Familie) sind so formuliert, dass Wasserhärte 'nur untergeordnete Rolle' spielt. Wichtig für Hochdruck-Anwendungen, wo Schaum sonst Drücke kollabieren lässt.",
    symptoms: ["bei Standard-KSS: Schaum bei Weichwasser unter Hochdruck"],
    rootCause: "Weiches Wasser fehlt mineralische Schaumdämpfung; Hochdruck verstärkt Schaumneigung",
    workaround: "Hochdruck-optimierte Rhenus-Variante (z.B. TS 421) statt Standard-KSS",
    preventiveMeasure: "Wasserhärte bestimmen, Hochdruck-formulierten KSS wählen",
    affectedMaterials: [],
    affectedOperations: ["Hochdruck-Zerspanung", "Tiefbohren"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/full-control-at-high-pressures-with-no-foam-2/",
    sourceTitle: "Full control at high pressures - with no foam | Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Rhenus FU MV 22",
    manufacturerName: "Rhenus Lub",
    category: "STABILITY",
    severity: "LOW",
    title: "Mikroemulsions-KSS — generelle Empfindlichkeit gegenüber Hartwasser-Salzen",
    description: "Allgemein dokumentiert: Mikroemulsions-KSS sind empfindlicher gegen Hartwasser-Salze (Calcium, Magnesium) als klassische Emulsionen. Bei Wasserhärten >25 °dH können Ablagerungen, verkürzte Standzeit und Filtrationsprobleme auftreten. Rhenus-Datenblätter geben Wasserhärtebereich an; Außerhalb-Betrieb senkt Standzeit.",
    symptoms: ["Ablagerungen", "Filtrationsprobleme", "verkürzte Standzeit"],
    rootCause: "Mikroemulsionen mit hohem Tensidanteil bilden Ca/Mg-Seifen bei Hartwasser",
    workaround: "Wasserenthärtung, regelmäßige Filterwartung, Wasserhärte-Monitoring",
    preventiveMeasure: "Wasserhärte vor Inbetriebnahme prüfen, ggf. Wasseraufbereitung",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.rhenuslub.de/en/metalworking-fluids/water-miscible-metalworking-fluids/",
    sourceTitle: "Water-Miscible Metalworking Fluids - Rhenus Lub",
    sourceAuthor: "Rhenus Lub",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Hycut DLR",
    manufacturerName: "Oemeta",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Oemeta-Produktfamilie: spezielle Inhaltsstoff-Kombinationen für Aerospace-Materialien (Titan, Inconel)",
    description: "Oemeta-Dokumentation: Für Superalloy-Bearbeitung empfiehlt Hersteller spezifische Produkte: NOVAMET 770 AE für Aerospace-Toleranzen, NOVAMET 910 B für hohe Filmstärke bei Superalloys. Hycut-Linie deckt aggressive Cuts ab. Falsche Produktwahl führt zu Werkzeug-Galling (Titan klebt am Werkzeug), Hitzestau (geringe thermische Leitfähigkeit von Inconel) und vorzeitigem Werkzeugverschleiß.",
    symptoms: ["Werkzeug-Galling bei Titan", "Hitzestau bei Inconel", "vorzeitiger Werkzeugverschleiß"],
    rootCause: "Inconel niedrige Wärmeleitfähigkeit + hohe Schnittkraft; Titan neigt zu Klebspänen",
    workaround: "Anwendungsspezifischen Hycut-/Novamet-Subtyp wählen, Konzentration anheben (8-10 %)",
    preventiveMeasure: "Materialbezogene KSS-Auswahl: Hycut für aggressive Cuts, Novamet für Toleranz-Anforderungen",
    affectedMaterials: ["Titan", "Inconel", "Superalloys"],
    affectedOperations: ["Aerospace-Zerspanung", "Hochleistungs-Bearbeitung"],
    reportedConcentration: 8,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oemeta.com/us/industry-sectors/aerospace",
    sourceTitle: "Metalworking fluid for the aerospace industry - Oemeta",
    sourceAuthor: "Oemeta",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Mecagreen 550",
    manufacturerName: "Oemeta",
    category: "COMPATIBILITY",
    severity: "MEDIUM",
    title: "Mecagreen 550 mag kein Kupfer — Coolant-Trennung mit dunkelblauer Phase",
    description: "Practical-Machinist-Anwender berichtet für Mecagreen 550 (Condat): 'does not seem to like the copper that we machine' — KSS trennt sich, dunkelblaue Flüssigkeit sammelt sich an der Oberfläche, Skimmer zieht sie ab, hoher Abfall-KSS. Mecagreen 550 ist auf Vegetable-Ester-Basis für Aerospace-Alu/Stahl/Titan ausgelegt — nicht für Kupfer.",
    symptoms: ["Coolant-Trennung", "dunkelblaue Phase auf Oberfläche", "hoher KSS-Verbrauch"],
    rootCause: "Pflanzenester-Basis reagiert mit Kupfer-Ionen; ungeeignet für Kupferbearbeitung",
    workaround: "Bei Kupferbearbeitung anderen KSS (mit Buntmetall-Inhibitor) verwenden",
    preventiveMeasure: "Mecagreen 550 nur für freigegebene Materialien (Al, Stahl, Ti), nicht für Cu/Cu-Legierungen",
    affectedMaterials: ["Kupfer", "Kupferlegierungen"],
    affectedOperations: ["Drehen", "Fräsen"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/forum/threads/coolant-price-gone-up-50-in-12-months-is-this-normal-mecagreen-550.372371/",
    sourceTitle: "Mecagreen 550 - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Mecagreen 550",
    manufacturerName: "Oemeta",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Rost-Probleme nach >12 Monaten Einsatz von Mecagreen 500/550 — schlechter Support",
    description: "Practical-Machinist-Anwender berichtet: Nach >1 Jahr Einsatz von Mecagreen 500 traten Rostprobleme an Werkstücken auf. Außerdem 'not receiving much help from Condat' beim Problem-Lösen.",
    symptoms: ["Flugrost an Werkstücken nach langer Standzeit", "Korrosion"],
    rootCause: "Mögliche pH-Abfall oder Verbrauch der Korrosionsschutz-Additive über Zeit",
    workaround: "pH-Wert und Konzentration messen; ggf. Korrosionsschutz-Booster oder kompletten KSS-Wechsel",
    preventiveMeasure: "Vierteljährlicher KSS-Check mit pH, Konzentration, Korrosionsschutz-Test (IP 287)",
    affectedMaterials: ["Stahl"],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "FORUM",
    sourceUrl: "https://www.practicalmachinist.com/vb/general/mecagreen-500-condat-any-count-234589/",
    sourceTitle: "Mecagreen 500 from Condat - Practical Machinist",
    sourceAuthor: "Practical Machinist Community",
    sourceDate: "2018-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Rhenus FU 51",
    manufacturerName: "Rhenus Lub",
    category: "FOAM",
    severity: "MEDIUM",
    title: "Allgemeine KSS-Schaumursachen — Pennine Lubricants-Leitfaden mit 8 Hauptursachen",
    description: "Branchenleitfaden Pennine Lubricants dokumentiert 8 Hauptursachen für KSS-Schaum, relevant für alle wassermischbaren KSS inkl. Rhenus FU 51: hohe Konzentration, weiches Wasser, Lufteinzug an Pumpen, Tankfüllstand <75 %, falsche KSS-Wahl für Hochdruck, kontaminierte Filter, Tankablagerungen, Pumpenposition. Lösung: Konzentration auf Hersteller-Minimum reduzieren.",
    symptoms: ["Schaum", "Maschinenstopps", "Spritzer aus Tank"],
    rootCause: "Mehrere mögliche Ursachen — systematisch durchgehen",
    workaround: "Konzentration prüfen/reduzieren, Tankfüllstand erhöhen, Lufteinzug eliminieren",
    preventiveMeasure: "Konzentrations-Mindestwert einhalten, Filter wechseln, Pumpenpositionen prüfen",
    affectedMaterials: [],
    affectedOperations: ["Hochdruck-Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "DISTRIBUTOR",
    sourceUrl: "https://www.penninelubricants.co.uk/news/8-reasons-your-coolant-is-foaming-and-how-to-stop-it/",
    sourceTitle: "8 Reasons your Coolant is Foaming - Pennine Lubricants",
    sourceAuthor: "Pennine Lubricants",
    sourceDate: "2022-01-01",
    language: "EN",
    isOfficial: false
  },
  {
    productName: "Aquamet HD 10",
    manufacturerName: "Eni",
    category: "STABILITY",
    severity: "LOW",
    title: "Aquamet LMK 2020 Plus: pH 9.7-9.9 bei 5 % — dauerhafte Pufferung als Standzeit-Treiber",
    description: "Eni dokumentiert für Aquamet LMK 2020 Plus: pH-Wert (5 %) 9.7-9.9 mit 'außergewöhnlicher pH-Wert-Stabilität' durch permanente Pufferung. Bedeutung: pH-Drift ist häufigste Ursache für KSS-Versagen (Korrosion bei <8.5, Hautirritation bei >9.5). Stabile Pufferung verlängert Standzeit signifikant.",
    symptoms: ["bei pH-instabilen KSS: Korrosion oder Hautreizung mit Zeit"],
    rootCause: "Konventionelle KSS verlieren Pufferkapazität bei CO2-Aufnahme und Mikrobenwachstum",
    workaround: null,
    preventiveMeasure: "Wahl von KSS mit dokumentierter Langzeit-pH-Stabilität; wöchentliche pH-Kontrolle",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: 9.8,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.baumannoil.de/eni-aquamet-lmk-2020",
    sourceTitle: "Eni aquamet LMK 2020 Plus",
    sourceAuthor: "Eni / Baumannoil",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Aquamet HD 10",
    manufacturerName: "Eni",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Aquamet LMK 2020 Plus: 4 % Mindestkonzentration für Biostabilität und Korrosionsschutz",
    description: "Eni dokumentiert: 'Bereits Einsatzkonzentrationen von 4 % bieten eine sehr gute Biostabilität und einen sehr guten Korrosionsschutz.' Unterhalb 4 % drohen Mikrobenprobleme und Korrosion. 'Geringe Austragverluste reduzieren Nachsatzmengen' — typisches Pflege-Problem ist Unterdosierung durch hohen Austrag.",
    symptoms: ["bei <4 % Konzentration: Mikrobenwachstum, Korrosion"],
    rootCause: "Unterdosierung — Austragverluste werden durch reines Wasser kompensiert",
    workaround: "Konzentrat nachdosieren bis ≥4 %; nur mit Konzentrat nachfüllen, nie nur Wasser",
    preventiveMeasure: "Refraktometer-tägliche Kontrolle, Konzentrat-only-Nachfüllregel",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: 4,
    reportedPh: 9.8,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://oilproducts.eni.com/de_DE/news/aquamet-lmk",
    sourceTitle: "Eni aquamet LMK - ACT | Eni Oil Products",
    sourceAuthor: "Eni / Enilive",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Eni Aquamet KS",
    manufacturerName: "Eni",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Stainless Steel benötigt 5-8 % Konzentration für optimale Schmierung",
    description: "Eni dokumentiert: Für Edelstahl-Bearbeitung mit Aquamet-Linie sind 5-8 % Konzentration erforderlich. Bei zu niedriger Konzentration: Werkzeugverschleiß steigt, Aufbauschneiden, Oberflächengüte sinkt. Bei zu hoher Konzentration: Schaum, Hautirritation.",
    symptoms: ["bei <5 %: Aufbauschneidenbildung", "schlechte Oberfläche", "Werkzeugverschleiß"],
    rootCause: "Edelstahl erfordert höhere Schmierfähigkeit als Standardstahl",
    workaround: "Konzentration für Edelstahl auf 5-8 % anheben",
    preventiveMeasure: "Materialbezogene Konzentrationseinstellung; bei Mix-Betrieb auf höhere Werte fahren",
    affectedMaterials: ["Edelstahl", "Stainless Steel"],
    affectedOperations: ["Drehen", "Fräsen", "Bohren"],
    reportedConcentration: 6,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://oilproducts.eni.com/en_GB/products/industrial-lubricants/metalworking-oils/water-miscible-cooling-lubricants/soluble-cutting-oils-with-transparent-emulsion",
    sourceTitle: "Water miscible cooling lubricants - Eni Oil Products",
    sourceAuthor: "Eni",
    sourceDate: "2023-01-01",
    language: "EN",
    isOfficial: true
  },
  {
    productName: "Sintilo 11/4",
    manufacturerName: "oelheld",
    category: "CORROSION",
    severity: "MEDIUM",
    title: "Allgemeine Korrosionsproblematik bei wassermischbaren KSS — Maßnahmenkatalog oelheld",
    description: "oelheld dokumentiert für die gesamte Sintilo-Linie Korrosionsmaßnahmen: pH-Wert >8.8 halten, Konzentration über Mindestwert (typ. 5 %), Stillstandzeiten mit Umpumpen überbrücken, Wasserhärte 10-25 °dH ideal. Bei dauerhaftem Stillstand: zusätzlicher Korrosionsschutz wie LubTool 6000 Spray.",
    symptoms: ["Flugrost am Maschinenbett", "Korrosion an Werkstücken bei Stillstand"],
    rootCause: "pH-Drift, Unterdosierung, Stillstand ohne Umwälzung",
    workaround: "pH-Booster, Konzentratnachschub, Umpumpen während Wochenende",
    preventiveMeasure: "Timer-gesteuerte Umwälzung an Wochenenden, Korrosionsschutz-Spray bei längeren Stillständen",
    affectedMaterials: ["Stahl", "Guss"],
    affectedOperations: [],
    reportedConcentration: 5,
    reportedPh: 8.8,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://www.oelheld.com/de/produkte/korrosionsschutz-reiniger/lubtool-6000-korrosionsschutzspray/",
    sourceTitle: "LubTool 6000 - Korrosionsschutzspray | oelheld",
    sourceAuthor: "oelheld",
    sourceDate: "2023-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hycut 765",
    manufacturerName: "Oemeta",
    category: "REGULATORY",
    severity: "MEDIUM",
    title: "Hycut-Linie inzwischen bor- und formaldehydfrei — wichtig für Gesundheitsschutz",
    description: "Oemeta hat die Hycut-Linie auf 'bor- und formaldehydfrei' umgestellt. Hintergrund: Borsäure ist als reproduktionstoxisch (CMR Kat. 1B) eingestuft, Formaldehyd-Abspalter als Karzinogen Kat. 1B. Neue Hycut-Generation erfüllt strengste Anforderungen ohne Performance-Verlust. Anwender mit altem Hycut sollten auf neue Generation umstellen.",
    symptoms: [],
    rootCause: "Klassische KSS-Inhaltsstoffe (Borsäure, Formaldehyd) zunehmend als CMR eingestuft",
    workaround: null,
    preventiveMeasure: "Wechsel auf bor-/formaldehydfreie Hycut-Generation; SDB bei Lieferung prüfen",
    affectedMaterials: [],
    affectedOperations: [],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "MANUFACTURER",
    sourceUrl: "https://de.oemeta.com/bor-und-formaldehydfreie-kuehlschmierstoffe/",
    sourceTitle: "Bor- und formaldehydfreie Kühlschmierstoffe - Oemeta Deutschland",
    sourceAuthor: "Oemeta",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: true
  },
  {
    productName: "Hycut 100",
    manufacturerName: "Oemeta",
    category: "PERFORMANCE",
    severity: "LOW",
    title: "Anwendungsbericht Rohde & Schwarz: Novamet 910 als Alternative zum Hycut für stain-anfällige Werkstoffe",
    description: "Oemeta dokumentiert Rohde-&-Schwarz-Case: Novamet 910 statt Hycut für hohe Performance, niedrigen Verbrauch und gute Hautverträglichkeit. Hintergrund: Bei stain-anfälligen Aluminium-Legierungen (mit Zn) ist Novamet-Linie besser als Hycut. Hycut bleibt erste Wahl bei aggressiver Zerspanung.",
    symptoms: ["bei Hycut mit Zn-Alu: potenzielle Verfärbung"],
    rootCause: "Esteröl-Hycut reagiert mit Zn-Komponenten von Aluminium-Legierungen",
    workaround: "Werkstoffspezifische KSS-Wahl: Hycut für Zerspanung, Novamet für stain-empfindliche Werkstoffe",
    preventiveMeasure: "Werkstoff-Verträglichkeitstest vor KSS-Wahl",
    affectedMaterials: ["Aluminium mit Zn", "rostfreie Stähle"],
    affectedOperations: ["Zerspanung"],
    reportedConcentration: null,
    reportedPh: null,
    sourceType: "CASE_STUDY",
    sourceUrl: "https://www.oemeta.com/fileadmin/redakteure/bilder/4_Informationen/Downloads/Anwendungsberichte/oemeta-case-study-rhode-schwarz-de.pdf",
    sourceTitle: "Oemeta Anwendungsbericht Rohde & Schwarz",
    sourceAuthor: "Oemeta",
    sourceDate: "2022-01-01",
    language: "DE",
    isOfficial: true
  }
];
